-- ============================================================================
-- MUSKY DOSE — UNIVERSAL MEDIA ASSETS SCHEMA MIGRATION (PHASE 3.2)
--
-- NATURE: Strictly Additive & Idempotent (No DROP, No TRUNCATE)
--
-- PURPOSE:
-- Establishes the canonical relational foundation for all visual assets across
-- PRODUCT, CATEGORY, GUIDE, KNOWLEDGE, BRAND, and MARKETING entities.
-- Features:
-- 1. Dual AI/Manual provenance tracking with human governance (suggested/approved/rejected/archived).
-- 2. Anti-hallucination visual context and approved facts payload (JSONB).
-- 3. Content deduplication via SHA-256 file hashes.
-- 4. Manual-primary locking (is_locked) to guarantee AI never demotes human decisions.
-- 5. Row Level Security (RLS) public SELECT gating on status = 'approved'.
-- ============================================================================

-- 1. CREATE TABLE: public.media_assets
CREATE TABLE IF NOT EXISTS public.media_assets (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('PRODUCT', 'CATEGORY', 'GUIDE', 'KNOWLEDGE', 'BRAND', 'MARKETING')),
  entity_id TEXT, -- Nullable for global / brand assets
  url TEXT NOT NULL,
  storage_path TEXT,
  storage_bucket TEXT NOT NULL DEFAULT 'product-images',
  file_hash TEXT, -- SHA-256 hash for binary deduplication
  file_name TEXT,
  mime_type TEXT NOT NULL DEFAULT 'image/webp',
  file_size_bytes INTEGER,
  width INTEGER,
  height INTEGER,
  aspect_ratio TEXT DEFAULT '1:1',
  role TEXT NOT NULL DEFAULT 'GALLERY' CHECK (role IN (
    'PRIMARY',
    'GALLERY',
    'PACKAGING',
    'LIFESTYLE',
    'DETAIL',
    'USAGE',
    'INGREDIENTS',
    'HERO',
    'OG_SOCIAL',
    'ICON'
  )),
  source TEXT NOT NULL DEFAULT 'MANUAL_UPLOAD' CHECK (source IN (
    'MANUAL_UPLOAD',
    'AI_GENERATED',
    'EXTERNAL_IMPORT',
    'SYSTEM_FALLBACK'
  )),
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN (
    'suggested',
    'approved',
    'rejected',
    'archived'
  )),
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  title TEXT,
  alt_text TEXT,
  caption TEXT,
  visual_context JSONB DEFAULT '{}'::jsonb,
  ai_metadata JSONB DEFAULT '{}'::jsonb,
  sort_order INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. INDEXES FOR PERFORMANCE, FILTERING & DEDUPLICATION
CREATE INDEX IF NOT EXISTS idx_media_assets_entity 
  ON public.media_assets (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_media_assets_role_status 
  ON public.media_assets (entity_type, entity_id, role, status);

CREATE INDEX IF NOT EXISTS idx_media_assets_file_hash 
  ON public.media_assets (file_hash);

CREATE INDEX IF NOT EXISTS idx_media_assets_status 
  ON public.media_assets (status);

CREATE INDEX IF NOT EXISTS idx_media_assets_sort_order 
  ON public.media_assets (sort_order ASC);

CREATE INDEX IF NOT EXISTS idx_media_assets_created_at 
  ON public.media_assets (created_at DESC);

-- 3. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read approved media_assets" ON public.media_assets;

-- Public read access strictly for APPROVED media assets
CREATE POLICY "Allow public read approved media_assets"
ON public.media_assets FOR SELECT
USING (status = 'approved');

-- Service role bypass is automatic for administrative CRUD operations.

DROP POLICY IF EXISTS "Allow service_role full access on media_assets" ON public.media_assets;
CREATE POLICY "Allow service_role full access on media_assets"
ON public.media_assets FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated read all media_assets" ON public.media_assets;
CREATE POLICY "Allow authenticated read all media_assets"
ON public.media_assets FOR SELECT
TO authenticated
USING (true);

-- 4. IDEMPOTENT CATALOG MEDIA ASSETS BACKFILL
INSERT INTO public.media_assets (
  id,
  entity_type,
  entity_id,
  url,
  storage_path,
  storage_bucket,
  file_hash,
  file_name,
  mime_type,
  file_size_bytes,
  width,
  height,
  aspect_ratio,
  role,
  source,
  status,
  is_locked,
  title,
  alt_text,
  caption,
  visual_context,
  ai_metadata,
  sort_order,
  created_at,
  updated_at
)
VALUES
(
  'med-product-prod-4-0',
  'PRODUCT',
  'prod-4',
  'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=1000&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Herbal Amla Reetha Shikakai & Hibiscus Hair Pack - Image 1',
  'Herbal Amla Reetha Shikakai & Hibiscus Hair Pack photo',
  NULL,
  '{"productId":"prod-4","productName":"Herbal Amla Reetha Shikakai & Hibiscus Hair Pack","slug":"herbal-amla-reetha-shikakai-hair-pack"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-multani-mitti-0',
  'PRODUCT',
  'prod-multani-mitti',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Rajasthani Multani Mitti (Fuller''s Earth) - Image 1',
  'Pure Rajasthani Multani Mitti (Fuller''s Earth) photo',
  NULL,
  '{"productId":"prod-multani-mitti","productName":"Pure Rajasthani Multani Mitti (Fuller''s Earth)","slug":"pure-rajasthani-multani-mitti-fullers-earth"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-amla-powder-0',
  'PRODUCT',
  'prod-amla-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Organic Amla Powder - Image 1',
  'Pure Organic Amla Powder photo',
  NULL,
  '{"productId":"prod-amla-powder","productName":"Pure Organic Amla Powder","slug":"pure-organic-amla-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-bhringraj-powder-0',
  'PRODUCT',
  'prod-bhringraj-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Bhringraj (Eclipta Alba) Powder - Image 1',
  'Pure Bhringraj (Eclipta Alba) Powder photo',
  NULL,
  '{"productId":"prod-bhringraj-powder","productName":"Pure Bhringraj (Eclipta Alba) Powder","slug":"pure-bhringraj-eclipta-alba-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-peppermint-oil-0',
  'PRODUCT',
  'prod-peppermint-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Peppermint Essential Oil - Image 1',
  'Pure Peppermint Essential Oil photo',
  NULL,
  '{"productId":"prod-peppermint-oil","productName":"Pure Peppermint Essential Oil","slug":"pure-peppermint-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-brahmi-powder-0',
  'PRODUCT',
  'prod-brahmi-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Brahmi (Bacopa Monnieri) Powder - Image 1',
  'Pure Brahmi (Bacopa Monnieri) Powder photo',
  NULL,
  '{"productId":"prod-brahmi-powder","productName":"Pure Brahmi (Bacopa Monnieri) Powder","slug":"pure-brahmi-bacopa-monnieri-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-jatamansi-powder-0',
  'PRODUCT',
  'prod-jatamansi-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Jatamansi (Spikenard) Root Powder - Image 1',
  'Pure Jatamansi (Spikenard) Root Powder photo',
  NULL,
  '{"productId":"prod-jatamansi-powder","productName":"Pure Jatamansi (Spikenard) Root Powder","slug":"pure-jatamansi-spikenard-root-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-lavender-oil-0',
  'PRODUCT',
  'prod-lavender-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Lavender Essential Oil - Image 1',
  'Pure Lavender Essential Oil photo',
  NULL,
  '{"productId":"prod-lavender-oil","productName":"Pure Lavender Essential Oil","slug":"pure-lavender-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-rosemary-oil-0',
  'PRODUCT',
  'prod-rosemary-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Rosemary Essential Oil - Image 1',
  'Pure Rosemary Essential Oil photo',
  NULL,
  '{"productId":"prod-rosemary-oil","productName":"Pure Rosemary Essential Oil","slug":"pure-rosemary-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-beetroot-powder-0',
  'PRODUCT',
  'prod-beetroot-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Natural Beetroot Powder - Image 1',
  'Pure Natural Beetroot Powder photo',
  NULL,
  '{"productId":"prod-beetroot-powder","productName":"Pure Natural Beetroot Powder","slug":"pure-natural-beetroot-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-5-0',
  'PRODUCT',
  'prod-5',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Sojat Damask Rose Water Spray - Image 1',
  'Pure Sojat Damask Rose Water Spray photo',
  NULL,
  '{"productId":"prod-5","productName":"Pure Sojat Damask Rose Water Spray","slug":"pure-sojat-damask-rose-water-spray"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-eucalyptus-nilgiri-oil-0',
  'PRODUCT',
  'prod-eucalyptus-nilgiri-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Eucalyptus (Nilgiri) Essential Oil - Image 1',
  'Pure Eucalyptus (Nilgiri) Essential Oil photo',
  NULL,
  '{"productId":"prod-eucalyptus-nilgiri-oil","productName":"Pure Eucalyptus (Nilgiri) Essential Oil","slug":"pure-eucalyptus-nilgiri-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-sandalwood-powder-0',
  'PRODUCT',
  'prod-sandalwood-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Natural Sandalwood (Chandan) Powder - Image 1',
  'Pure Natural Sandalwood (Chandan) Powder photo',
  NULL,
  '{"productId":"prod-sandalwood-powder","productName":"Pure Natural Sandalwood (Chandan) Powder","slug":"pure-natural-sandalwood-chandan-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-tea-tree-oil-0',
  'PRODUCT',
  'prod-tea-tree-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Tea Tree Essential Oil - Image 1',
  'Pure Tea Tree Essential Oil photo',
  NULL,
  '{"productId":"prod-tea-tree-oil","productName":"Pure Tea Tree Essential Oil","slug":"pure-tea-tree-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-reetha-powder-0',
  'PRODUCT',
  'prod-reetha-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Natural Reetha (Soapnut) Powder - Image 1',
  'Pure Natural Reetha (Soapnut) Powder photo',
  NULL,
  '{"productId":"prod-reetha-powder","productName":"Pure Natural Reetha (Soapnut) Powder","slug":"pure-natural-reetha-soapnut-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-shikakai-powder-0',
  'PRODUCT',
  'prod-shikakai-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Ayurvedic Shikakai Powder - Image 1',
  'Pure Ayurvedic Shikakai Powder photo',
  NULL,
  '{"productId":"prod-shikakai-powder","productName":"Pure Ayurvedic Shikakai Powder","slug":"pure-ayurvedic-shikakai-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-hibiscus-powder-0',
  'PRODUCT',
  'prod-hibiscus-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Hibiscus Flower Petal Powder - Image 1',
  'Pure Hibiscus Flower Petal Powder photo',
  NULL,
  '{"productId":"prod-hibiscus-powder","productName":"Pure Hibiscus Flower Petal Powder","slug":"pure-hibiscus-flower-petal-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-moringa-powder-0',
  'PRODUCT',
  'prod-moringa-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Organic Moringa Leaf Powder - Image 1',
  'Pure Organic Moringa Leaf Powder photo',
  NULL,
  '{"productId":"prod-moringa-powder","productName":"Pure Organic Moringa Leaf Powder","slug":"pure-organic-moringa-leaf-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-fenugreek-methi-powder-0',
  'PRODUCT',
  'prod-fenugreek-methi-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Fenugreek (Methi) Seed Powder - Image 1',
  'Pure Fenugreek (Methi) Seed Powder photo',
  NULL,
  '{"productId":"prod-fenugreek-methi-powder","productName":"Pure Fenugreek (Methi) Seed Powder","slug":"pure-fenugreek-methi-seed-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-curry-leaf-powder-0',
  'PRODUCT',
  'prod-curry-leaf-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Natural Curry Leaf Powder - Image 1',
  'Pure Natural Curry Leaf Powder photo',
  NULL,
  '{"productId":"prod-curry-leaf-powder","productName":"Pure Natural Curry Leaf Powder","slug":"pure-natural-curry-leaf-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-lemongrass-oil-0',
  'PRODUCT',
  'prod-lemongrass-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Lemongrass Essential Oil - Image 1',
  'Pure Lemongrass Essential Oil photo',
  NULL,
  '{"productId":"prod-lemongrass-oil","productName":"Pure Lemongrass Essential Oil","slug":"pure-lemongrass-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-clove-oil-0',
  'PRODUCT',
  'prod-clove-oil',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Clove Essential Oil - Image 1',
  'Pure Clove Essential Oil photo',
  NULL,
  '{"productId":"prod-clove-oil","productName":"Pure Clove Essential Oil","slug":"pure-clove-essential-oil"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-3-0',
  'PRODUCT',
  'prod-3',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1000&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Musky Dose Special Bridal Mehendi Cones (Pack of 12) - Image 1',
  'Musky Dose Special Bridal Mehendi Cones (Pack of 12) photo',
  NULL,
  '{"productId":"prod-3","productName":"Musky Dose Special Bridal Mehendi Cones (Pack of 12)","slug":"musky-dose-special-bridal-mehendi-cones"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-product-prod-neem-powder-0',
  'PRODUCT',
  'prod-neem-powder',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '1:1',
  'PRIMARY',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Pure Natural Neem Leaf Powder - Image 1',
  'Pure Natural Neem Leaf Powder photo',
  NULL,
  '{"productId":"prod-neem-powder","productName":"Pure Natural Neem Leaf Powder","slug":"pure-natural-neem-leaf-powder"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-category-cat-1-0',
  'CATEGORY',
  'cat-1',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '16:9',
  'HERO',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Henna Category Banner',
  'Henna banner',
  NULL,
  '{"categoryId":"cat-1","categoryName":"Henna","slug":"henna"}'::jsonb,
  '{}'::jsonb,
  1,
  NOW(),
  NOW()
),
(
  'med-category-cat-2-0',
  'CATEGORY',
  'cat-2',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '16:9',
  'HERO',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Hair Care Category Banner',
  'Hair Care banner',
  NULL,
  '{"categoryId":"cat-2","categoryName":"Hair Care","slug":"hair-care"}'::jsonb,
  '{}'::jsonb,
  2,
  NOW(),
  NOW()
),
(
  'med-category-cat-3-0',
  'CATEGORY',
  'cat-3',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '16:9',
  'HERO',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Face Care Category Banner',
  'Face Care banner',
  NULL,
  '{"categoryId":"cat-3","categoryName":"Face Care","slug":"face-care"}'::jsonb,
  '{}'::jsonb,
  3,
  NOW(),
  NOW()
),
(
  'med-category-cat-4-0',
  'CATEGORY',
  'cat-4',
  'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '16:9',
  'HERO',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Herbal Products Category Banner',
  'Herbal Products banner',
  NULL,
  '{"categoryId":"cat-4","categoryName":"Herbal Products","slug":"herbal-products"}'::jsonb,
  '{}'::jsonb,
  4,
  NOW(),
  NOW()
),
(
  'med-category-cat-1787586348109-0',
  'CATEGORY',
  'cat-1787586348109',
  '/images/fallback.svg',
  NULL,
  'product-images',
  NULL,
  NULL,
  'image/webp',
  NULL,
  NULL,
  NULL,
  '16:9',
  'HERO',
  'MANUAL_UPLOAD',
  'approved',
  TRUE,
  'Beauty Category Banner',
  'Beauty banner',
  NULL,
  '{"categoryId":"cat-1787586348109","categoryName":"Beauty","slug":"beauty-category"}'::jsonb,
  '{}'::jsonb,
  5,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  url = EXCLUDED.url,
  title = EXCLUDED.title,
  alt_text = EXCLUDED.alt_text,
  role = EXCLUDED.role,
  status = EXCLUDED.status,
  is_locked = EXCLUDED.is_locked,
  updated_at = NOW();
