// ============================================================
// MUSKY DOSE — UNIVERSAL AUTO-GUIDE GENERATION ENGINE
// Truth-Grounded, Taxonomy-Aware, SEO-Optimized Product Guides
// ============================================================

import { Product, ProductGuide, ProductGuideFAQ } from '@/lib/types';
import { deriveProductIntelligence, UniversalProductIntelligence } from './product-intelligence';
import { generateProductKeywordUniverseV2, ProductKeywordUniverseV2 } from './keyword-universe-engine';
import {
  evaluateGuideOpportunities,
  generateUniversalGuideDraft,
  GuideFamily,
  GuideOpportunity,
  UniversalGuideDraft,
} from './guide-opportunity-engine';

export {
  deriveProductIntelligence,
  generateProductKeywordUniverseV2,
  evaluateGuideOpportunities,
  generateUniversalGuideDraft,
};
export type { UniversalProductIntelligence, ProductKeywordUniverseV2, GuideFamily, GuideOpportunity, UniversalGuideDraft };

export function sanitizeSlug(input: string): string {
  if (!input || typeof input !== 'string') return '';
  return input
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

export interface AutoGeneratedGuideDraft {
  title: string;
  slug: string;
  shortIntro: string;
  category: string;
  readTime: string;
  overview: string;
  whatIsThis: string;
  keyBenefits: string[];
  ingredients: string[];
  whoShouldUse: string;
  whoShouldAvoid: string;
  howToUse: string;
  quantityPreparation: string;
  storageInstructions: string;
  importantNotes: string;
  content: string;
  faqs: ProductGuideFAQ[];
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  longTailKeywords: string[];
  associatedProductId: string;
  relatedProductIds: string[];
  coverImage: string;
  needsReview: boolean;
  missingFields: string[];
}

/**
 * Derives a complete, truth-grounded guide draft from a Product.
 * Uses botanical entity taxonomy and product metadata without fabricating claims.
 */
export function deriveProductGuide(
  product: Partial<Product>,
  allProducts: Product[] = [],
  allGuides: ProductGuide[] = []
): AutoGeneratedGuideDraft {
  const coverImage = (Array.isArray(product.images) && product.images[0]) || '/images/fallback.svg';
  const productId = product.id || '';

  // 1. Universal Product Intelligence Layer (handles blends, oils, forms, terroirs)
  const intel = deriveProductIntelligence(product, allProducts);

  // 2. Structured 20-Category Keyword Universe (A–T, GSC integrated)
  const kwUniverse = generateProductKeywordUniverseV2({ intelligence: intel });

  // 3. Dynamic Guide Opportunity Evaluation (14 Families, relevance suppression)
  const opps = evaluateGuideOpportunities(intel, allGuides);

  // 4. Determine Primary Guide Family for Headless / Default Draft
  const defaultOpp = opps.find((o) => o.family === 'PRODUCT_OVERVIEW') || opps[0];
  const primaryFamily = defaultOpp?.family || 'PRODUCT_OVERVIEW';

  // 5. Universal Truth-Grounded Template Draft Generation
  const draft = generateUniversalGuideDraft({
    intelligence: intel,
    family: primaryFamily,
    keywordUniverse: kwUniverse,
    allProducts,
    productId,
    coverImage,
  });

  return {
    title: draft.title,
    slug: draft.slug,
    shortIntro: draft.shortIntro,
    category: draft.category,
    readTime: draft.readTime,
    overview: draft.overview,
    whatIsThis: draft.whatIsThis,
    keyBenefits: draft.keyBenefits,
    ingredients: draft.ingredients,
    whoShouldUse: draft.whoShouldUse,
    whoShouldAvoid: draft.whoShouldAvoid,
    howToUse: draft.howToUse,
    quantityPreparation: draft.quantityPreparation,
    storageInstructions: draft.storageInstructions,
    importantNotes: draft.importantNotes,
    content: draft.content,
    faqs: draft.faqs,
    seoTitle: draft.seoTitle,
    seoDescription: draft.seoDescription,
    seoKeywords: draft.seoKeywords,
    primaryKeyword: draft.primaryKeyword,
    secondaryKeywords: draft.secondaryKeywords,
    longTailKeywords: draft.longTailKeywords,
    associatedProductId: draft.associatedProductId,
    relatedProductIds: draft.relatedProductIds,
    coverImage: draft.coverImage,
    needsReview: draft.needsReview,
    missingFields: draft.reviewReasons,
  };
}
