// ============================================================
// MUSKY DOSE — UNIVERSAL AUTO-GUIDE GENERATION ENGINE
// Truth-Grounded, Taxonomy-Aware, SEO-Optimized Product Guides
// ============================================================

import { Product, ProductGuide, ProductGuideFAQ } from '@/lib/types';
import { BOTANICAL_SEARCH_ENTITIES, detectProductEntity, SearchEntity } from './entities';

export function sanitizeSlug(input: string): string {
  if (!input || typeof input !== 'string') return '';
  return input
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

export interface AutoGeneratedGuideDraft {
  title: string;
  slug: string;
  shortIntro: string;
  category: string;
  readTime: string;
  overview: string;
  whatIsThis: string;
  keyBenefits: string[];
  ingredients: string[];
  whoShouldUse: string;
  whoShouldAvoid: string;
  howToUse: string;
  quantityPreparation: string;
  storageInstructions: string;
  importantNotes: string;
  content: string;
  faqs: ProductGuideFAQ[];
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  longTailKeywords: string[];
  associatedProductId: string;
  relatedProductIds: string[];
  coverImage: string;
  needsReview: boolean;
  missingFields: string[];
}

/**
 * Derives a complete, truth-grounded guide draft from a Product.
 * Uses botanical entity taxonomy and product metadata without fabricating claims.
 */
export function deriveProductGuide(
  product: Partial<Product>,
  allProducts: Product[] = [],
  allGuides: ProductGuide[] = []
): AutoGeneratedGuideDraft {
  const name = (product.name || 'Botanical Product').trim();
  const rawSlug = sanitizeSlug(product.slug || name);
  const detectedEntity = detectProductEntity(product);
  const entityId = detectedEntity?.id || 'UNKNOWN';

  const ingredients = Array.isArray(product.ingredients) && product.ingredients.length > 0
    ? product.ingredients
    : ['100% Pure Botanical Powder'];

  const verifiedBenefits = Array.isArray(product.benefits) && product.benefits.length > 0
    ? product.benefits
    : [];

  const weight = product.quantityOrWeight || '250g';
  const coverImage = (Array.isArray(product.images) && product.images[0]) || '/images/fallback.svg';
  const productId = product.id || '';

  // Find related product IDs within the same botanical or complementary scope
  const relatedProducts = allProducts.filter((p) => {
    if (p.id === productId || p.isActive === false) return false;
    const otherEntity = detectProductEntity(p);
    if (!otherEntity || !detectedEntity) return false;
    // Same entity or complementary hair/skin botanicals
    if (otherEntity.id === detectedEntity.id) return true;
    if (detectedEntity.primaryScope === 'HAIR' && otherEntity.primaryScope === 'HAIR') return true;
    if (detectedEntity.primaryScope === 'BODY_ART' && otherEntity.id === 'HENNA_MEHNDI') return true;
    if (detectedEntity.primaryScope === 'SKIN' && otherEntity.primaryScope === 'SKIN') return true;
    return false;
  }).slice(0, 4);

  const relatedProductIds = relatedProducts.map((p) => p.id);

  // Determine botanical specific content
  switch (entityId) {
    case 'HENNA_MEHNDI':
      return generateHennaMehndiGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'INDIGO':
      return generateIndigoGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'AMLA':
      return generateAmlaGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'HIBISCUS':
      return generateHibiscusGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'ROSE':
      return generateRoseGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'MORINGA':
      return generateMoringaGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'BEETROOT':
      return generateBeetrootGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    case 'REETHA':
    case 'SHIKAKAI':
    case 'NEEM':
    case 'BRAHMI':
    case 'BHRINGRAJ':
      return generateAyurvedicHairSkinGuide(product, detectedEntity!, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);

    default:
      return generateUnknownBotanicalGuide(product, name, rawSlug, ingredients, verifiedBenefits, weight, coverImage, productId, relatedProductIds);
  }
}

// ------------------------------------------------------------
// 1. HENNA / MEHNDI GUIDE GENERATOR
// ------------------------------------------------------------
function generateHennaMehndiGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const isBaq = name.toLowerCase().includes('baq') || name.toLowerCase().includes('body art');
  const isCone = name.toLowerCase().includes('cone');
  
  const title = isBaq
    ? `BAQ Henna Powder Guide: Mixing, Dye Release & Body Art Preparation`
    : isCone
    ? `Bridal Mehndi Cones Guide: Application, Stain Care & Longevity`
    : `Complete Guide to Sojat Henna / Mehndi Powder: Mixing, Uses & Care`;

  const slug = `${rawSlug}-guide`;
  const primaryKeyword = isBaq ? 'BAQ henna powder' : isCone ? 'bridal mehndi cones' : 'Sojat henna powder';
  
  const secondaryKeywords = [
    'natural mehndi powder',
    'Lawsonia inermis care',
    'henna cone preparation',
    'Sojat henna mixing',
    'dark mehndi stain tips',
    'triple sifted henna',
    'chemical free mehendi',
    'heena powder guide',
  ];

  const longTailKeywords = [
    'how to mix BAQ henna for dark stain',
    'sojat henna powder dye release time',
    'natural bridal mehndi cone paste recipe',
    'how long to keep henna on hair and hands',
    'difference between henna and mehendi powder',
  ];

  const shortIntro = isBaq
    ? `A comprehensive, step-by-step master guide on preparing and using pure Body Art Quality (BAQ) Lawsonia Inermis henna powder direct from Sojat, Rajasthan for rich, natural reddish-brown stains.`
    : isCone
    ? `Detailed guide on applying fresh, natural bridal mehndi cones, achieving dark oxidation tones, and post-application care for maximum stain longevity.`
    : `The definitive guide to authentic Sojat Henna (Mehndi) powder, covering botanical characteristics, batch mixing ratios, resting time, and application techniques.`;

  const overview = `Henna and Mehndi refer to the identical botanical entity, *Lawsonia Inermis*. Cultivated primarily in the arid, mineral-rich soils of Sojat (Pali District, Rajasthan), authentic henna leaves naturally produce lawsone pigment molecules that bond to keratin protein in hair and epidermal skin cells.`;

  const whatIsThis = `This product is 100% natural, unadulterated Lawsonia Inermis powder micro-pulverized and cloth-sifted in Sojat, Rajasthan. It contains zero synthetic dyes, PPD, metallic salts, or chemical preservatives.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    '100% pure Lawsonia Inermis harvested from Sojat, Rajasthan',
    'Ultra-fine micro-sifted texture ensuring clog-free mehndi cone flow',
    'Naturally cooling on the scalp and skin',
    'Safe, gentle botanical coloring for hair and intricate body art',
    'Zero chemical additives, artificial colors, or metallic salts',
  ];

  const whoShouldUse = `Henna artists, bridal cone makers, salon professionals, and individuals seeking pure, unadulterated herbal hair coloring or traditional body art.`;
  const whoShouldAvoid = `Individuals with known plant allergies to Lawsonia Inermis or G6PD deficiency. Always conduct a 24-hour patch test before full application.`;

  const quantityPreparation = isCone
    ? `Cones are ready to use. For mixing paste: Blend 100g sifted powder with warm water/lemon juice, add 30ml eucalyptus/tea tree essential oil, and let rest for 8–12 hours until dye release is visible.`
    : `Mix 100g henna powder with warm water (or mild black tea) until smooth paste consistency (like Greek yogurt). Cover with plastic wrap and rest at room temperature (25°C–30°C) for 8–12 hours for dye release.`;

  const howToUse = isCone
    ? `1. Wash and dry skin thoroughly (avoid oils or lotions).\n2. Snip the cone tip to desired thickness.\n3. Apply intricate designs.\n4. Allow paste to dry for 20–30 minutes, then apply lemon-sugar sealant.\n5. Keep on skin for 4–8 hours for deep stain.`
    : `1. Ensure hair or skin is clean and oil-free.\n2. Section hair evenly and apply thick paste from roots to tips using gloves.\n3. Cover with a shower cap to keep paste moist.\n4. Leave on for 2–4 hours (hair) or 4–8 hours (body art).\n5. Rinse thoroughly with plain water; avoid shampoo for 24–48 hours for oxidation.`;

  const storageInstructions = `Store in an airtight, moisture-proof container in a cool, dry place away from direct sunlight. Once mixed into paste, freeze excess paste for up to 3 months.`;
  const importantNotes = `Natural henna stains oxidize gradually from bright orange to deep mahogany/auburn brown over 24–48 hours. Never apply hot water (>60°C) as excessive heat degrades lawsone dye molecules.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Is there any difference between Henna and Mehndi?',
      answer: 'No. "Henna" (English/Arabic) and "Mehndi" (Hindi/Sanskrit) refer to the exact same botanical plant, Lawsonia Inermis. Musky Dose uses these terms interchangeably for the same pure Sojat harvest.',
    },
    {
      question: 'How long does natural henna dye release take?',
      answer: 'At normal room temperature (25°C to 30°C), natural Sojat henna releases its dye in approximately 8 to 12 hours. In cooler weather, it may take 14 to 18 hours.',
    },
    {
      question: 'Why is patch testing mandatory before use?',
      answer: 'Even 100% natural botanicals can cause sensitivity in rare individuals. A 24-hour patch test behind the ear or on the inner elbow ensures complete safety before full application.',
    },
    {
      question: 'Can this henna powder be used for both hair and body art cones?',
      answer: 'Yes. Our Body Art Quality (BAQ) henna is micro-sifted to 0.05mm, making it ideal for smooth cone flow without clogging, as well as conditioning hair packs.',
    },
  ];

  const content = `## Complete Guide to ${name}

### Overview & Botanical Origin
${overview}

### What Makes Sojat Henna Distinctive?
${whatIsThis}

### Key Verified Characteristics
${keyBenefits.map((b) => `- **${b}**`).join('\n')}

### Preparation & Mixing Proportions
${quantityPreparation}

### Application Instructions
${howToUse}

### Who It Is Suitable For
- **Recommended for:** ${whoShouldUse}
- **Precautionary Notes:** ${whoShouldAvoid}

### Storage & Freshness
${storageInstructions}

> [!NOTE]
> ${importantNotes}
`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Henna Application',
    readTime: '6 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 2. INDIGO GUIDE GENERATOR
// ------------------------------------------------------------
function generateIndigoGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Natural Indigo Powder Guide: 2-Step Henna-Indigo Process for Black & Brown Hair`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = 'natural indigo powder for hair';
  
  const secondaryKeywords = [
    'indigofera tinctoria hair dye',
    'two step henna indigo method',
    'organic indigo powder',
    'black hair without chemical dye',
    'sojat herbal hair care',
  ];

  const longTailKeywords = [
    'how to use indigo powder with henna for black hair',
    'indigo powder dye release time',
    'natural brown hair recipe henna and indigo',
    'why is my indigo hair color not sticking',
  ];

  const shortIntro = `Master the traditional 2-step botanical method using pure Indigofera Tinctoria powder with Henna to achieve natural rich brown to jet black hair color without chemical dyes or PPD.`;

  const overview = `*Indigofera Tinctoria* (True Indigo) is a leguminous botanical that produces indigotin dye molecules. Unlike synthetic black dyes that penetrate and damage hair cuticles, pure indigo works in synergy with henna to deposit natural pigments along the hair shaft.`;

  const whatIsThis = `100% pure, freshly harvested Indigo leaf powder with zero additives, peroxide, ammonia, or synthetic fillers.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    '100% pure Indigofera Tinctoria leaf powder',
    'Provides natural brown to jet black color when used with henna',
    'Strengthens hair strands and adds lustrous volume',
    'Completely free of PPD, ammonia, peroxide, and metallic salts',
  ];

  const whoShouldUse = `Individuals looking for a completely natural, chemical-free alternative to synthetic black hair dyes, especially for covering greys with the 2-step henna-indigo process.`;
  const whoShouldAvoid = `Indigo should never be applied alone directly on white/grey hair, as it will produce a greenish-blue hue. Always apply over henna-treated hair or in a henna-indigo blend. Patch test required.`;

  const quantityPreparation = `Mix 100g indigo powder with lukewarm water (40°C–50°C) and a pinch of salt to assist dye uptake. Indigo requires NO resting time—apply within 15–20 minutes of mixing, as indigotin dye oxidizes quickly.`;

  const howToUse = `**The 2-Step Process for Jet Black Hair:**\n1. **Step 1 (Henna):** Apply pure henna paste, leave for 2–3 hours, then rinse with water. Hair will be copper-red.\n2. **Step 2 (Indigo):** Immediately apply freshly mixed indigo paste. Leave for 1–2 hours.\n3. Rinse with plain water. Color deepens over 48 hours.`;

  const storageInstructions = `Indigo is light- and oxygen-sensitive. Store in a double-sealed, airtight pouch away from moisture and heat. Do not freeze mixed indigo paste.`;
  const importantNotes = `Do not shampoo for 48 hours after indigo application to allow the indigotin pigment to fully oxidize with atmospheric oxygen into rich black.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Can I apply Indigo powder directly on grey hair without Henna?',
      answer: 'No. Indigo on untreated white/grey hair results in a light greenish-blue tint. Henna acts as the red base primer that binds with indigo to produce deep brown and black tones.',
    },
    {
      question: 'How much time does Indigo take to release its dye?',
      answer: 'Unlike henna, indigo releases its dye almost immediately (within 10–15 minutes). It must be applied quickly before the pigment oxidizes in the mixing bowl.',
    },
    {
      question: 'How long does the 2-step color last?',
      answer: 'Natural henna-indigo coloring typically lasts 4 to 6 weeks depending on hair washing frequency and growth cycle.',
    },
  ];

  const content = `## Complete Guide to ${name}

### Understanding Botanical Indigo
${overview}

### The Science of 2-Step Natural Color
${whatIsThis}

### Key Verified Benefits
${keyBenefits.map((b) => `- **${b}**`).join('\n')}

### Preparation & Mixing
${quantityPreparation}

### Step-by-Step Application
${howToUse}

### Precautions & Suitability
- **Ideal for:** ${whoShouldUse}
- **Precaution:** ${whoShouldAvoid}

### Storage
${storageInstructions}

> [!IMPORTANT]
> ${importantNotes}
`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Hair Care',
    readTime: '5 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 3. AMLA GUIDE GENERATOR
// ------------------------------------------------------------
function generateAmlaGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Pure Amla Powder Guide: Traditional Hair Strengthening & Scalp Care`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = 'pure amla powder for hair';
  const secondaryKeywords = ['phyllanthus emblica powder', 'ayurvedic amla hair mask', 'natural vitamin c hair tonic', 'amla reetha shikakai pack'];
  const longTailKeywords = ['how to mix amla powder for hair conditioning', 'amla with henna for cooler brown tone'];

  const shortIntro = `A comprehensive guide to utilizing pure Indian Gooseberry (Phyllanthus Emblica) powder for nourishing scalp packs, hair conditioning, and toning henna mixes.`;
  const overview = `*Phyllanthus Emblica* (Amla) is revered in Ayurvedic tradition for its naturally occurring antioxidants, tannins, and vitamin C. When applied topically to the scalp and hair, it helps clarify sebum, condition hair shafts, and tone henna pastes.`;
  const whatIsThis = `100% stone-ground Indian Amla fruit pulp and pericarp dried hygienically without sulfur or bleaching agents.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Rich in natural botanical tannins and antioxidants',
    'Conditions hair cuticle for smooth texture and natural shine',
    'Tones down red/orange brassiness when mixed with henna',
    'Gently clarifies scalp buildup and excess oil',
  ];

  const whoShouldUse = `Anyone looking for botanical scalp nourishment, natural hair strengthening, or adjusting henna stain tones.`;
  const whoShouldAvoid = `Individuals with sensitive scalps or citrus/tannin sensitivities. Perform patch test.`;

  const quantityPreparation = `Mix 2–3 tablespoons of Amla powder with warm water, herbal tea, or yogurt to form a smooth mask. For henna toning, add 1 part Amla to 4 parts Henna.`;
  const howToUse = `Apply mask to damp hair and scalp, massage gently, leave for 30–45 minutes, then rinse with lukewarm water.`;
  const storageInstructions = `Keep in an airtight jar in a cool, dry place. Reseal tightly after each use.`;
  const importantNotes = `Amla is naturally acidic and may slightly tone down the fiery copper hues of henna into a deeper auburn.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Does Amla powder dye grey hair black on its own?',
      answer: 'No. Pure Amla contains tannins but is not a permanent black dye. It conditions hair and enhances darkness when combined with henna and indigo.',
    },
    {
      question: 'How often can I use an Amla hair mask?',
      answer: 'Using an Amla scalp mask once a week is ideal for healthy scalp maintenance and conditioning.',
    },
  ];

  const content = `## Guide to ${name}\n\n### Botanical Overview\n${overview}\n\n### Key Verified Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### Preparation\n${quantityPreparation}\n\n### How to Use\n${howToUse}\n\n### Storage\n${storageInstructions}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Hair Care',
    readTime: '4 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 4. HIBISCUS GUIDE GENERATOR
// ------------------------------------------------------------
function generateHibiscusGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Pure Hibiscus Flower Petal Powder Guide: Scalp Conditioning & Shine`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = 'pure hibiscus powder for hair';
  const secondaryKeywords = ['hibiscus rosa-sinensis petal powder', 'natural mucilage hair mask', 'gudhul powder benefits'];
  const longTailKeywords = ['how to make hibiscus hair mask at home', 'mixing hibiscus with henna for red shine'];

  const shortIntro = `Discover the botanical benefits of shade-dried *Hibiscus Rosa-Sinensis* petal powder for hydrating scalp packs, natural slip, and radiant hair gloss.`;
  const overview = `Hibiscus petals are naturally rich in botanical mucilage, amino acids, and flavonoids. When blended with water, the powder creates a soothing, slippery gel consistency that deeply conditions hair.`;
  const whatIsThis = `100% pure shade-dried red hibiscus petals finely milled into micro-powder without artificial colors or preservatives.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Natural botanical mucilage provides excellent comb-through slip',
    'Deeply conditions dry, brittle hair strands',
    'Adds rich luster and enhances burgundy tones in henna mixes',
    'Soothes dry, irritated scalps naturally',
  ];

  const whoShouldUse = `Those with dry, frizzy hair, dry scalps, or anyone wanting natural slip in herbal hair wash recipes.`;
  const whoShouldAvoid = `Individuals with known floral sensitivities. Standard 24h patch test recommended.`;
  const quantityPreparation = `Mix 2 tablespoons of hibiscus powder with warm water, aloe vera juice, or yogurt to form a creamy, viscous paste.`;
  const howToUse = `Apply from scalp to ends, leave on for 30 minutes under a shower cap, and rinse thoroughly with plain water.`;
  const storageInstructions = `Store in a cool, dark place in an airtight container to preserve petal freshness.`;
  const importantNotes = `Natural hibiscus produces a deep reddish-purple paste that does not permanently dye hair on its own but enhances red undertones.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Can Hibiscus powder be added to Henna paste?',
      answer: 'Yes! Adding 15–20% Hibiscus powder to henna paste enhances moisture, improves paste texture, and promotes rich reddish undertones.',
    },
  ];

  const content = `## Complete Guide to ${name}\n\n### Botanical Overview\n${overview}\n\n### Key Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### How to Use\n${howToUse}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Hair Care',
    readTime: '4 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 5. ROSE GUIDE GENERATOR
// ------------------------------------------------------------
function generateRoseGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const isWater = name.toLowerCase().includes('water') || name.toLowerCase().includes('mist') || name.toLowerCase().includes('jal');
  const title = isWater
    ? `Damask Rose Water Spray Guide: Pure Hydrosol Toning & Skin Refreshment`
    : `Pure Damask Rose Petal Powder Guide: Natural Face Masks & Glow`;

  const slug = `${rawSlug}-guide`;
  const primaryKeyword = isWater ? 'pure damask rose water' : 'rose petal powder for face';
  const secondaryKeywords = ['rosa damascena hydrosol', 'natural skin toner', 'sojat rose water', 'ayurvedic face mask'];
  const longTailKeywords = ['how to use pure rose water toner', 'rose petal powder and sandalwood face pack'];

  const shortIntro = isWater
    ? `A practical guide to incorporating 100% steam-distilled Damask Rose water into your daily skincare routine for balanced pH, hydration, and soothing relief.`
    : `Step-by-step instructions for crafting revitalizing herbal face masks and body polishes using stone-milled Rajasthan Damask Rose petals.`;

  const overview = `*Rosa Damascena* (Damask Rose) is celebrated for its delicate natural aromatic volatiles, mild astringency, and cooling properties that help soothe and tone all skin types.`;
  const whatIsThis = isWater
    ? `Steam-distilled pure rose hydrosol collected during traditional copper deg distillation without artificial perfumes or alcohol.`
    : `Finely milled, shade-dried Damask Rose flower petals with zero added fragrance or fillers.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Naturally balances skin pH and tightens pores gently',
    'Provides soothing hydration for sensitive, sun-exposed skin',
    '100% pure botanical with zero alcohol, artificial aroma, or parabens',
  ];

  const whoShouldUse = `Suitable for all skin types, including sensitive and dry skin, seeking natural hydration and tone.`;
  const whoShouldAvoid = `Individuals with known floral allergies. Patch test recommended.`;
  const quantityPreparation = isWater
    ? `Ready to use. Spritz directly onto cleansed skin morning and evening, or use to activate dry face packs.`
    : `Mix 1 tablespoon of rose petal powder with raw milk, yogurt, or rose water into a creamy paste.`;

  const howToUse = isWater
    ? `1. Cleanse face with mild water.\n2. Hold bottle 6 inches away and spritz 3–4 times.\n3. Gently pat into skin before applying moisturizer.`
    : `1. Apply paste evenly over face avoiding the eye area.\n2. Allow to rest for 10–15 minutes.\n3. Rinse with cool water and pat dry.`;

  const storageInstructions = `Store in a cool place away from direct heat and sunlight. Refrigeration provides an extra cooling sensation.`;
  const importantNotes = `Natural rose aroma is subtle and botanical, unlike synthetic perfumed rose products.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Is this Rose Water steam-distilled?',
      answer: 'Yes. Musky Dose Damask Rose Water is hydro-distilled to capture pure floral waters and essential oil micro-droplets without alcohol.',
    },
  ];

  const content = `## Guide to ${name}\n\n### Overview\n${overview}\n\n### Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### Instructions\n${howToUse}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Face Care',
    readTime: '3 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 6. MORINGA GUIDE GENERATOR
// ------------------------------------------------------------
function generateMoringaGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Pure Moringa Leaf Powder Guide: Nutritional & Topical Herbal Applications`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = 'pure moringa leaf powder';
  const secondaryKeywords = ['moringa oleifera powder', 'organic drumstick leaf powder', 'herbal moringa pack'];
  const longTailKeywords = ['how to use moringa powder for face pack', 'pure rajasthan moringa leaf powder'];

  const shortIntro = `A complete guide on utilizing shade-dried *Moringa Oleifera* leaf powder for clarifying botanical skincare packs and herbal wellness routines.`;
  const overview = `*Moringa Oleifera* is known as the "Miracle Tree" due to its rich concentration of chlorophyll, plant amino acids, and minerals.`;
  const whatIsThis = `100% pure shade-dried, unbleached Moringa leaf powder ground to a smooth fine grade.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Rich in natural chlorophyll and plant antioxidants',
    'Helps clarify skin impurities in DIY face packs',
    'Pure botanical leaf powder with zero fillers',
  ];

  const whoShouldUse = `Enthusiasts of herbal botanical care looking for natural clarifying and nourishing packs.`;
  const whoShouldAvoid = `Conduct standard patch test before topical facial application.`;
  const quantityPreparation = `Mix 1 tablespoon with honey, yogurt, or rose water to form a smooth paste.`;
  const howToUse = `Apply evenly to skin, leave for 10–15 minutes, then rinse gently with warm water.`;
  const storageInstructions = `Store in an airtight jar in a dark, cool cupboard to preserve natural green chlorophyll.`;
  const importantNotes = `Keep away from moisture to prevent clumping.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Is this Moringa powder suitable for external skincare?',
      answer: 'Yes, our finely milled moringa leaf powder makes an excellent clarifying face and scalp mask when combined with natural mixers.',
    },
  ];

  const content = `## Guide to ${name}\n\n### Botanical Overview\n${overview}\n\n### Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Herbal Products',
    readTime: '3 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 7. BEETROOT GUIDE GENERATOR
// ------------------------------------------------------------
function generateBeetrootGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Pure Beetroot Powder Guide: Natural Skin Glow, Lip Packs & Hair Tone`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = 'pure beetroot powder for skin';
  const secondaryKeywords = ['beta vulgaris root powder', 'natural pink lip pack', 'beetroot face mask recipe', 'henna beetroot hair tone'];
  const longTailKeywords = ['how to mix beetroot powder with henna', 'natural beetroot face pack for glowing skin'];

  const shortIntro = `Learn how to use 100% pure *Beta Vulgaris* (Beetroot) powder for natural radiant skincare face packs, gentle lip scrubs, and enhancing burgundy tones in henna hair pastes.`;
  const overview = `*Beta Vulgaris* (Beetroot) contains betalain pigments and natural minerals. In DIY herbal beauty, it is celebrated for lending a natural rosy tint and nourishing dull skin.`;
  const whatIsThis = `Dehydrated, fine-grade Rajasthan beetroot root powder free from added synthetic food coloring, sugar, or starch.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Natural botanical betalain pigments provide a gentle pink glow',
    'Revitalizes tired, dull skin when used in weekly face packs',
    'Enhances burgundy/red undertones when mixed with henna paste',
    '100% natural, zero synthetic dyes or preservatives',
  ];

  const whoShouldUse = `Those seeking natural, chemical-free face masks, DIY lip scrubs, or botanical hair tone enhancers.`;
  const whoShouldAvoid = `People with sensitive skin should always patch test first.`;
  const quantityPreparation = `Mix 1 tablespoon of beetroot powder with yogurt, honey, or rose water for face packs; add 2–3 tablespoons to warm henna paste for burgundy hair highlights.`;
  const howToUse = `Apply paste evenly to cleansed face, leave for 10–12 minutes, then wash gently with water. For lips, mix with coconut oil as a gentle scrub.`;
  const storageInstructions = `Beetroot powder is hygroscopic (absorbs moisture). Keep tightly sealed in a dry container.`;
  const importantNotes = `Natural betalain color washes off easily from skin and does not stain permanently like synthetic dyes.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: 'Will beetroot powder stain my face permanently?',
      answer: 'No. The natural vegetable pigments wash away easily with regular water, leaving skin fresh and softly glowing.',
    },
  ];

  const content = `## Guide to ${name}\n\n### Overview\n${overview}\n\n### Key Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### How to Use\n${howToUse}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Face Care',
    readTime: '3 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 8. AYURVEDIC HAIR/SKIN BOTANICALS (REETHA, SHIKAKAI, NEEM, BRAHMI, BHRINGRAJ)
// ------------------------------------------------------------
function generateAyurvedicHairSkinGuide(
  product: Partial<Product>,
  entity: SearchEntity,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const canonical = entity.canonicalName;
  const sciName = entity.scientificName;
  const title = `Guide to Pure ${canonical} Powder: Traditional ${entity.primaryScope === 'HAIR' ? 'Hair Care' : 'Herbal'} Uses & Benefits`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = `pure ${canonical.toLowerCase()} powder`;
  const secondaryKeywords = [`${sciName.toLowerCase()} powder`, `ayurvedic ${canonical.toLowerCase()} benefits`, `natural herbal ${canonical.toLowerCase()}`];
  const longTailKeywords = [`how to use ${canonical.toLowerCase()} powder`, `benefits of ${canonical.toLowerCase()} for hair`];

  const shortIntro = `A complete practical guide to using 100% pure *${sciName}* (${canonical}) powder for natural, traditional botanical care.`;
  const overview = `*${sciName}* (${canonical}) has been utilized across centuries in classical Ayurvedic wellness. Known for its gentle, plant-based cleansing and conditioning attributes, it provides a time-tested alternative to synthetic beauty chemicals.`;
  const whatIsThis = `100% pure, unadulterated ${canonical} powder sustainably sourced and micro-pulverized for smooth application.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    `100% pure ${sciName} with zero additives`,
    `Traditional Ayurvedic botanical care`,
    `Gentle, non-stripping natural properties`,
  ];

  const whoShouldUse = `Individuals seeking traditional herbal wellness and chemical-free personal care.`;
  const whoShouldAvoid = `Avoid contact with eyes. Perform a 24-hour patch test prior to first use.`;
  const quantityPreparation = `Mix 2–3 tablespoons with warm water into a smooth paste. Let rest for 15 minutes before applying.`;
  const howToUse = `Apply evenly to scalp, hair, or skin as needed, leave for 20–30 minutes, then rinse thoroughly with clean water.`;
  const storageInstructions = `Store in an airtight container in a cool, dry place away from moisture.`;
  const importantNotes = `Natural herbal powders can vary slightly in aroma and color depending on seasonal harvest.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: `How should I store ${canonical} powder?`,
      answer: `Keep the powder in a sealed airtight container in a dry environment away from moisture.`,
    },
  ];

  const content = `## Complete Guide to ${name}\n\n### Botanical Overview\n${overview}\n\n### Verified Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### How to Use\n${howToUse}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: entity.categorySlug === 'hair-care' ? 'Hair Care' : 'Herbal Products',
    readTime: '4 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: false,
    missingFields: [],
  };
}

// ------------------------------------------------------------
// 9. UNKNOWN BOTANICAL (SAFE CONSERVATIVE FALLBACK)
// ------------------------------------------------------------
function generateUnknownBotanicalGuide(
  product: Partial<Product>,
  name: string,
  rawSlug: string,
  ingredients: string[],
  benefits: string[],
  weight: string,
  coverImage: string,
  productId: string,
  relatedProductIds: string[]
): AutoGeneratedGuideDraft {
  const title = `Guide to ${name}: Overview, Uses & Storage`;
  const slug = `${rawSlug}-guide`;
  const primaryKeyword = name.toLowerCase();
  const secondaryKeywords = [name.toLowerCase(), 'natural botanical powder', 'herbal care'];
  const longTailKeywords = [`how to use ${name.toLowerCase()}`];

  const missingFields: string[] = [];
  if (!product.shortDescription && !product.fullDescription) missingFields.push('description');
  if (benefits.length === 0) missingFields.push('benefits');
  if (!product.ingredients || product.ingredients.length === 0) missingFields.push('ingredients');

  const shortIntro = product.shortDescription
    ? product.shortDescription
    : `A comprehensive overview and usage guide for ${name} from Musky Dose.`;

  const overview = product.fullDescription || `Natural botanical product carefully sourced and prepared by Musky Dose.`;
  const whatIsThis = `100% natural botanical product. Information based on verified manufacturer product details.`;

  const keyBenefits = benefits.length > 0 ? benefits : [
    'Pure natural botanical formulation',
    'Carefully processed for maximum freshness',
  ];

  const whoShouldUse = `Suitable for individuals looking for pure botanical ingredients.`;
  const whoShouldAvoid = `Individuals with known plant sensitivities. Perform a 24-hour patch test before full use.`;
  const quantityPreparation = product.usageInstructions || `Mix desired quantity with warm water or appropriate natural mixer until smooth.`;
  const howToUse = product.usageInstructions || `Apply evenly as directed, allow to rest for recommended duration, and rinse thoroughly.`;
  const storageInstructions = `Store in an airtight container in a cool, dry place away from direct sunlight.`;
  const importantNotes = `Always perform a patch test prior to first use. For external botanical use.`;

  const faqs: ProductGuideFAQ[] = [
    {
      question: `How do I store ${name}?`,
      answer: `Store in a tightly closed airtight container in a dry location away from moisture and direct heat.`,
    },
  ];

  const content = `## Guide to ${name}\n\n### Overview\n${overview}\n\n### Ingredients & Characteristics\n${whatIsThis}\n\n### Benefits\n${keyBenefits.map((b) => `- ${b}`).join('\n')}\n\n### How to Use\n${howToUse}\n`;

  return {
    title,
    slug,
    shortIntro,
    category: 'Herbal Products',
    readTime: '3 min read',
    overview,
    whatIsThis,
    keyBenefits,
    ingredients,
    whoShouldUse,
    whoShouldAvoid,
    howToUse,
    quantityPreparation,
    storageInstructions,
    importantNotes,
    content,
    faqs,
    seoTitle: `${title.slice(0, 50)} | Musky Dose`,
    seoDescription: shortIntro.slice(0, 155),
    seoKeywords: [primaryKeyword, ...secondaryKeywords].join(', '),
    primaryKeyword,
    secondaryKeywords,
    longTailKeywords,
    associatedProductId: productId,
    relatedProductIds,
    coverImage,
    needsReview: missingFields.length > 0,
    missingFields,
  };
}

