// ============================================================
// MUSKY DOSE — UNIVERSAL PRODUCT AUTO-FILL ENGINE
// Deterministic, Taxonomy-Aware, SEO-Optimized Product Derivation
// ============================================================

import { Product, Category, ProductGuide } from '@/lib/types';
import { BOTANICAL_SEARCH_ENTITIES, detectProductEntity, SearchEntity } from './entities';
import { deriveProductAutoSeo } from './product-keyword-engine';

export function sanitizeSlug(input: string): string {
  if (!input || typeof input !== 'string') return '';
  return input
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

export interface AutoGeneratedProductDraft {
  name: string;
  slug: string;
  categoryId: string;
  categoryName: string;
  productType: string;
  quantityOrWeight: string;
  shortDescription: string;
  fullDescription: string;
  overview: string;
  whatIsThis: string;
  ingredients: string[];
  benefits: string[];
  usageInstructions: string;
  storageInstructions: string;
  importantNotes: string;
  suitableFor: string;
  precautions: string;
  faqs: { question: string; answer: string }[];
  tags: string[];
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  primaryKeyword: string;
  secondaryKeywords: string[];
  longTailKeywords: string[];
  searchAliases: string[];
  entityId: string;
  scientificName: string;
  isWholesaleEligible: boolean;
  stockStatus: 'in_stock' | 'low_stock' | 'out_of_stock';
  robotsIndex: boolean;
  robotsFollow: boolean;
  relatedProductIds: string[];
  suggestedGuideSlug?: string;
  suggestedGuideTitle?: string;
  schemaType: string;
  checklist: {
    productData: 'READY' | 'NEEDS_REVIEW';
    seo: 'READY';
    search: 'READY';
    schema: 'READY';
    relatedContent: 'READY';
    guideLink: 'READY';
    sitemap: 'READY';
    price: 'READY' | 'NEEDS_INPUT';
    sku: 'READY' | 'NEEDS_INPUT';
    image: 'READY' | 'NEEDS_INPUT';
  };
  needsReview: boolean;
  missingFields: string[];
}

/**
 * Derives a complete product draft from a product name and category.
 */
export function deriveProductAutoFill(
  input: {
    productName: string;
    categoryId?: string;
    categoryName?: string;
    productType?: string;
    quantityOrWeight?: string;
    price?: number;
    compareAtPrice?: number;
    sku?: string;
    images?: string[];
  },
  categories: Category[] = [],
  allProducts: Product[] = [],
  allGuides: ProductGuide[] = []
): AutoGeneratedProductDraft {
  const name = input.productName.trim();
  const rawSlug = sanitizeSlug(name);
  const detectedEntity = detectProductEntity({ name, slug: rawSlug });
  const entityId = detectedEntity?.id || 'UNKNOWN';

  // Match category
  let categoryId = input.categoryId || '';
  let categoryName = input.categoryName || '';

  if (!categoryId && categories.length > 0) {
    if (detectedEntity) {
      const match = categories.find((c) =>
        c.slug === detectedEntity.categorySlug ||
        c.name.toLowerCase().includes(detectedEntity.canonicalName.toLowerCase()) ||
        (detectedEntity.primaryScope === 'HAIR' && c.name.toLowerCase().includes('hair')) ||
        (detectedEntity.primaryScope === 'SKIN' && (c.name.toLowerCase().includes('face') || c.name.toLowerCase().includes('skin'))) ||
        (detectedEntity.id === 'HENNA_MEHNDI' && c.name.toLowerCase().includes('henna'))
      );
      if (match) {
        categoryId = match.id;
        categoryName = match.name;
      }
    }
    if (!categoryId) {
      categoryId = categories[0].id;
      categoryName = categories[0].name;
    }
  }

  // Determine botanical content based on entity
  const botanicalData = getBotanicalProductContent(name, detectedEntity);

  const productType = input.productType || botanicalData.productType;
  const quantityOrWeight = input.quantityOrWeight || botanicalData.defaultWeight;

  // Build Auto-SEO
  const seoData = deriveProductAutoSeo({
    name,
    slug: rawSlug,
    categoryName,
    shortDescription: botanicalData.shortDescription,
    ingredients: botanicalData.ingredients,
    benefits: botanicalData.benefits,
    price: input.price || 199,
  });

  // Find related products
  const relatedProducts = allProducts
    .filter((p) => {
      if (p.slug === rawSlug || p.isActive === false) return false;
      const otherEntity = detectProductEntity(p);
      if (!otherEntity || !detectedEntity) return false;
      if (otherEntity.id === detectedEntity.id) return true;
      if (detectedEntity.primaryScope === 'HAIR' && otherEntity.primaryScope === 'HAIR') return true;
      if (detectedEntity.primaryScope === 'BODY_ART' && otherEntity.id === 'HENNA_MEHNDI') return true;
      if (detectedEntity.primaryScope === 'SKIN' && otherEntity.primaryScope === 'SKIN') return true;
      return false;
    })
    .slice(0, 4);

  const relatedProductIds = relatedProducts.map((p) => p.id);

  // Match existing guide
  const matchingGuide = allGuides.find((g) =>
    g.slug.includes(rawSlug) ||
    (detectedEntity && g.title.toLowerCase().includes(detectedEntity.canonicalName.toLowerCase())) ||
    (detectedEntity?.id === 'HENNA_MEHNDI' && (g.title.toLowerCase().includes('henna') || g.title.toLowerCase().includes('mehndi')))
  );

  // Missing fields & Checklist evaluation
  const missingFields: string[] = [];
  if (!input.price || input.price <= 0) missingFields.push('price');
  if (!input.sku || input.sku === 'MD-888') missingFields.push('sku');
  if (!input.images || input.images.length === 0 || input.images[0].includes('fallback')) missingFields.push('image');
  if (botanicalData.needsReview) missingFields.push('botanical_review');

  const fullDescription = `${botanicalData.overview}\n\n${botanicalData.whatIsThis}`;

  const draft: AutoGeneratedProductDraft = {
    name,
    slug: rawSlug,
    categoryId,
    categoryName,
    productType,
    quantityOrWeight,
    shortDescription: botanicalData.shortDescription,
    fullDescription,
    overview: botanicalData.overview,
    whatIsThis: botanicalData.whatIsThis,
    ingredients: botanicalData.ingredients,
    benefits: botanicalData.benefits,
    usageInstructions: botanicalData.usageInstructions,
    storageInstructions: botanicalData.storageInstructions,
    importantNotes: botanicalData.importantNotes,
    suitableFor: botanicalData.suitableFor,
    precautions: botanicalData.precautions,
    faqs: botanicalData.faqs,
    tags: [detectedEntity?.canonicalName || 'Botanical', categoryName, 'Natural Herbal', 'Sojat Rajasthan'].filter(Boolean),
    seoTitle: seoData.seoTitle,
    seoDescription: seoData.metaDescription,
    seoKeywords: [seoData.primaryKeyword, ...seoData.secondaryKeywords],
    primaryKeyword: seoData.primaryKeyword,
    secondaryKeywords: seoData.secondaryKeywords,
    longTailKeywords: seoData.longTailKeywords,
    searchAliases: detectedEntity?.aliases || [name.toLowerCase()],
    entityId,
    scientificName: detectedEntity?.scientificName || '',
    isWholesaleEligible: true,
    stockStatus: 'in_stock',
    robotsIndex: true,
    robotsFollow: true,
    relatedProductIds,
    suggestedGuideSlug: matchingGuide?.slug || `${rawSlug}-guide`,
    suggestedGuideTitle: matchingGuide?.title || `Complete Guide to ${name}`,
    schemaType: 'Product',
    checklist: {
      productData: botanicalData.needsReview ? 'NEEDS_REVIEW' : 'READY',
      seo: 'READY',
      search: 'READY',
      schema: 'READY',
      relatedContent: 'READY',
      guideLink: 'READY',
      sitemap: 'READY',
      price: input.price && input.price > 0 ? 'READY' : 'NEEDS_INPUT',
      sku: input.sku && input.sku !== 'MD-888' ? 'READY' : 'NEEDS_INPUT',
      image: input.images && input.images.length > 0 && !input.images[0].includes('fallback') ? 'READY' : 'NEEDS_INPUT',
    },
    needsReview: botanicalData.needsReview || missingFields.length > 0,
    missingFields,
  };

  return draft;
}

// ------------------------------------------------------------
// BOTANICAL CONTENT SPECIFICATIONS
// ------------------------------------------------------------
function getBotanicalProductContent(name: string, entity: SearchEntity | null) {
  const lower = name.toLowerCase();

  // 1. HENNA / MEHNDI
  if (entity?.id === 'HENNA_MEHNDI' || lower.includes('henna') || lower.includes('mehendi') || lower.includes('mehndi')) {
    const isCone = lower.includes('cone');
    const isBaq = lower.includes('baq') || lower.includes('body art');

    if (isCone) {
      return {
        productType: 'FINISHED',
        defaultWeight: 'Pack of 12 Cones',
        shortDescription: `Fresh, ready-to-use bridal mehndi cones prepared with 100% pure Sojat henna and essential oils for rich, natural reddish-brown stains.`,
        overview: `Crafted in Sojat, Rajasthan, Musky Dose Bridal Mehndi Cones are prepared with micro-sifted natural Lawsonia Inermis paste, filtered water, and botanical essential oils. Features a smooth fine-tip pin nozzle for intricate bridal line work without clogging.`,
        whatIsThis: `Ready-to-use bridal mehndi cones filled with freshly mixed Sojat henna paste. 100% natural formula free from toxic chemical dyes or synthetic stain accelerators.`,
        ingredients: [
          '100% Pure Sojat Henna Powder (Lawsonia Inermis)',
          'Eucalyptus Essential Oil',
          'Clove Bud Essential Oil',
          'Lemon Juice & Natural Cane Sugar',
          'Purified Water',
        ],
        benefits: [
          'Micro-filtered smooth paste ensuring effortless, clog-free cone flow',
          'Rich natural oxidation developing into deep mahogany-brown stains',
          'Zero synthetic chemical dyes, PPD, or kerosene additives',
          'Fine precision tip designed for intricate bridal and festive body art',
        ],
        usageInstructions: `1. Wash and dry skin thoroughly before application.\n2. Snip the cone pin-tip to desired line thickness.\n3. Apply intricate patterns on palms, arms, or feet.\n4. Allow paste to dry for 30 minutes, then apply lemon-sugar sealant.\n5. Keep on skin for 4 to 8 hours. Scrape off gently without water for 24 hours to allow stain oxidation.`,
        storageInstructions: `Store in a cool place away from direct heat. For extended shelf life, freeze sealed cones for up to 3 months.`,
        importantNotes: `Natural henna stains oxidize gradually from orange to deep reddish-brown over 24 to 48 hours. Always conduct a 24-hour patch test before full use.`,
        suitableFor: `Bridal artists, mehndi professionals, and festive body art enthusiasts.`,
        precautions: `Individuals with known sensitivities to Lawsonia Inermis or essential oils should patch test first.`,
        faqs: [
          {
            question: 'How long does the bridal mehndi stain last?',
            answer: 'With proper aftercare and avoiding water for the first 24 hours, natural henna stains typically last 1 to 2 weeks depending on skin exfoliation.',
          },
          {
            question: 'Are there any chemical colorants added to these cones?',
            answer: 'No. Musky Dose cones are formulated strictly with pure Sojat henna powder and botanical essential oils, with zero PPD or synthetic dyes.',
          },
        ],
        needsReview: false,
      };
    }

    return {
      productType: isBaq ? 'BAQ_POWDER' : 'POWDER',
      defaultWeight: '250g Pack',
      shortDescription: `100% pure, cloth-sifted Lawsonia Inermis henna powder from Sojat, Rajasthan for smooth body art cones and natural hair conditioning.`,
      overview: `Sourced directly from the arid, mineral-rich fields of Sojat (Pali District, Rajasthan), Musky Dose Henna Powder is cloth-sifted to an ultra-fine grade. It provides rich natural reddish-brown coloring for hair care and body art without chemical additives.`,
      whatIsThis: `100% pure, unadulterated Lawsonia Inermis leaf powder pulverized and triple-cloth-sifted in Sojat, Rajasthan. Zero synthetic dyes, PPD, metallic salts, or preservatives.`,
      ingredients: ['100% Pure Natural Lawsonia Inermis (Sojat Henna) Leaf Powder'],
      benefits: [
        '100% authentic Sojat, Rajasthan harvest',
        'Ultra-fine cloth-sifted texture ensuring smooth, clog-free paste mixing',
        'Traditional cooling sensation on the scalp and skin',
        'Natural plant coloring for hair care and traditional body art',
        'Zero chemical dyes, metallic salts, ammonia, or PPD',
      ],
      usageInstructions: `In a non-metallic bowl, mix henna powder with lukewarm water (or mild black tea) into a smooth, yogurt-like consistency. Cover and rest at room temperature (25°C–30°C) for 8–12 hours for natural dye release. Apply section by section on clean hair or fill into cones for body art. Rinse thoroughly with plain water.`,
      storageInstructions: `Store in an airtight, moisture-proof container in a cool, dry place away from direct sunlight. Once mixed, excess paste may be frozen for up to 3 months.`,
      importantNotes: `Avoid boiling water (>60°C) when mixing to preserve natural botanical quality. Natural stains oxidize gradually over 24–48 hours.`,
      suitableFor: `Henna artists, cone makers, salon professionals, and individuals seeking pure herbal hair care.`,
      precautions: `Conduct a standard 24-hour patch test prior to full application.`,
      faqs: [
        {
          question: 'What is the difference between Henna and Mehndi?',
          answer: 'Henna and Mehndi refer to the exact same botanical plant, Lawsonia Inermis. Musky Dose uses these terms interchangeably for the same pure Sojat harvest.',
        },
        {
          question: 'How long does natural henna dye release take?',
          answer: 'At room temperature (25°C to 30°C), natural Sojat henna releases its dye in 8 to 12 hours.',
        },
      ],
      needsReview: false,
    };
  }

  // 2. INDIGO
  if (entity?.id === 'INDIGO' || lower.includes('indigo')) {
    return {
      productType: 'POWDER',
      defaultWeight: '200g Pack',
      shortDescription: `100% pure Indigofera Tinctoria leaf powder for natural brown to black hair tones when used in combination with henna.`,
      overview: `Musky Dose Natural Indigo Powder is made from freshly harvested and shade-dried *Indigofera Tinctoria* leaves. When applied in the traditional 2-step method over henna-treated hair, it delivers deep brown to rich black shades without chemical dyes.`,
      whatIsThis: `100% pure, unadulterated Indigo leaf powder with zero additives, peroxide, ammonia, or synthetic fillers.`,
      ingredients: ['100% Pure Natural Indigofera Tinctoria Leaf Powder'],
      benefits: [
        '100% pure Indigofera Tinctoria leaf powder',
        'Provides natural brown to black tones when used in combination with henna',
        'Coats the hair cuticle for a smoother feel and natural look',
        'Completely free of PPD, ammonia, peroxide, and metallic salts',
      ],
      usageInstructions: `Mix indigo powder with lukewarm water (40°C–50°C) into a smooth paste. Apply within 15–20 minutes of mixing onto freshly henna-treated damp hair. Leave on for 1 to 2 hours, then rinse thoroughly with plain water. Avoid shampoo for 24–48 hours to allow color oxidation.`,
      storageInstructions: `Indigo is light- and oxygen-sensitive. Store in a double-sealed, airtight pouch away from moisture and direct light.`,
      importantNotes: `Indigo should not be applied alone on white or grey hair without a henna base, as it produces a greenish-blue tint. Always patch test.`,
      suitableFor: `Individuals seeking a natural plant-based alternative to synthetic hair dyes, particularly for grey coverage in the 2-step henna-and-indigo routine.`,
      precautions: `Do not use alone on grey/white hair without henna. Perform a 24-hour patch test.`,
      faqs: [
        {
          question: 'Can I apply Indigo directly on grey hair without Henna?',
          answer: 'Indigo applied alone on white or grey hair produces a greenish-blue hue. Henna serves as the warm red base that combines with indigo to produce natural brown and black tones.',
        },
        {
          question: 'How quickly should Indigo be applied after mixing?',
          answer: 'Indigo should be applied within 15 to 20 minutes of mixing with water, before the mixture oxidizes in the bowl.',
        },
      ],
      needsReview: false,
    };
  }

  // 3. AMLA
  if (entity?.id === 'AMLA' || lower.includes('amla') || lower.includes('gooseberry')) {
    return {
      productType: 'POWDER',
      defaultWeight: '200g Pack',
      shortDescription: `Pure stone-ground Indian Gooseberry (Phyllanthus Emblica) powder for nourishing herbal scalp packs and conditioning.`,
      overview: `Musky Dose Pure Amla Powder is stone-ground from shade-dried Indian Gooseberries (*Phyllanthus Emblica*). Traditionally used in Ayurvedic hair masks, it helps condition hair cuticles and can be added to henna to tone down bright orange tones into deeper auburn shades.`,
      whatIsThis: `100% stone-ground Indian Amla fruit pulp and pericarp dried hygienically without sulfur, additives, or chemical preservatives.`,
      ingredients: ['100% Pure Phyllanthus Emblica (Amla) Fruit Powder'],
      benefits: [
        'Pure Phyllanthus Emblica fruit powder',
        'Conditions hair strands for a manageable feel and natural look',
        'Can be mixed with henna paste to achieve deeper, cooler tones',
        'Traditional botanical scalp pack ingredient',
      ],
      usageInstructions: `Mix 2–3 tablespoons of Amla powder with warm water, herbal tea, or yogurt into a smooth paste. Apply to damp hair and scalp, leave for 30–45 minutes, then rinse thoroughly with plain lukewarm water. For henna toning, add 1 part Amla to 4 parts Henna.`,
      storageInstructions: `Keep in an airtight jar in a cool, dry place. Reseal tightly after each use.`,
      importantNotes: `Amla is naturally acidic and may slightly mute bright orange tones in henna towards deeper brown.`,
      suitableFor: `Individuals seeking herbal scalp packs, traditional hair conditioning, or adjusting henna paste tones.`,
      precautions: `Conduct a standard 24-hour patch test before full use.`,
      faqs: [
        {
          question: 'Does Amla powder dye grey hair black on its own?',
          answer: 'No. Pure Amla is a conditioning botanical and not a black hair dye. It can be mixed with henna and indigo to adjust color tones.',
        },
      ],
      needsReview: false,
    };
  }

  // 4. HIBISCUS
  if (entity?.id === 'HIBISCUS' || lower.includes('hibiscus') || lower.includes('gudhul')) {
    return {
      productType: 'POWDER',
      defaultWeight: '150g Pack',
      shortDescription: `100% pure shade-dried Hibiscus flower petal powder for hydrating scalp packs, natural slip, and hair gloss.`,
      overview: `Musky Dose Pure Hibiscus Powder is prepared from hand-picked, shade-dried *Hibiscus Rosa-Sinensis* flower petals. Naturally rich in plant mucilage, it creates a smooth conditioning paste that provides comb-through slip and enhances shine in herbal hair packs.`,
      whatIsThis: `100% pure shade-dried red hibiscus petals finely milled into a smooth botanical powder without artificial colors or preservatives.`,
      ingredients: ['100% Pure Hibiscus Rosa-Sinensis Flower Petal Powder'],
      benefits: [
        'Natural plant mucilage provides smooth comb-through slip',
        'Conditions hair strands for a soft and manageable feel',
        'Enhances reddish-burgundy undertones when mixed with henna paste',
        'Pure dried flower petal powder with zero chemical fillers',
      ],
      usageInstructions: `Mix 2 tablespoons of hibiscus powder with warm water, aloe vera gel, or yogurt into a creamy paste. Apply from scalp to hair ends, leave on for 20–30 minutes under a shower cap, and rinse thoroughly with plain water.`,
      storageInstructions: `Store in a cool, dry place in an airtight container away from direct sunlight.`,
      importantNotes: `Natural hibiscus creates a deep reddish-purple paste that does not permanently dye hair on its own, but complements warm tones in henna.`,
      suitableFor: `Individuals seeking natural botanical conditioning or wanting to mix hibiscus into henna hair packs.`,
      precautions: `Conduct a standard 24h patch test before use.`,
      faqs: [
        {
          question: 'Can Hibiscus powder be added to Henna paste?',
          answer: 'Yes. Adding 15% to 20% Hibiscus powder to a henna paste mix adds moisture and complements warm reddish undertones.',
        },
      ],
      needsReview: false,
    };
  }

  // 5. ROSE
  if (entity?.id === 'ROSE' || lower.includes('rose') || lower.includes('gulab')) {
    const isWater = lower.includes('water') || lower.includes('mist') || lower.includes('jal');
    if (isWater) {
      return {
        productType: 'FINISHED',
        defaultWeight: '100ml Bottle',
        shortDescription: `100% steam-distilled pure Damask Rose water spray for daily facial hydration, soothing toner, and skin mist.`,
        overview: `Hydro-distilled in traditional copper stills from fresh Rajasthan Damask Rose (*Rosa Damascena*) petals, this pure floral hydrosol delivers gentle facial hydration and a soothing botanical aroma without alcohol or synthetic perfumes.`,
        whatIsThis: `Steam-distilled pure rose hydrosol collected during traditional distillation without added synthetic perfumes, alcohol, or parabens.`,
        ingredients: ['100% Pure Steam-Distilled Rosa Damascena (Damask Rose) Hydrosol'],
        benefits: [
          'Provides soothing hydration and a refreshed feeling on the skin',
          'Gentle botanical facial toner suitable for daily use',
          '100% pure botanical with zero alcohol, artificial aroma, or parabens',
        ],
        usageInstructions: `Hold the bottle 6 inches from cleansed face and spritz 3–4 times. Gently pat into skin before applying moisturizer or facial oil. Can also be used to activate dry botanical face packs.`,
        storageInstructions: `Store in a cool place away from direct heat and sunlight.`,
        importantNotes: `Natural rose aroma is subtle and botanical, unlike synthetic perfumed products.`,
        suitableFor: `Individuals seeking natural, alcohol-free facial hydration or botanical mixers for dry face packs.`,
        precautions: `Conduct a patch test before first use.`,
        faqs: [
          {
            question: 'Is this Rose Water steam-distilled?',
            answer: 'Yes. Musky Dose Damask Rose Water is hydro-distilled to capture pure floral waters without added alcohol or synthetic perfumes.',
          },
        ],
        needsReview: false,
      };
    }

    return {
      productType: 'POWDER',
      defaultWeight: '100g Pack',
      shortDescription: `Pure shade-dried Damask Rose petal powder for revitalizing DIY face packs and gentle herbal skincare.`,
      overview: `Prepared from shade-dried *Rosa Damascena* petals, Musky Dose Rose Petal Powder is stone-milled into an ultra-fine powder. Ideal for DIY face packs with raw milk, yogurt, or rose water.`,
      whatIsThis: `Finely milled, shade-dried Damask Rose flower petals with zero added fragrance, colorants, or fillers.`,
      ingredients: ['100% Pure Rosa Damascena (Damask Rose) Petal Powder'],
      benefits: [
        'Pure dried flower petal powder with zero artificial aroma or fillers',
        'Provides a soothing, refreshed feel in DIY facial packs',
        'Gentle botanical ingredient suitable for herbal skincare',
      ],
      usageInstructions: `Mix 1 tablespoon of rose petal powder with raw milk, yogurt, or rose water into a creamy paste. Apply evenly over face avoiding the eye area. Rest for 10–15 minutes, then rinse with cool water.`,
      storageInstructions: `Store in an airtight container in a cool, dry place.`,
      importantNotes: `For external cosmetic use only.`,
      suitableFor: `Individuals looking for pure botanical ingredients for DIY face masks.`,
      precautions: `Conduct a 24-hour patch test before full use.`,
      faqs: [
        {
          question: 'Can Rose Petal Powder be mixed with Multani Mitti or Sandalwood?',
          answer: 'Yes. Rose petal powder mixes smoothly with clays and botanical powders to create gentle facial masks.',
        },
      ],
      needsReview: false,
    };
  }

  // 6. MORINGA
  if (entity?.id === 'MORINGA' || lower.includes('moringa')) {
    return {
      productType: 'POWDER',
      defaultWeight: '150g Pack',
      shortDescription: `Pure Rajasthan Moringa leaf powder for clarifying botanical skincare packs and herbal wellness routines.`,
      overview: `Musky Dose Pure Moringa Powder is shade-dried and micro-milled from fresh *Moringa Oleifera* leaves. Traditionally used for herbal packs and clarifying masks.`,
      whatIsThis: `100% pure shade-dried, unbleached Moringa leaf powder ground to a smooth fine grade.`,
      ingredients: ['100% Pure Moringa Oleifera Leaf Powder'],
      benefits: [
        'Pure Moringa Oleifera leaf powder',
        'Useful as a clarifying botanical ingredient in DIY face packs',
        'Pure leaf powder with zero additives or preservatives',
      ],
      usageInstructions: `Mix 1 tablespoon with honey, yogurt, or rose water to form a smooth paste. Apply evenly to skin, leave for 10–15 minutes, then rinse gently with warm water.`,
      storageInstructions: `Store in an airtight jar in a dark, cool place.`,
      importantNotes: `Keep away from moisture to prevent clumping.`,
      suitableFor: `Enthusiasts of herbal botanical care looking for natural clarifying and nourishing packs.`,
      precautions: `Conduct standard patch test before topical facial application.`,
      faqs: [
        {
          question: 'Is this Moringa powder suitable for external skincare?',
          answer: 'Yes, our finely milled moringa leaf powder makes an excellent clarifying face and scalp mask when combined with natural mixers.',
        },
      ],
      needsReview: false,
    };
  }

  // 7. BEETROOT
  if (entity?.id === 'BEETROOT' || lower.includes('beetroot')) {
    return {
      productType: 'POWDER',
      defaultWeight: '100g Pack',
      shortDescription: `Pure dehydrated Beetroot powder for natural face masks, gentle lip packs, and enhancing burgundy tones in henna mixes.`,
      overview: `Musky Dose Pure Beetroot Powder is ground from dehydrated *Beta Vulgaris* roots. Its natural vegetable pigments make it a versatile botanical for glowing face packs, lip scrubs, and toning henna hair pastes.`,
      whatIsThis: `Dehydrated, fine-grade Rajasthan beetroot root powder free from added synthetic food coloring, sugar, or starch.`,
      ingredients: ['100% Pure Beta Vulgaris (Beetroot) Root Powder'],
      benefits: [
        'Natural botanical vegetable pigments provide a gentle rosy glow',
        'Revitalizes dull-looking skin when used in weekly face packs',
        'Enhances burgundy/red undertones when mixed with henna paste',
        '100% natural, zero synthetic dyes or preservatives',
      ],
      usageInstructions: `Mix 1 tablespoon of beetroot powder with yogurt, honey, or rose water for face packs; add 2–3 tablespoons to warm henna paste for burgundy hair highlights. Leave for 10–15 minutes, then wash gently.`,
      storageInstructions: `Beetroot powder absorbs moisture easily. Keep tightly sealed in a dry container.`,
      importantNotes: `Natural betalain color washes off easily from skin and does not stain permanently.`,
      suitableFor: `Those seeking natural face masks, DIY lip scrubs, or botanical hair tone enhancers.`,
      precautions: `Conduct a patch test before first use.`,
      faqs: [
        {
          question: 'Will beetroot powder stain my face permanently?',
          answer: 'No. The natural vegetable pigments wash away easily with regular water, leaving skin fresh and softly glowing.',
        },
      ],
      needsReview: false,
    };
  }

  // 8. AYURVEDIC SINGLE HERBS (REETHA, SHIKAKAI, NEEM, BRAHMI, BHRINGRAJ)
  if (entity && ['REETHA', 'SHIKAKAI', 'NEEM', 'BRAHMI', 'BHRINGRAJ'].includes(entity.id)) {
    const canonical = entity.canonicalName;
    const sciName = entity.scientificName;
    return {
      productType: 'POWDER',
      defaultWeight: '200g Pack',
      shortDescription: `100% pure ${canonical} (${sciName}) powder for traditional Ayurvedic ${entity.primaryScope === 'HAIR' ? 'hair care' : 'herbal'} routines.`,
      overview: `Sourced from authentic botanical harvests, Musky Dose Pure ${canonical} Powder is micro-pulverized for easy paste mixing and traditional Ayurvedic applications.`,
      whatIsThis: `100% pure, unadulterated ${canonical} powder sustainably sourced and micro-pulverized for smooth application.`,
      ingredients: [`100% Pure ${sciName} (${canonical}) Powder`],
      benefits: [
        `100% pure ${sciName} with zero additives`,
        `Traditional Ayurvedic botanical care`,
        `Gentle, non-stripping natural properties`,
      ],
      usageInstructions: `Mix 2–3 tablespoons with warm water into a smooth paste. Let rest for 15 minutes before applying to scalp, hair, or skin. Leave for 20–30 minutes, then rinse thoroughly with clean water.`,
      storageInstructions: `Store in an airtight container in a cool, dry place away from moisture.`,
      importantNotes: `Natural herbal powders can vary slightly in aroma and color depending on seasonal harvest.`,
      suitableFor: `Individuals seeking traditional herbal wellness and chemical-free personal care.`,
      precautions: `Avoid contact with eyes. Perform a 24-hour patch test prior to first use.`,
      faqs: [
        {
          question: `How should I store ${canonical} powder?`,
          answer: `Keep the powder in a sealed airtight container in a dry environment away from moisture.`,
        },
      ],
      needsReview: false,
    };
  }

  // 9. UNKNOWN / CUSTOM BOTANICAL (SAFE CONSERVATIVE FALLBACK)
  return {
    productType: 'POWDER',
    defaultWeight: '200g Pack',
    shortDescription: `Natural botanical product carefully prepared and packaged by Musky Dose.`,
    overview: `Musky Dose botanical product prepared using traditional quality methods. Free from harmful additives.`,
    whatIsThis: `100% natural botanical product. Information based on verified manufacturer product details.`,
    ingredients: ['100% Pure Natural Botanical Ingredient'],
    benefits: [
      'Pure natural botanical formulation',
      'Carefully processed for freshness',
    ],
    usageInstructions: `Mix desired quantity with warm water or appropriate natural mixer until smooth. Apply evenly, allow to rest, and rinse thoroughly.`,
    storageInstructions: `Store in an airtight container in a cool, dry place away from direct sunlight.`,
    importantNotes: `Always perform a patch test prior to first use. For external botanical use.`,
    suitableFor: `Individuals looking for pure botanical ingredients.`,
    precautions: `Conduct a 24-hour patch test before full use.`,
    faqs: [
      {
        question: `How do I store this botanical product?`,
        answer: `Store in a tightly closed airtight container in a dry location away from moisture.`,
      },
    ],
    needsReview: true,
  };
}

