/**
 * ============================================================================
 * MUSKY DOSE — AI & AUTOMATION GOVERNANCE ENGINE (V1.0)
 *
 * CORE CONTRACT:
 * 1. AI suggests. Governance decides. Admin confirms.
 * 2. AI output is never silently authoritative.
 * 3. All suggestions must carry provenance, confidence score, and NEEDS_REVIEW status.
 * 4. Claims must be backed by verified botanical attributes.
 * ============================================================================
 */

import { AiSuggestionEnvelope, UniversalEntityType, GovernanceValidationResult } from './types';
import { UniversalGovernanceCore } from './core';

export class AiGovernance {
  /**
   * Wraps an AI-generated suggestion in a standardized governance envelope.
   */
  public static createSuggestion<T>(
    payload: T,
    source: 'AI_AUTOFILL' | 'AI_GROWTH' | 'HEURISTIC_PARSER',
    confidenceScore: number,
    auditTrail: string[] = []
  ): AiSuggestionEnvelope<T> {
    const boundedConfidence = Math.max(0, Math.min(1, confidenceScore));

    return {
      source,
      confidenceScore: boundedConfidence,
      generatedAt: new Date().toISOString(),
      suggestedState: 'NEEDS_REVIEW',
      payload,
      auditTrail: [
        ...auditTrail,
        `Generated by ${source} at ${new Date().toISOString()} (Confidence: ${(boundedConfidence * 100).toFixed(1)}%)`,
      ],
    };
  }

  /**
   * Validates an AI suggestion against the registered entity governance rules.
   * If validation fails, the suggestion is rejected before reaching the admin.
   */
  public static validateSuggestion<T>(
    entityType: UniversalEntityType,
    envelope: AiSuggestionEnvelope<T>
  ): GovernanceValidationResult {
    if (envelope.confidenceScore < 0.3) {
      return {
        isValid: false,
        errors: [`AI suggestion rejected: Confidence score (${envelope.confidenceScore}) below minimum threshold (0.3).`],
        warnings: [],
      };
    }

    return UniversalGovernanceCore.validateEntity(entityType, envelope.payload, false);
  }

  /**
   * Prepares an approved AI suggestion for persistence into authoritative storage.
   * Elevates status from NEEDS_REVIEW to MANUAL or AUTO upon admin confirmation.
   */
  public static promoteApprovedSuggestion<T extends Record<string, any>>(
    envelope: AiSuggestionEnvelope<T>,
    approvedByUserId: string
  ): T {
    return {
      ...envelope.payload,
      state: 'MANUAL',
      approvedBy: approvedByUserId,
      approvedAt: new Date().toISOString(),
    };
  }
}
