import { CmsTextConfig, SiteSettings } from './types';

export const DEFAULT_CMS_TEXT: Required<CmsTextConfig> = {
  // Navigation & Search
  navSearchPlaceholder: 'Search natural henna, hair care...',
  navWhatsappCtaText: 'Order on WhatsApp',
  navCartButtonText: 'Cart',
  navWishlistText: 'Wishlist',
  navCategoryDropdownTitle: 'Product Categories',
  navAllProductsText: 'All Products',
  navWholesaleText: 'Wholesale',
  sojatBadgeText: 'SOJAT ORIGIN',

  // Homepage
  heroEyebrow: 'Direct from Sojat, Rajasthan, India',
  heroTitle: 'Authentic 100% Pure Sojat Henna & Natural Herbal Care',
  heroSubtitle: 'Ultra-fine sifted natural mehendi, natural indigo, and traditional Rajasthani herbal remedies crafted without chemicals or additives.',
  heroPrimaryCtaText: 'ORDER ON WHATSAPP',
  heroSecondaryCtaText: 'EXPLORE PRODUCTS',
  featuredSectionTitle: 'Featured Henna & Herbal Products',
  featuredSectionDescription: 'Bestselling Lawsonia Inermis, natural indigo & botanical formulations.',
  categorySectionTitle: 'Explore Our Product Categories',
  categorySectionDescription: 'Curated herbal formulations from Sojat farms.',
  sojatStoryBadge: 'SOJAT ORIGIN & HERITAGE',
  sojatStoryTitle: 'Cultivated in Sojat, Rajasthan — The Henna Capital of the World',
  homepageHennaSectionTitle: 'Signature Henna & Indigo Range',
  homepageHennaSectionSubtitle: 'Ultra-fine sifted natural mehendi powder & pure Indigo leaves from Sojat farms.',
  homepageHairSectionTitle: 'Herbal Hair Care Powders',
  homepageHairSectionSubtitle: 'Chemical-free Amla, Reetha, Shikakai, Bhringraj, and Hibiscus for holistic scalp care.',
  homepageViewAllProductsCta: 'VIEW ALL PRODUCTS',
  homepageSojatStoryTitle: 'Cultivated in Sojat, Rajasthan — The Henna Capital of the World',
  homepageSojatStorySubtitle: 'Sojat in Pali district, Rajasthan possesses the ideal climate, rainfall, and soil composition required to yield Lawsonia Inermis leaves with the highest natural Lawsone dye content globally.',
  homepageSojatStoryCtaText: 'LEARN MORE ABOUT OUR SOJAT FACTORY',
  whyMuskyDoseTitle: 'Pure Lawsonia Inermis Sourced From Sojat',
  whyMuskyDoseDescription: 'Sojat in Pali district, Rajasthan is globally celebrated for cultivating the finest quality henna leaves due to its ideal climate and rich soil.',
  homeFaqTitle: 'Frequently Asked Questions',
  testimonialsSectionTitle: 'Trusted by Customers & Mehendi Artists Across India',
  testimonialsSectionDescription: 'Real experiences from wholesale buyers, salon owners, and natural henna enthusiasts.',
  wholesaleCtaHeading: 'Looking for Bulk Wholesale Henna Supply?',
  wholesaleCtaDescription: 'Direct factory rates for salons, exporters, distributors, and professional mehendi artists nationwide.',
  wholesaleCtaButtonText: 'REQUEST WHOLESALE QUOTE',
  finalCtaHeading: 'Experience Genuine Sojat Mehendi Today',
  finalCtaDescription: 'Handpicked henna leaves processed with traditional care. Guaranteed 100% chemical-free purity.',
  finalCtaButtonText: 'ORDER DIRECTLY ON WHATSAPP',

  // FAQ Page
  faqHeroBadge: 'Customer Help & Support',
  faqPageTitle: 'Frequently Asked Questions',
  faqPageSubtitle: 'Find answers about our Sojat Henna purity, direct farm sourcing, processing standards, and WhatsApp ordering process.',
  faqStillHaveQuestionsTitle: 'Still Have Questions?',
  faqStillHaveQuestionsSubtitle: 'Connect directly with our Sojat team on WhatsApp for product guidance, custom weight mixes, and wholesale inquiries.',
  faqWhatsappCtaText: 'Ask Us on WhatsApp',
  faqEmptyTitle: 'FAQ Section Currently Updating',
  faqEmptyDescription: 'Our support team is updating our Frequently Asked Questions. Please reach out directly on WhatsApp for assistance.',

  // Products & Detail
  productsPageTitle: 'Our Pure Sojat Henna & Botanical Range',
  productsPageSubtitle: 'Direct from Sojat, Rajasthan, India',
  productSearchPlaceholder: 'Search natural henna, hair care...',
  productsSearchPlaceholder: 'Search products by name, category, or benefit...',
  productsFilterCategoryAll: 'All Categories',
  productsSortLabel: 'Sort By',
  productsSortFeatured: 'Featured First',
  productsSortPriceLowHigh: 'Price: Low to High',
  productsSortPriceHighLow: 'Price: High to Low',
  productsSortRating: 'Highest Rated',
  productsResetFiltersText: 'Reset all filters',
  productsLoadMoreText: 'Load More Products',
  productsCustomEnquiryBadge: 'Custom Product Enquiry & Direct Factory Orders',
  productsCustomEnquiryTitle: 'Looking for something specific?',
  productsCustomEnquirySubtitle: 'We have a wide range of henna and herbal products. If you cannot find exactly what you need, ask us directly from our Sojat manufacturing facility.',
  productsCustomEnquiryPlaceholder: 'Type your product requirement (e.g., Ultra-Fine Sifted Rajasthani Henna 25kg, Pure Indigo, Organic Rose Water)...',
  productsCustomEnquiryCta: 'Send Requirement on WhatsApp',
  productCardInStockBadge: 'In Stock',
  productCardOutOfStockBadge: 'Out of Stock',
  productCardHeritageBadge: 'Sojat Origin',
  productCardTripleShiftedBadge: 'Ultra-Fine Sifted',
  productCardViewDetailsText: 'View Details',
  productCardAddToCartText: 'Add to Cart',
  productCardWhatsappOrderText: 'Order on WhatsApp',
  productDetailBreadcrumbHome: 'Home',
  productDetailBreadcrumbProducts: 'Products',
  productDetailPriceLabel: 'Price:',
  productDetailWeightLabel: 'Weight / Pack Size:',
  productDetailQuantityLabel: 'Quantity:',
  productDetailKeyIngredientsHeading: 'Key Ingredients',
  productDetailBenefitsHeading: 'Key Benefits',
  productDetailHowToUseHeading: 'How to Use',
  productDetailDescriptionHeading: 'Product Description',
  productDetailReviewsHeading: 'Customer Reviews',
  productDetailRelatedProductsHeading: 'Related Henna & Herbal Products',
  productDetailWholesaleEnquiryCtaText: 'Need Bulk Wholesale Rates? Submit Bulk Enquiry',
  productDetailTrustBadge1: '100% Pure Sojat Lawsonia',
  productDetailTrustBadge2: 'Direct Farm Sourcing',
  productDetailTrustBadge3: 'Chemical & Dye Free',
  productDetailShareText: 'Share',
  productDetailLinkCopiedText: 'Product link copied to clipboard!',
  productDetailDirectOrderCta: 'Order Direct on WhatsApp',
  productDetailAddToCartCta: 'Add to Cart',
  productDetailOrderWhatsAppText: 'Order on WhatsApp',
  productDetailShareWhatsappText: 'Share Product Details',
  productDetailBulkInquiryTitle: 'Need Bulk / Wholesale Quantity for Salons or Export?',
  productDetailBulkInquirySubtitle: 'Direct factory rates from Sojat for quantities from 5kg to 500kg+ with custom packaging options.',
  productDetailBulkInquiryCta: 'Send Bulk Enquiry on WhatsApp',
  productDetailFaqHeading: 'Frequently Asked Questions About This Product',

  // Categories
  categoriesPageTitle: 'Product Categories',
  categoriesPageSubtitle: 'Browse our botanical collections cultivated in Sojat, Rajasthan',
  categoryProductsCountText: 'Products Available',

  // Cart, Checkout & Wishlist
  cartTitle: 'Your Shopping Cart',
  cartEmptyTitle: 'Your cart is currently empty',
  cartEmptySubtitle: 'Discover authentic 100% pure Sojat henna and botanical products.',
  cartEmptyDescription: 'Discover authentic 100% pure Sojat henna and botanical products.',
  cartEmptyCtaText: 'Explore Products',
  cartSubtotalLabel: 'Subtotal:',
  cartShippingLabel: 'Shipping:',
  cartShippingCalculatedText: 'Calculated at WhatsApp checkout',
  cartTotalLabel: 'Total Amount:',
  cartCheckoutButtonText: 'Proceed to WhatsApp Order',
  cartApplyCouponPlaceholder: 'Enter Coupon Code',
  cartApplyCouponButtonText: 'Apply',
  cartDrawerSubtitle: 'Consolidated WhatsApp order dispatch',
  cartCustomerDetailsHeading: 'Customer Details for WhatsApp Order (Optional)',
  cartCustomerNamePlaceholder: 'Your Full Name (Optional)',
  cartCustomerAddressPlaceholder: 'Delivery Address / City (Optional)',
  cartBulkDiscountLabel: 'Bulk Volume Discount:',
  cartShippingNotice: '* Shipping charges extra as applicable based on weight & delivery pincode.',

  checkoutHeaderTitle: 'Complete Order via WhatsApp',
  checkoutHeaderSubtitle: 'Review your items and customer details below.',
  checkoutPageTitle: 'Complete Order via WhatsApp',
  checkoutPlaceOrderWhatsappText: 'Confirm & Open WhatsApp Order',
  checkoutCustomerDetailsHeading: 'Customer Information',
  checkoutDeliveryAddressHeading: 'Delivery Address',
  checkoutOrderSummaryHeading: 'Order Summary',
  checkoutSubmitButtonText: 'Confirm & Open WhatsApp Order',
  checkoutNoticeText: 'Payment method: WhatsApp Confirmation. Online payment is currently disabled.',
  checkoutBackToCartText: 'Back to Shopping Cart',
  checkoutFullNameLabel: 'Full Name',
  checkoutFullNamePlaceholder: 'Enter your full name',
  checkoutMobileLabel: 'Mobile Number',
  checkoutMobilePlaceholder: '+91 82337 03080',
  checkoutAddressLabel: 'Complete Street Address',
  checkoutAddressPlaceholder: 'House/Flat No, Street, Landmark',
  checkoutCityLabel: 'City / Town',
  checkoutCityPlaceholder: 'e.g. Sojat / Jaipur / Mumbai',
  checkoutStateLabel: 'State',
  checkoutPincodeLabel: 'PIN / Postal Code',
  checkoutPincodePlaceholder: '6-digit pincode',
  checkoutCouponSectionTitle: 'Have a Discount Coupon?',

  wishlistDrawerTitle: 'Your Wishlist',
  wishlistDrawerSubtitle: 'Saved botanical items for easy ordering',
  wishlistEmptyTitle: 'Your Wishlist is Empty',
  wishlistEmptySubtitle: 'Click the heart icon on any product to save it for later.',
  wishlistExploreCta: 'Explore Products',
  wishlistMoveToCartText: 'Move to Cart',

  // Contact & Wholesale
  contactPageTitle: 'Contact Us',
  contactBadgeText: 'GET IN TOUCH',
  contactHeroTitle: 'Get in Touch with Musky Dose',
  contactHeroSubtitle: 'We are here to answer your questions regarding retail orders, bulk wholesale, or factory visits in Sojat, Rajasthan.',
  contactFormHeading: 'Send Us a Message',
  contactFormTitle: 'Send Us A Message',
  contactFormSubtitle: 'Fill out the form below to send your query directly to our Sojat team on WhatsApp.',
  contactInfoHeading: 'Contact Information',
  contactSubmitButtonText: 'Send Message via WhatsApp',
  contactFullNameLabel: 'Your Full Name',
  contactFullNamePlaceholder: 'Enter your name',
  contactPhoneLabel: 'Phone Number',
  contactPhonePlaceholder: '+91 82337 03080',
  contactEmailLabel: 'Email Address',
  contactEmailPlaceholder: 'your.email@example.com',
  contactEnquiryTypeLabel: 'Enquiry Type',
  contactMessageLabel: 'Your Message',
  contactMessagePlaceholder: 'Type your message or bulk quantity requirement here...',

  wholesalePageTitle: 'Wholesale & Bulk Orders',
  wholesaleHeroBadgeB2B: 'B2B Trade & Wholesale Supply',
  wholesaleHeroBadgeBulk: 'Bulk Quantity & Custom Packs (5kg–100kg+)',
  wholesaleHeroTitle: 'Bulk & Wholesale Henna Supply',
  wholesaleHeroSubtitle: 'Direct factory rates for salons, exporters, distributors, and mehendi artists nationwide.',
  wholesaleFormHeading: 'Submit Wholesale Requirement',
  wholesaleFormTitle: 'Submit Wholesale Requirement',
  wholesaleFormSubtitle: 'Fill out the details below to receive bulk factory rates directly from Sojat.',
  wholesaleSubmitButtonText: 'Submit Wholesale Enquiry on WhatsApp',
  wholesaleFullNameLabel: 'Full Name',
  wholesaleFullNamePlaceholder: 'Your name',
  wholesaleBusinessNameLabel: 'Business / Salon / Firm Name',
  wholesaleBusinessNamePlaceholder: 'e.g. Royal Mehendi Salon / Global Exports',
  wholesalePhoneLabel: 'Phone Number',
  wholesalePhonePlaceholder: '+91 82337 03080',
  wholesaleEmailLabel: 'Email Address',
  wholesaleEmailPlaceholder: 'your.email@example.com',
  wholesaleCityLabel: 'City',
  wholesaleCityPlaceholder: 'e.g. Mumbai / Delhi / Jaipur',
  wholesaleStateLabel: 'State',
  wholesaleStatePlaceholder: 'e.g. Rajasthan',
  wholesaleProductsLabel: 'Products Required',
  wholesaleProductsPlaceholder: 'e.g. Ultra-Fine Sifted Henna Powder, Organic Indigo Leaves, Herbal Mix...',
  wholesaleQuantityLabel: 'Approximate Quantity',
  wholesaleQuantityPlaceholder: 'e.g. 25 kg / 50 kg / 100 kg',
  wholesaleNotesLabel: 'Additional Notes / Custom Packaging Needs',
  wholesaleNotesPlaceholder: 'Mention any specific sifting grade, packaging preferences, or private label requirements...',
  wholesaleCalculatorTitle: 'Wholesale Quantity & Tier Pricing Calculator',
  wholesaleCalculatorSubtitle: 'Calculate approximate factory volume rates based on your requirement.',
  wholesaleCalculatorDisclaimer: 'Estimated factory pricing based on active volume tiers. Final logistics/shipping rates and commercial GST tax invoicing are confirmed at quotation/order stage based on your delivery destination and packaging format.',
  wholesalePricingNotice: 'Standard Base Rate / Quote Required',
  wholesaleInquiryCtaText: 'Get Wholesale Quote with this Estimate',

  // Offers
  offersHeroBadge: 'Special Festival & Promotional Deals',
  offersHeroTitle: 'Musky Dose Offers & Festival Specials',
  offersHeroSubtitle: 'Enjoy exclusive discounts on Sojat\'s finest 100% natural organic henna powder and premium herbal hair care essentials. Apply festival coupons directly at checkout or on WhatsApp!',
  offersEmptyTitle: 'No Active Campaigns Right Now',
  offersEmptyDescription: 'Check back soon for upcoming festival celebrations and special deals! You can still enjoy our everyday wholesale bulk pricing savings storewide.',

  // Footer & Trust
  footerBrandDescription: 'Authentic 100% pure, unadulterated Lawsonia Inermis Henna & natural botanical products cultivated in Sojat, Rajasthan.',
  footerContactHeading: 'Contact Us',
  footerQuickLinksHeading: 'Quick Links',
  footerCategoriesHeading: 'Categories',
  footerCustomerCareHeading: 'Customer Care',
  footerCopyrightText: '© 2026 Musky Dose. All rights reserved.',
  footerTrustTitle: 'Authentic Sojat Quality Guarantee',
  footerTrustSubtitle: 'Every pack is batch-tested for purity and lawsone dye content directly at our Sojat facility.',

  // Errors, Policy UI & Empty States
  emptySearchTitle: 'No products found matching your search',
  emptySearchDescription: 'Try searching with different keywords or clear your search filter.',
  emptySearchClearCta: 'Clear Search Filter',
  emptyCategoryTitle: 'No products in this category yet',
  emptyCategoryDescription: 'We are constantly adding fresh batches from Sojat. Check back soon!',
  notFoundBadgeText: 'PAGE NOT FOUND',
  notFoundTitle: 'Page Not Found',
  notFoundDescription: 'The page you are looking for does not exist or has been moved.',
  notFoundButtonText: 'Return to Homepage',
  notFoundExploreButtonText: 'Explore All Products',
  policyHeroBadge: 'CUSTOMER INFORMATION & TERMS',
  policyBadgeText: 'Customer Information & Terms',
  policyBackToHomeText: 'Back to Home',
  policyNotPublishedTitle: 'Policy Page Updating',
  policyNotPublishedMessage: 'This policy page is currently being updated by the business owner. Please contact us on WhatsApp for any immediate queries.',
  policyUnpublishedTitle: 'Not Published — Official Content Pending',
  policyUnpublishedDescription: 'This official policy page is currently being updated by the business owner. If you have any questions regarding orders, shipping, or returns, please reach out to our team directly on WhatsApp.',
  policyNeedSupportTitle: 'Need Immediate Support?',
  policyNeedSupportSubtitle: 'Our Sojat team is available on WhatsApp to answer questions regarding your order or policies.',
  policyNeedSupportMessage: 'Our Sojat team is available on WhatsApp to answer questions regarding your order or policies.',
  policyWhatsappCtaText: 'CONTACT ON WHATSAPP',
  policyContactWhatsappText: 'Contact on WhatsApp',
  genericErrorMessage: 'An error occurred while loading content. Please refresh or contact support.',
};

export function getCmsText(siteSettings?: Partial<SiteSettings> | null): Required<CmsTextConfig> {
  const topLevelFallbacks: Partial<CmsTextConfig> = {};
  if (siteSettings?.heroEyebrow) topLevelFallbacks.heroEyebrow = siteSettings.heroEyebrow;
  if (siteSettings?.heroTitle) topLevelFallbacks.heroTitle = siteSettings.heroTitle;
  if (siteSettings?.heroSubtitle) topLevelFallbacks.heroSubtitle = siteSettings.heroSubtitle;
  if (siteSettings?.heroPrimaryCtaText) topLevelFallbacks.heroPrimaryCtaText = siteSettings.heroPrimaryCtaText;
  if (siteSettings?.heroSecondaryCtaText) topLevelFallbacks.heroSecondaryCtaText = siteSettings.heroSecondaryCtaText;
  if (siteSettings?.featuredSectionTitle) topLevelFallbacks.featuredSectionTitle = siteSettings.featuredSectionTitle;
  if (siteSettings?.featuredSectionDescription) topLevelFallbacks.featuredSectionDescription = siteSettings.featuredSectionDescription;
  if (siteSettings?.categorySectionTitle) topLevelFallbacks.categorySectionTitle = siteSettings.categorySectionTitle;
  if (siteSettings?.categorySectionDescription) topLevelFallbacks.categorySectionDescription = siteSettings.categorySectionDescription;
  if (siteSettings?.whyMuskyDoseTitle) topLevelFallbacks.whyMuskyDoseTitle = siteSettings.whyMuskyDoseTitle;
  if (siteSettings?.whyMuskyDoseDescription) topLevelFallbacks.whyMuskyDoseDescription = siteSettings.whyMuskyDoseDescription;
  if (siteSettings?.finalCtaHeading) topLevelFallbacks.finalCtaHeading = siteSettings.finalCtaHeading;
  if (siteSettings?.finalCtaDescription) topLevelFallbacks.finalCtaDescription = siteSettings.finalCtaDescription;
  if (siteSettings?.finalCtaButtonText) topLevelFallbacks.finalCtaButtonText = siteSettings.finalCtaButtonText;
  if (siteSettings?.copyrightText) topLevelFallbacks.footerCopyrightText = siteSettings.copyrightText;
  if (siteSettings?.footerDescription) topLevelFallbacks.footerBrandDescription = siteSettings.footerDescription;

  // Canonical resolution order:
  // 1. DEFAULT_CMS_TEXT (system fallback)
  // 2. topLevelFallbacks (legacy / tab-specific fields like settings.heroTitle)
  // 3. siteSettings.cmsText (explicit user edits in CMS tab take authoritative precedence)
  return {
    ...DEFAULT_CMS_TEXT,
    ...topLevelFallbacks,
    ...(siteSettings?.cmsText || {}),
  };
}
