import { Product, Category, Order, SiteSettings, PaymentSettings, Customer, HomepageSectionConfig, HomepageVideoConfig, AnnouncementItem, NavItem, FooterLink, FooterSectionConfig, FAQItem, PolicyContent, MediaItem, WhyCard, TestimonialItem, LayoutControls, ProductGuide, BusinessContentItem, BrandColors, TrustStripItem } from './types';

export const INITIAL_BUSINESS_CONTENT: BusinessContentItem[] = [
  {
    id: 'doc-gst-cert',
    title: 'GST Registration Certificate',
    slug: 'gst-registration-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Official Goods & Services Tax Registration Certificate issued by the Government of India for Musky Dose Enterprise.',
    longDescription: 'Verified GSTIN registration for Musky Dose Enterprise located in Sojat City, Pali District, Rajasthan. Ensures fully transparent and legal B2B and B2C commercial supply of herbal products.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'ShieldCheck',
    issueDate: '2021-04-12',
    certificateNumber: '08XXXXX1234X1Z5',
    issuingAuthority: 'Government of India - GST Revenue Portal',
    verificationUrl: 'https://services.gst.gov.in',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'footer', 'trust_section'],
    sortOrder: 1,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-fssai-lic',
    title: 'FSSAI Food Safety & Standards License',
    slug: 'fssai-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Food Safety and Standards Authority of India Compliance for natural herbal & consumable botanical products.',
    longDescription: 'Compliance certification from FSSAI confirming hygiene, safety, and purity standards at our Sojat processing unit for natural powders and floral waters.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Award',
    issueDate: '2022-09-18',
    expiryDate: '2027-09-17',
    certificateNumber: '10021013000892',
    issuingAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    verificationUrl: 'https://foscos.fssai.gov.in',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'factory', 'trust_section'],
    sortOrder: 2,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-iso-9001',
    title: 'ISO 9001:2015 Quality Management Certificate',
    slug: 'iso-9001-2015-quality-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Internationally recognized Quality Management System certification for harvesting, milling, micro-sifting, and packaging Sojat Henna.',
    longDescription: 'ISO 9001:2015 standard verification certifying that our Sojat manufacturing and quality control processes adhere to strict international quality standards.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Award',
    issueDate: '2023-01-15',
    expiryDate: '2028-01-14',
    certificateNumber: 'ISO-9001-MD-SOJAT-2025',
    issuingAuthority: 'International Organization for Standardization (ISO Accredited)',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'factory', 'footer', 'trust_section'],
    sortOrder: 3,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-lab-coa',
    title: '100% Pure Lawsonia Inermis Lab Analysis Report (COA)',
    slug: 'sojat-henna-lab-analysis-coa',
    type: 'DOCUMENT',
    shortDescription: 'Comprehensive Chemical & Microbiological Lab Certificate of Analysis confirming high Lawsone Content and zero added synthetic dyes.',
    longDescription: 'NABL Accredited Laboratory Test Report verifying that Musky Dose Lawsonia Inermis leaves contain peak natural lawsone pigment density with zero synthetic dye additives, heavy metals, or PPD.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'FileCheck',
    issueDate: '2026-02-10',
    certificateNumber: 'NABL-LAB-SOJAT-2026-981',
    issuingAuthority: 'NABL Accredited Botanical & Chemical Testing Laboratory',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'factory', 'trust_section'],
    sortOrder: 4,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-msme-udyam',
    title: 'MSME Udyam Enterprise Registration',
    slug: 'msme-udyam-enterprise-registration',
    type: 'CERTIFICATE',
    shortDescription: 'Ministry of Micro, Small & Medium Enterprises Registration for Herbal & Botanical Manufacturing in Sojat.',
    longDescription: 'Official Udyam Registration Certificate issued by the Ministry of MSME, Government of India, recognizing Musky Dose Enterprise as an accredited manufacturer and processor in Sojat, Rajasthan.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Building',
    issueDate: '2020-11-05',
    certificateNumber: 'UDYAM-RJ-26-0012948',
    issuingAuthority: 'Ministry of Micro, Small and Medium Enterprises',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'footer'],
    sortOrder: 5,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const DEFAULT_LAYOUT_CONTROLS: LayoutControls = {
  mobileLogoWidth: 140,
  desktopLogoWidth: 180,
  headerPaddingVertical: 12,
  headerStyle: 'normal',
  mobileHeroHeight: 420,
  desktopHeroHeight: 560,
  heroHeadingMobileSize: 28,
  heroHeadingDesktopSize: 48,
  mobileGridColumns: 2,
  desktopGridColumns: 4,
  productCardAspectRatio: 'portrait',
  productCardPadding: 'standard',
  headingScaleFactor: 1.0,
  bodyFontSizeBase: 16,
  containerMaxWidth: 1280,
  sectionVerticalPadding: 'standard',
  mobileScreenMargin: 16,
};

export const INITIAL_MEDIA_LIBRARY: MediaItem[] = [
  {
    id: 'media-1',
    name: 'Sojat Henna Powder Banner',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 245000,
    category: 'hero',
    altText: 'Sojat Pure Ultra-Fine Sifted Henna Powder in bowl',
    uploadedAt: '2026-08-01T10:00:00Z',
    usedIn: ['Homepage Hero', 'Henna Category', 'Product: Sojat Pure Ultra-Fine Sifted Henna Powder'],
  },
  {
    id: 'media-2',
    name: 'Natural Indigo Powder',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 180000,
    category: 'products',
    altText: 'Natural Indigo Leaf Powder for Dark Hair',
    uploadedAt: '2026-08-01T10:05:00Z',
    usedIn: ['Product: Natural Indigo Powder for Dark Hair', 'Hair Care Category'],
  },
  {
    id: 'media-3',
    name: 'Sojat Henna Leaf Harvest',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 310000,
    category: 'factory',
    altText: 'Sojat Henna Crop Harvest Field',
    uploadedAt: '2026-08-01T10:10:00Z',
    usedIn: ['About Page Hero', 'Product: Sojat Pure Ultra-Fine Sifted Henna Powder'],
  },
  {
    id: 'media-4',
    name: 'Damask Rose Water Spray',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 210000,
    category: 'products',
    altText: 'Pure Sojat Damask Rose Water Spray',
    uploadedAt: '2026-08-01T10:15:00Z',
    usedIn: ['Product: Pure Sojat Damask Rose Water Spray', 'Face Care Category'],
  },
  {
    id: 'media-5',
    name: 'Herbal Botanical Processing',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 280000,
    category: 'factory',
    altText: 'Herbal Botanical Processing Facility',
    uploadedAt: '2026-08-01T10:20:00Z',
    usedIn: ['Factory Story Section', 'Herbal Products Category'],
  },
  {
    id: 'media-6',
    name: 'Ayurvedic Herbal Hair Powder',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 195000,
    category: 'products',
    altText: '9-Herbal Organic Hair Care Pack',
    uploadedAt: '2026-08-01T10:25:00Z',
    usedIn: ['Product: 9-Herbal Organic Hair Care Pack'],
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Henna',
    slug: 'henna',
    description: '100% pure, unadulterated Lawsonia Inermis powder harvested from Sojat, Rajasthan — the Henna City of India.',
    image: '/images/fallback.svg',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-2',
    name: 'Hair Care',
    slug: 'hair-care',
    description: 'Nourishing herbal hair blends, pure Indigo, Amla, Reetha, Shikakai & natural scalp elixirs.',
    image: '/images/fallback.svg',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-3',
    name: 'Face Care',
    slug: 'face-care',
    description: 'Authentic Indian herbal face packs, Damask rose waters, wild turmeric & purifying clays.',
    image: '/images/fallback.svg',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-4',
    name: 'Herbal Products',
    slug: 'herbal-products',
    description: 'Traditional wellness formulations, raw botanical leaves, seeds and cold-pressed botanical oils.',
    image: '/images/fallback.svg',
    sortOrder: 4,
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Sojat Pure Ultra-Fine Sifted Henna Powder',
    slug: 'sojat-pure-triple-shifted-henna-powder',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: 'Pure natural, cloth-filtered Rajasthani Henna powder with high lawsone pigment content for rich dark stain.',
    fullDescription: 'Harvested directly from our family farms in Sojat, Rajasthan — renowned globally as the Henna City. Our henna leaves are dried naturally under solar shade, micro-milled and ultra-fine cloth-filtered to produce a silk-like powder that gives a deep rich mahogany burgundy stain.',
    price: 249,
    compareAtPrice: 349,
    quantityOrWeight: '250g Pack',
    sku: 'MD-HEN-250',
    images: [
      '/images/fallback.svg',
      '/images/fallback.svg',
    ],
    ingredients: ['100% Pure Natural Lawsonia Inermis (Henna) Leaf Powder'],
    benefits: [
      'Deep, natural long-lasting dark stain',
      'Acts as a natural hair conditioner and coolant',
      'Zero synthetic chemicals, PPD, ammonia, or metallic salts',
      'Cloth-sifted for clog-free Mehendi cone flow',
    ],
    usageInstructions: 'Mix powder with warm water and lemon juice/tea water into a smooth paste. Cover and soak for 6-8 hours for dye release. Apply to clean hair or skin. Leave for 2-3 hours before rinsing with plain water.',
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    sortOrder: 2,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Natural Organic Indigo Powder for Dark Hair',
    slug: 'natural-organic-indigo-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Pure Indigofera Tinctoria leaf powder for natural black or rich brown shade when used with Henna.',
    fullDescription: 'Our Organic Indigo Powder is made exclusively from whole Indigofera Tinctoria leaves, solar-dried and micro-milled to create an ultra-fine, pure botanical hair dye. Used alone on light hair it produces a cool blue-green tint, but when applied after Henna (2-step method) or mixed with Henna, it yields rich chocolate-brown to jet-black tones with zero ammonia, PPD, or peroxide.',
    price: 349,
    compareAtPrice: 449,
    quantityOrWeight: '200g Pack',
    sku: 'MD-IND-200',
    images: [
      '/images/fallback.svg',
      '/images/fallback.svg',
    ],
    ingredients: ['100% Pure Indigofera Tinctoria Leaf Powder'],
    benefits: [
      'Natural black tint without peroxide or harsh dye chemicals',
      'Coats and protects delicate hair shaft',
      'Reduces premature greying and soothes scalp',
    ],
    usageInstructions: 'Mix with warm water and apply immediately on hair previously treated with Henna. Leave for 1-2 hours, then rinse with water. Avoid shampoo for 48 hours for full color oxidation.',
    stockStatus: 'in_stock',
    isActive: true,
    isFeatured: true,
    sortOrder: 3,
    createdAt: '2026-01-02T00:00:00Z',
    updatedAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Musky Dose Special Bridal Mehendi Cones (Pack of 12)',
    slug: 'musky-dose-special-bridal-mehendi-cones',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: 'Freshly prepared 100% natural Mehendi cones infused with Eucalyptus & Nilgiri essential oil.',
    fullDescription: 'Ready-to-use smooth flowing bridal henna cones made with our fresh Sojat ultra-fine sifted henna paste, pure eucalyptus oil, clove oil, and cane sugar. Delivers intense dark stain within 24-48 hours.',
    price: 299,
    compareAtPrice: 399,
    quantityOrWeight: 'Pack of 12 Cones (approx 30g each)',
    sku: 'MD-CONE-12',
    images: [
      '/images/fallback.svg',
    ],
    ingredients: ['Sojat Henna Powder', 'Eucalyptus Oil', 'Clove Oil', 'Cane Sugar', 'Filter Water'],
    benefits: [
      'Silky smooth extra fine tip flow',
      'Dark dark brown to dark red stain',
      '100% natural, chemical-free formulation',
    ],
    usageInstructions: 'Cut the tip desired thickness, apply intricate pattern on clean hands/feet. Allow to dry 2-4 hours. Scrape off paste (do not wash with water immediately). Apply mustard oil for maximum dark stain.',
    stockStatus: 'in_stock',
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
    productType: 'FINISHED',
    createdAt: '2026-01-03T00:00:00Z',
    updatedAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Herbal Amla Reetha Shikakai & Hibiscus Hair Pack',
    slug: 'herbal-amla-reetha-shikakai-hair-pack',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Traditional herbal hair-care blend for gentle cleansing, nourishing and conditioning.',
    fullDescription: 'A classic Indian ayurvedic formulation combining sun-dried natural Amla (Indian Gooseberry), Reetha (Soapnut), Shikakai, Hibiscus flower petals, and Bhringraj. Natural saponins cleanse hair without stripping natural scalp oils.',
    price: 399,
    compareAtPrice: 499,
    quantityOrWeight: '300g Jar',
    sku: 'MD-AMR-300',
    images: [
      '/images/fallback.svg',
    ],
    ingredients: ['Amla Powder', 'Reetha Powder', 'Shikakai Powder', 'Hibiscus Petal Powder', 'Bhringraj Powder'],
    benefits: [
      'Natural soap-free herbal hair cleanser',
      'Strengthens roots and reduces hair loss',
      'Adds natural volume, luster, and bounce',
    ],
    usageInstructions: 'Soak 2-3 tablespoons in lukewarm water for 30 mins to form a gentle lathering paste. Apply onto scalp and lengths, massage gently, rinse off after 15-20 minutes.',
    stockStatus: 'in_stock',
    isFeatured: false,
    isActive: true,
    sortOrder: 4,
    productType: 'POWDER',
    createdAt: '2026-01-04T00:00:00Z',
    updatedAt: '2026-01-04T00:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Pure Sojat Damask Rose Water Spray',
    slug: 'pure-sojat-damask-rose-water-spray',
    categoryId: 'cat-3',
    categoryName: 'Face Care',
    shortDescription: 'Steam-distilled pure natural Damask rose hydrosol toner & refreshing mist.',
    fullDescription: 'Directly steam distilled from handpicked morning rose blossoms. Hydrates skin, tightens pores, balances pH, and elevates skin glow with a delicate, captivating floral aroma.',
    price: 199,
    compareAtPrice: 249,
    quantityOrWeight: '100ml Glass Spray Bottle',
    sku: 'MD-ROS-100',
    images: [
      '/images/fallback.svg',
    ],
    ingredients: ['100% Steam Distilled Rosa Damascena Flower Water'],
    benefits: [
      'Instant cooling and pore tightening facial toner',
      'Restores skin moisture barrier naturally',
      'Ideal base for mixing henna and herbal face masks',
    ],
    usageInstructions: 'Mist directly onto cleansed face and neck mornings and evenings or whenever skin feels dry. Can also be mixed with herbal face powders.',
    stockStatus: 'in_stock',
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
    productType: 'FINISHED',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Sojat Raw Whole Henna Leaves',
    slug: 'sojat-raw-whole-henna-leaves',
    categoryId: 'cat-4',
    categoryName: 'Herbal Products',
    shortDescription: 'Sun-dried premium green Lawsonia Inermis leaves directly from Sojat farms.',
    fullDescription: 'Whole unground henna leaves for wholesale buyers, DIY enthusiasts, and traditional remedies. Sourced directly from our farms during the peak September-October harvest season.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '250g Pouch',
    sku: 'MD-LEAF-250',
    images: [
      '/images/fallback.svg',
    ],
    ingredients: ['100% Whole Sun-Dried Henna Leaves'],
    benefits: [
      'Pure, 100% natural whole henna harvest',
      'Ideal for home grinding, hair oils, or botanical dye extracts',
    ],
    usageInstructions: 'Grind in a dry grinder or soak overnight in water or hair oil infusions.',
    stockStatus: 'in_stock',
    isFeatured: false,
    isActive: true,
    sortOrder: 6,
    productType: 'RAW',
    createdAt: '2026-01-06T00:00:00Z',
    updatedAt: '2026-01-06T00:00:00Z',
  },
  {
    id: 'prod-bridal-henna-oil',
    name: 'Bridal Henna Oil',
    slug: 'bridal-henna-oil',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: 'Pure botanical essential oil blend to intensify and deepen natural mehndi stains.',
    fullDescription: 'An artisan blend of high-terpene botanical essential oils specifically crafted to enhance the oxidation and stain depth of fresh Sojat Henna. Scented with pure Nilgiri eucalyptus, clove bud, and tea tree extracts.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '30ml',
    sku: 'MD-BHO-30',
    images: ['/images/fallback.svg'],
    ingredients: ['Pure Eucalyptus Oil', 'Clove Bud Oil', 'Tea Tree Oil', 'Cajeput Oil', 'Fractionated Botanical Carrier'],
    benefits: ['Enhances deep rich dark henna stain', 'Aromatic natural botanical fragrance', 'Smooth application over dried mehndi motifs'],
    usageInstructions: 'Dab gently over dried henna design using cotton pad or fingertips. Leave on overnight for maximum dye oxidation.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 10,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-eucalyptus-nilgiri-oil',
    name: 'Pure Eucalyptus (Nilgiri) Essential Oil',
    slug: 'pure-eucalyptus-nilgiri-essential-oil',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: 'Steam-distilled pure Nilgiri eucalyptus oil for mehndi mixing and invigorating aromatherapy.',
    fullDescription: '100% pure steam-distilled eucalyptus oil sourced from the Nilgiri hills. Rich in natural cineole terpenes, it is traditionally used as an essential ingredient in smooth Rajasthani henna paste formulations.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-EUC-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Eucalyptus Globulus (Nilgiri) Leaf Oil'],
    benefits: ['Traditional terping agent for dark mehndi stains', 'Refreshing, invigorating herbal aroma', 'Multipurpose botanical oil for aromatherapy and DIY blends'],
    usageInstructions: 'Add a few drops to henna paste during preparation or use in aromatherapy diffusers.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 11,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-tea-tree-oil',
    name: 'Pure Tea Tree Essential Oil',
    slug: 'pure-tea-tree-essential-oil',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: '100% pure Australian tea tree essential oil for henna paste terping and purifying skincare.',
    fullDescription: 'Pure Melaleuca Alternifolia oil packed with natural terpinen-4-ol. Prized by henna artists for enhancing dye release and loved in skincare routines for its natural clarifying qualities.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-TTR-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Melaleuca Alternifolia (Tea Tree) Essential Oil'],
    benefits: ['High terpene density for henna dye release', 'Clarifying and purifying herbal properties', 'Ideal for skin toners, scalp packs, and henna paste'],
    usageInstructions: 'Mix 1-2 drops with carrier oil for topical use or add to henna paste for dye enhancement.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 12,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-clove-oil',
    name: 'Pure Clove Essential Oil',
    slug: 'pure-clove-essential-oil',
    categoryId: 'cat-1',
    categoryName: 'Henna',
    shortDescription: 'Distilled clove bud essential oil rich in eugenol for rich mehndi color and warm aroma.',
    fullDescription: 'Steam distilled from sun-cured clove buds. Contains high concentrations of eugenol, an aromatic botanical compound that creates pleasant warmth and supports henna pigment development.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-CLV-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Syzygium Aromaticum (Clove) Bud Essential Oil'],
    benefits: ['Warm eugenol-rich botanical oil', 'Traditional mehndi color booster', 'Soothing and aromatic herbal essence'],
    usageInstructions: 'Add 2-3 drops to henna powder mixture or dilute with carrier oil for massage application.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 13,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-amla-powder',
    name: 'Pure Organic Amla Powder',
    slug: 'pure-organic-amla-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Micro-milled Indian Gooseberry (Amla) powder rich in Vitamin C for hair conditioning.',
    fullDescription: '100% natural, deseeded and shade-dried Indian Gooseberry fruit powder. A classic cornerstone of Ayurvedic hair care, Amla conditions strands, supports healthy scalp pH, and imparts natural shine.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-AML-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Phyllanthus Emblica (Amla) Fruit Powder'],
    benefits: ['Rich in natural Vitamin C and bioflavonoids', 'Strengthens hair roots and tones scalp', 'Adds natural volume and texture to hair strands'],
    usageInstructions: 'Mix with water, rose water, or yogurt to form a smooth paste. Apply to scalp and hair for 30 minutes, then rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 14,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-reetha-powder',
    name: 'Pure Natural Reetha (Soapnut) Powder',
    slug: 'pure-natural-reetha-soapnut-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Natural plant saponin cleanser powder for chemical-free, gentle hair washing.',
    fullDescription: 'Crafted from pure deseeded Sapindus Mukorossi shells. Creates a mild, non-drying lather that removes excess oil and grime while keeping delicate scalp moisture balanced.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-REE-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Sapindus Mukorossi (Soapnut / Reetha) Shell Powder'],
    benefits: ['Natural plant saponin cleanser', 'Gentle soap-free lather that purifies scalp', 'Maintains natural hair moisture and softness'],
    usageInstructions: 'Mix with warm water to create a mild lathering herbal hair wash. Massage into scalp and rinse thoroughly.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 15,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-shikakai-powder',
    name: 'Pure Ayurvedic Shikakai Powder',
    slug: 'pure-ayurvedic-shikakai-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Traditional low-pH botanical conditioner powder for detangled, soft hair.',
    fullDescription: 'Finely ground from wild-harvested Acacia Concinna pods and bark. Naturally low in pH, Shikakai detangles hair without stripping natural protective oils, giving noticeable silkiness and bounce.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-SHI-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Acacia Concinna (Shikakai) Pod Powder'],
    benefits: ['Traditional low-pH natural hair conditioner', 'Gently detangles and softens hair strands', 'Promotes silky smooth hair manageability'],
    usageInstructions: 'Combine with water or herbal decoction into a paste. Apply from roots to tips, leave for 15 minutes, and rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 16,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-hibiscus-powder',
    name: 'Pure Hibiscus Flower Petal Powder',
    slug: 'pure-hibiscus-flower-petal-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Sun-dried red Hibiscus flower petal powder for deep conditioning and gloss.',
    fullDescription: '100% pure powder milled from shade-dried Hibiscus Rosa-Sinensis petals. Rich in natural botanical mucilage and alpha-hydroxy acids that condition dull hair and hydrate dry scalp.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-HIB-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Hibiscus Rosa-Sinensis Flower Petal Powder'],
    benefits: ['Natural botanical conditioning and shine enhancer', 'Nourishes scalp and supports lustrous hair', 'Imparts subtle reddish tint when combined with henna'],
    usageInstructions: 'Blend with henna or hair oil masks. Apply evenly and rinse with lukewarm water after 30-45 minutes.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 17,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-bhringraj-powder',
    name: 'Pure Bhringraj (Eclipta Alba) Powder',
    slug: 'pure-bhringraj-eclipta-alba-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Authentic Keshraj herb powder for revitalizing scalp nourishment and hair strength.',
    fullDescription: 'Known in Ayurveda as the "King of Herbs for Hair", pure whole-plant Eclipta Alba powder provides cooling relief to heated scalps, revitalizes follicles, and improves overall hair density.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-BHR-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Eclipta Alba / Prostrata (Bhringraj) Whole Herb Powder'],
    benefits: ['Revered ayurvedic Keshraj herb for hair vitality', 'Soothes and cools the scalp', 'Improves overall hair volume and thickness'],
    usageInstructions: 'Mix with coconut oil, sesame oil, or water. Massage onto scalp and leave for 30 minutes before washing.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 18,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-neem-powder',
    name: 'Pure Natural Neem Leaf Powder',
    slug: 'pure-natural-neem-leaf-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Pure Azadirachta Indica leaf powder for scalp purification and clarifying face masks.',
    fullDescription: 'Carefully harvested and solar-dried whole Neem leaves ground into a micro-fine powder. Revered for centuries in traditional Indian wellness for its clarifying, cooling, and skin-cleansing benefits.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-NEE-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Azadirachta Indica (Neem) Leaf Powder'],
    benefits: ['Clarifying botanical with purifying properties', 'Soothes itchy scalp and skin irritations', 'Ideal for dual-use hair and facial masks'],
    usageInstructions: 'Mix with rose water or plain water to make a face or scalp mask. Apply for 15-20 minutes, then rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 19,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-moringa-powder',
    name: 'Pure Organic Moringa Leaf Powder',
    slug: 'pure-organic-moringa-leaf-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Nutrient-rich Moringa Oleifera green leaf powder for enriching hair and scalp masks.',
    fullDescription: 'Pure organic Moringa Oleifera leaves milled into a fine vibrant green powder. Packed with natural plant proteins, vitamins, and minerals that replenish dry scalp and nourish brittle hair.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-MOR-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Moringa Oleifera Leaf Powder'],
    benefits: ['Rich in amino acids, minerals, and phytonutrients', 'Nourishes dry scalp and brittle hair strands', 'Adds strength and vitality to herbal hair packs'],
    usageInstructions: 'Add 1-2 tablespoons to hair packs, henna blends, or herbal rinses.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 20,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-fenugreek-methi-powder',
    name: 'Pure Fenugreek (Methi) Seed Powder',
    slug: 'pure-fenugreek-methi-seed-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'High-mucilage Methi seed powder for deep moisture, conditioning, and softness.',
    fullDescription: 'Finely ground Trigonella Foenum-Graecum seeds. Natural plant mucilage creates a rich conditioning gel upon soaking, providing remarkable slip, detangling, and moisture retention.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-FEN-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Trigonella Foenum-Graecum (Fenugreek) Seed Powder'],
    benefits: ['High mucilage content for intense slip and conditioning', 'Moisturizes dry scalp and softens rough hair', 'Improves combability and reduces tangles'],
    usageInstructions: 'Soak with warm water for 15 minutes to allow natural mucilage to expand into a gel-like mask. Apply to hair and rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 21,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-brahmi-powder',
    name: 'Pure Brahmi (Bacopa Monnieri) Powder',
    slug: 'pure-brahmi-bacopa-monnieri-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Traditional Bacopa Monnieri herb powder for scalp cooling and root vitality.',
    fullDescription: 'Pure Bacopa Monnieri leaves harvested and milled with care. Renowned in Ayurvedic hair therapy for soothing the mind, cooling the scalp, and fortifying hair strands from the root.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-BRH-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Bacopa Monnieri (Brahmi) Herb Powder'],
    benefits: ['Traditional revitalizing herb for scalp cooling', 'Nourishes hair follicles and strengthens strands', 'Enhances shine and natural softness'],
    usageInstructions: 'Mix with amla and bhringraj powders with warm water. Apply to scalp for 25-30 minutes and rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 22,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-curry-leaf-powder',
    name: 'Pure Natural Curry Leaf Powder',
    slug: 'pure-natural-curry-leaf-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Shade-dried Murraya Koenigii leaf powder rich in beta-carotene for hair nourishment.',
    fullDescription: 'Made from whole fresh green curry leaves, shade-dried to lock in essential phytonutrients. Traditional home remedy to support natural hair color depth, scalp vitality, and gloss.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-CUR-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Murraya Koenigii (Curry) Leaf Powder'],
    benefits: ['Rich in beta-carotene and essential amino acids', 'Maintains natural hair pigmentation and shine', 'Nourishes roots and supports healthy scalp balance'],
    usageInstructions: 'Infuse into warm coconut oil or mix with yogurt as a revitalizing scalp mask.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 23,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-jatamansi-powder',
    name: 'Pure Jatamansi (Spikenard) Root Powder',
    slug: 'pure-jatamansi-spikenard-root-powder',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Aromatic Spikenard rhizome powder for soothing scalp masks and traditional hair care.',
    fullDescription: 'Finely milled from wild-collected Nardostachys Jatamansi roots. Known for its earthy, woody fragrance and natural conditioning qualities that leave hair smooth, soft, and lightly aromatic.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-JAT-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Nardostachys Jatamansi Rhizome/Root Powder'],
    benefits: ['Calming and soothing herbal botanical for scalp care', 'Imparts natural conditioning and gloss', 'Traditional aromatic herb used in royal hair formulations'],
    usageInstructions: 'Blend with hair oils or herbal paste, apply gently to scalp, and rinse after 20 minutes.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 24,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-beetroot-powder',
    name: 'Pure Natural Beetroot Powder',
    slug: 'pure-natural-beetroot-powder',
    categoryId: 'cat-4',
    categoryName: 'Herbal Products',
    shortDescription: 'Vibrant natural red beetroot powder for rich burgundy dye highlights and face masks.',
    fullDescription: 'Dehydrated and finely ground Beta Vulgaris roots. A favorite botanical color additive among henna enthusiasts for achieving rich ruby tones without artificial dyes or chemicals.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-BTR-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Beta Vulgaris (Beetroot) Root Powder'],
    benefits: ['Natural botanical pigment for reddish-burgundy tints', 'Enriches henna mixes with deep ruby tones', 'Gentle on skin and hair with zero synthetic dyes'],
    usageInstructions: 'Add 2-3 tablespoons to henna powder paste for ruby highlights or mix with rose water as a facial mask.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 25,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-multani-mitti',
    name: "Pure Rajasthani Multani Mitti (Fuller's Earth)",
    slug: 'pure-rajasthani-multani-mitti-fullers-earth',
    categoryId: 'cat-3',
    categoryName: 'Face Care',
    shortDescription: 'Natural mineral clay from Rajasthan for oil-balancing, deep-pore facial cleansing.',
    fullDescription: 'Sourced from mineral-rich clay beds in Rajasthan. Multani Mitti acts as a gentle vacuum for skin impurities, drawing out excess sebum, unclogging pores, and leaving skin refreshed and toned.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-MUL-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Solum Fullonum (Fuller\'s Earth / Multani Mitti)'],
    benefits: ['Absorbs excess facial oils and deep cleanses pores', 'Natural cooling and skin refreshing clay mask', 'Leaves skin soft, smooth, and revitalized'],
    usageInstructions: 'Mix 1-2 spoons with Musky Dose Rose Water or milk. Apply evenly on face, let dry for 10-15 minutes, and rinse with cold water.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 26,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-sandalwood-powder',
    name: 'Pure Natural Sandalwood (Chandan) Powder',
    slug: 'pure-natural-sandalwood-chandan-powder',
    categoryId: 'cat-3',
    categoryName: 'Face Care',
    shortDescription: 'Classic aromatic Chandan powder for skin cooling, toning, and radiant complexion.',
    fullDescription: 'Micro-fine powder ground from authentic sandalwood. Celebrated for its calming aroma and time-honored skincare benefits, it soothes sun-exposed skin and imparts a natural, healthy radiance.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '100g',
    sku: 'MD-SAN-100',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Santalum Album (Sandalwood) Wood Powder'],
    benefits: ['Classic Indian aromatic skincare powder', 'Soothes sun-exposed skin and refines complexion', 'Delicate, lingering woody aroma'],
    usageInstructions: 'Mix with pure rose water or Multani Mitti into a fine paste. Apply on face and neck, relax for 15 minutes, then rinse.',
    stockStatus: 'in_stock',
    productType: 'POWDER',
    isActive: false,
    isFeatured: false,
    sortOrder: 27,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-lavender-oil',
    name: 'Pure Lavender Essential Oil',
    slug: 'pure-lavender-essential-oil',
    categoryId: 'cat-4',
    categoryName: 'Herbal Products',
    shortDescription: 'Steam-distilled French lavender essential oil for calming aromatherapy and skin soothing.',
    fullDescription: '100% pure Lavandula Angustifolia essential oil. Known for its relaxing floral aroma, it is widely used in bedtime diffusers, restorative bath soaks, and soothing skincare formulations.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-LAV-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Lavandula Angustifolia (Lavender) Flower Oil'],
    benefits: ['Calming, floral aromatic botanical essence', 'Soothing companion for skincare and scalp oils', 'Versatile for aromatherapy diffusers and DIY beauty'],
    usageInstructions: 'Dilute 2-3 drops in carrier oil for skin application or add to aromatherapy diffuser.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 28,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-rosemary-oil',
    name: 'Pure Rosemary Essential Oil',
    slug: 'pure-rosemary-essential-oil',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    shortDescription: 'Concentrated Rosemary leaf essential oil for scalp stimulation and hair vitality.',
    fullDescription: 'Steam distilled from fresh Rosmarinus Officinalis leaves. High in 1,8-cineole and camphor, Rosemary oil is the gold standard herbal essential oil for invigorating the scalp and hair care routines.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-ROS-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Rosmarinus Officinalis (Rosemary) Leaf Oil'],
    benefits: ['Popular aromatic herb for hair and scalp wellness', 'Invigorating herbal scent that refreshes the senses', 'Pairs exceptionally well with coconut, castor, and amla hair oils'],
    usageInstructions: 'Dilute 3-5 drops in a tablespoon of carrier oil. Massage gently into scalp or add to hair rinse water.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 29,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-peppermint-oil',
    name: 'Pure Peppermint Essential Oil',
    slug: 'pure-peppermint-essential-oil',
    categoryId: 'cat-4',
    categoryName: 'Herbal Products',
    shortDescription: 'Refreshing Mentha Piperita essential oil for cooling scalp care and uplifting aroma.',
    fullDescription: 'Steam distilled from fresh peppermint leaves, delivering a potent natural menthol concentration. Creates an instant cooling sensation on tired skin and refreshes the mind with a crisp herbal fragrance.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-PEP-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Mentha Piperita (Peppermint) Leaf Oil'],
    benefits: ['Cooling menthol sensation for scalp and skin', 'Crisp, energizing herbal aroma', 'Refreshing addition to foot soaks, scalp rinses, and diffusers'],
    usageInstructions: 'Dilute 1-2 drops with carrier oil before applying to skin or scalp. Do not use undiluted.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 30,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
  {
    id: 'prod-lemongrass-oil',
    name: 'Pure Lemongrass Essential Oil',
    slug: 'pure-lemongrass-essential-oil',
    categoryId: 'cat-4',
    categoryName: 'Herbal Products',
    shortDescription: 'Crisp citrus-herbal lemongrass essential oil for skin toning and natural room freshening.',
    fullDescription: 'Steam distilled from fresh Cymbopogon leaves. Known for its uplifting, sweet-citrus fragrance and natural astringent properties that cleanse and revitalize the skin.',
    price: 199,
    compareAtPrice: 299,
    quantityOrWeight: '10ml',
    sku: 'MD-LEM-10',
    images: ['/images/fallback.svg'],
    ingredients: ['100% Pure Cymbopogon Flexuosus (Lemongrass) Essential Oil'],
    benefits: ['Bright, citrusy herbal aroma that revitalizes spaces', 'Natural toning properties for oily skin types', 'Excellent for aromatic steam, diffusers, and body oils'],
    usageInstructions: 'Add 2-3 drops to water diffuser or dilute in massage oil for a revitalizing herbal experience.',
    stockStatus: 'in_stock',
    productType: 'OIL',
    isActive: false,
    isFeatured: false,
    sortOrder: 31,
    createdAt: '2026-08-26T00:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
];

export const DEFAULT_CHECKOUT_FIELD_CONFIG = {
  fullName: { enabled: true, required: true },
  mobile: { enabled: true, required: true },
  whatsapp: { enabled: true, required: false },
  email: { enabled: true, required: false },
  houseShop: { enabled: true, required: false },
  address: { enabled: true, required: true },
  area: { enabled: true, required: false },
  landmark: { enabled: true, required: false },
  city: { enabled: true, required: true },
  state: { enabled: true, required: true },
  pincode: { enabled: true, required: true },
  notes: { enabled: true, required: false },
};

export const DEFAULT_BRAND_COLORS: import('./types').BrandColors = {
  primary: '#183F2B',
  secondary: '#5F7F52',
  henna: '#9A4F32',
  gold: '#C49A55',
  background: '#F7F3E8',
  card: '#FFFDF8',
  text: '#22231F',
  muted: '#626c66',
  border: '#e8e2d5',
  success: '#2d6a4f',
  warning: '#c5a059',
  error: '#9A4F32',
};

export const DEFAULT_TRUST_STRIP_ITEMS: import('./types').TrustStripItem[] = [
  {
    id: 'ts-1',
    icon: 'Leaf',
    title: 'Direct Sojat Origin',
    description: '100% Pure & Authentic Henna cultivated in Sojat, Rajasthan',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'ts-2',
    icon: 'ShieldCheck',
    title: 'Ultra-Fine Sifted Powder',
    description: 'Ultra-Fine Cloth Sifted Quality for Smooth Paste',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'ts-3',
    icon: 'Sparkles',
    title: 'Chemical Free & Pure',
    description: 'No PPD, No Ammonia, 100% Natural Botanicals',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'ts-4',
    icon: 'Truck',
    title: 'Fast Dispatch',
    description: 'Express Shipping & Fresh Batch Stock Direct from Factory',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_HOMEPAGE_VIDEO: HomepageVideoConfig = {
  enabled: true,
  videoUrl: '',
  posterUrl: '/images/hero-1.webp',
  heading: 'Behind The Scenes: Pure Sojat Henna Processing',
  subheading: 'SOJAT HERITAGE IN MOTION',
  description: 'Experience the traditional harvest, solar drying, and fine micro-sifting of authentic Rajasthani Lawsonia Inermis henna in Sojat City.',
  ctaText: 'Explore Henna Collection',
  ctaUrl: '/categories/henna',
  badgeText: 'DIRECT FROM SOJAT FARMS',
  autoplay: false,
  muted: true,
  loop: false,
};

export const DEFAULT_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann-1',
    text: 'Direct Farm Dispatch from Sojat, Rajasthan • 100% Pure Lawsonia Inermis',
    link: '/about',
    enabled: true,
    sortOrder: 1,
    badge: 'ORIGIN SOJAT',
    priority: 'HIGH',
  },
  {
    id: 'ann-2',
    text: 'Wholesale & Bulk Orders Welcome • 25kg & 50kg Bags Available',
    link: '/wholesale',
    enabled: true,
    sortOrder: 2,
    badge: 'BULK & WHOLESALE',
    priority: 'NORMAL',
  },
  {
    id: 'ann-3',
    text: 'Fresh Batch Harvest Stock with Fast Courier Dispatch Across India',
    link: '/shipping-policy',
    enabled: true,
    sortOrder: 3,
    badge: 'FRESH BATCH',
    priority: 'NORMAL',
  },
];

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionConfig[] = [
  {
    id: 'announcement',
    name: 'Top Announcement Bar',
    enabled: false,
    sortOrder: 101,
    heading: 'Direct Factory Shipping from Sojat, Rajasthan',
    subheading: 'ANNOUNCEMENT',
    description: 'Weight-based pincode delivery across India',
  },
  {
    id: 'navbar',
    name: 'Header & Search Bar',
    enabled: false,
    sortOrder: 102,
    heading: 'Header Navigation',
    subheading: 'NAVIGATION',
    description: 'Header logo, search bar, navigation links and WhatsApp CTA.',
  },
  {
    id: 'hero',
    name: 'Hero Banner / Slider',
    enabled: true,
    sortOrder: 1,
    heading: 'Authentic 100% Pure Sojat Henna & Natural Herbal Care',
    subheading: 'Direct from Sojat, Rajasthan, India',
    description: 'Ultra-fine sifted natural mehendi, natural indigo, and traditional Rajasthani herbal remedies crafted without chemicals or additives.',
  },
  {
    id: 'categories',
    name: 'Shop by Category',
    enabled: true,
    sortOrder: 2,
    heading: 'Explore Our Product Collections',
    subheading: 'BROWSE CATEGORIES',
    description: 'Curated herbal formulations grown and harvested from Sojat farms.',
  },
  {
    id: 'bestsellers',
    name: 'Best Sellers / Featured Products',
    enabled: true,
    sortOrder: 3,
    heading: 'Our Best Sellers & Featured Range',
    subheading: 'POPULAR CHOICE',
    description: 'Handpicked, high-lawsone Sojat henna and customer-favorite herbal remedies.',
  },
  {
    id: 'video',
    name: 'Brand & Processing Video Showcase',
    enabled: true,
    sortOrder: 4,
    heading: 'Behind The Scenes: Pure Sojat Henna Processing',
    subheading: 'SOJAT HERITAGE IN MOTION',
    description: 'Experience the traditional harvest, solar drying, and fine micro-sifting of authentic Rajasthani Lawsonia Inermis henna in Sojat City.',
    ctaText: 'Explore Henna Collection',
    ctaLink: '/categories/henna',
  },
  {
    id: 'why_musky_dose',
    name: 'Why Musky Dose',
    enabled: true,
    sortOrder: 5,
    heading: 'Pure Lawsonia Inermis Sourced From Sojat',
    subheading: 'WHY CHOOSE MUSKY DOSE',
    description: 'Sojat in Pali district, Rajasthan is globally celebrated for cultivating the finest quality henna leaves due to its ideal climate and rich soil.',
  },
  {
    id: 'sojat_story',
    name: 'Sojat / Factory Story',
    enabled: true,
    sortOrder: 6,
    heading: 'From Sojat, Rajasthan — The Henna City of India',
    subheading: 'OUR HERITAGE',
    description: 'Nestled in Pali district, Sojat produces over 90% of India’s natural henna. High lawsone density delivers rich, long-lasting natural color.',
  },
  {
    id: 'reviews',
    name: 'Verified Customer Reviews',
    enabled: true,
    sortOrder: 7,
    heading: 'Verified Customer Testimonials',
    subheading: 'CUSTOMER TRUST',
    description: 'Read genuine feedback from salons, artists, and retail customers.',
  },
  {
    id: 'whatsapp_cta',
    name: '3-Step WhatsApp Order Guide',
    enabled: true,
    sortOrder: 8,
    heading: 'How to Order Direct on WhatsApp',
    subheading: 'SIMPLE 3-STEP ORDERING',
    description: 'Experience effortless ordering directly with our Sojat team on WhatsApp in three quick steps.',
  },
  {
    id: 'trust_strip',
    name: 'Trust Badges Strip',
    enabled: false,
    sortOrder: 103,
    heading: 'Why Customers Trust Musky Dose',
    subheading: 'PURITY & HERITAGE',
    description: 'Key guarantees of our Sojat processing unit.',
  },
  {
    id: 'new_arrivals',
    name: 'New Arrivals',
    enabled: false,
    sortOrder: 104,
    heading: 'Fresh Batch Harvest & New Arrivals',
    subheading: 'NEW ARRIVALS',
    description: 'Discover the latest micro-sifted botanical harvests freshly prepared at our Sojat facility.',
  },
  {
    id: 'guides',
    name: 'Product Guides & Articles',
    enabled: false,
    sortOrder: 105,
    heading: 'Botanical Knowledge & How-to Guides',
    subheading: 'HERBAL GUIDES',
    description: 'Learn how to mix, stain, and care for hair and skin naturally with expert guides.',
  },
  {
    id: 'wholesale_cta',
    name: 'Wholesale Enquiries Banner',
    enabled: false,
    sortOrder: 106,
    heading: 'Looking for Wholesale Henna & Herbal Products?',
    subheading: 'BULK SUPPLY & PRIVATE LABEL',
    description: 'We supply high-purity Sojat henna powder, indigo, and raw herbal powders in bulk bags and custom packaging to salons, body artists & global distributors.',
  },
  {
    id: 'footer',
    name: 'Footer Navigation',
    enabled: false,
    sortOrder: 107,
    heading: 'Footer Links & Business Details',
    subheading: 'FOOTER',
    description: 'Footer quick links, category menu, contact information, and legal policies.',
  },
];

export const DEFAULT_NAV_ITEMS: NavItem[] = [
  { id: 'nav-home', label: 'Home', href: '/', enabled: true, sortOrder: 1 },
  { id: 'nav-products', label: 'Products', href: '/products', enabled: true, sortOrder: 2 },
  { id: 'nav-categories', label: 'Categories', href: '/categories', enabled: true, sortOrder: 3 },
  { id: 'nav-wholesale', label: 'Wholesale', href: '/wholesale', enabled: true, sortOrder: 4 },
  { id: 'nav-about', label: 'About Us', href: '/about', enabled: true, sortOrder: 5 },
  { id: 'nav-factory', label: 'Our Factory', href: '/factory', enabled: true, sortOrder: 6 },
  { id: 'nav-contact', label: 'Contact', href: '/contact', enabled: true, sortOrder: 7 },
];

export const INITIAL_FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How does WhatsApp ordering work?',
    answer: 'Simply select your desired Sojat Henna or herbal products, click "Order on WhatsApp", and your order cart is automatically prepared in a structured WhatsApp message. Our Sojat team will confirm stock availability and calculate delivery charges instantly.',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'faq-2',
    question: 'Where are Musky Dose products processed?',
    answer: 'All Musky Dose products are grown, harvested, and processed directly at our facility in Sojat City, Pali District, Rajasthan — globally renowned as the Henna Capital of India.',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'faq-3',
    question: 'Are the products 100% natural and pure?',
    answer: 'Yes! We supply pure Lawsonia Inermis and unadulterated herbal powders, free from synthetic dyes, PPD, ammonia, metallic salts, or chemical additives.',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'faq-4',
    question: 'How quickly are orders dispatched from Sojat?',
    answer: 'Orders are processed and dispatched directly from our Sojat warehouse within 24 to 48 business hours via reliable express courier partners.',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_FOOTER_SECTIONS: FooterSectionConfig[] = [
  {
    id: 'footer-sec-quick',
    title: 'Quick Navigation',
    enabled: true,
    sortOrder: 1,
    links: [
      { id: 'fl-1', label: 'Home', href: '/', enabled: true, sortOrder: 1 },
      { id: 'fl-2', label: 'All Products', href: '/products', enabled: true, sortOrder: 2 },
      { id: 'fl-3', label: 'Product Categories', href: '/categories', enabled: true, sortOrder: 3 },
      { id: 'fl-4', label: 'Wholesale & Bulk Orders', href: '/wholesale', enabled: true, sortOrder: 4 },
      { id: 'fl-faq', label: 'Frequently Asked Questions (FAQ)', href: '/faq', enabled: true, sortOrder: 5 },
    ],
  },
  {
    id: 'footer-sec-business',
    title: 'Business & Story',
    enabled: true,
    sortOrder: 2,
    links: [
      { id: 'fl-5', label: 'Our Brand Story', href: '/about', enabled: true, sortOrder: 1 },
      { id: 'fl-6', label: 'Sojat Factory & Process', href: '/factory', enabled: true, sortOrder: 2 },
      { id: 'fl-docs', label: 'Certificates & Documents', href: '/documents', enabled: true, sortOrder: 3 },
      { id: 'fl-7', label: 'Contact Us', href: '/contact', enabled: true, sortOrder: 4 },
    ],
  },
  {
    id: 'footer-sec-policies',
    title: 'Support & Policies',
    enabled: true,
    sortOrder: 3,
    links: [
      { id: 'fl-shipping', label: 'Shipping & Delivery Policy', href: '/shipping-policy', enabled: true, sortOrder: 1 },
      { id: 'fl-return', label: 'Return & Refund Policy', href: '/return-policy', enabled: true, sortOrder: 2 },
      { id: 'fl-privacy', label: 'Privacy Policy', href: '/privacy-policy', enabled: true, sortOrder: 3 },
      { id: 'fl-terms', label: 'Terms & Conditions', href: '/terms', enabled: true, sortOrder: 4 },
      { id: 'fl-cancel', label: 'Cancellation Policy', href: '/cancellation-policy', enabled: true, sortOrder: 5 },
    ],
  },
];

export const DEFAULT_WHY_CARDS: WhyCard[] = [
  {
    id: 'why-1',
    title: 'Sojat Origin',
    description: "Rooted in the heart of Sojat, Rajasthan — India's world-renowned Henna hub.",
    icon: 'ShieldCheck',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'why-2',
    title: '100% Pure & Natural',
    description: 'Zero PPD, zero ammonia, zero metallic salts, zero chemical dye additives.',
    icon: 'Leaf',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'why-3',
    title: '3X Cloth Shifted',
    description: 'Micro-fine, silky smooth mehendi powder for clog-free cone flow and fast pigment release.',
    icon: 'Droplets',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'why-4',
    title: 'Direct Factory Dispatch',
    description: 'Sourced and packed directly at our Sojat facility with maximum harvest freshness.',
    icon: 'Factory',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    customerName: 'Priya Sharma',
    location: 'Jaipur, Rajasthan',
    reviewText: 'The stain from this Sojat henna powder is astonishingly deep! Pure, ultra-smooth and cone flow is completely clog-free. Best bridal henna I have used.',
    rating: 5,
    enabled: false,
    sortOrder: 1,
  },
  {
    id: 'test-2',
    customerName: 'Ananya Verma',
    location: 'Mumbai, Maharashtra',
    reviewText: 'Used the Henna + Indigo combo for natural hair coloring. Covered my grays completely with zero chemical irritation. Direct Sojat quality is evident.',
    rating: 5,
    enabled: false,
    sortOrder: 2,
  },
  {
    id: 'test-3',
    customerName: 'Rajesh Patel',
    location: 'Ahmedabad, Gujarat',
    reviewText: 'Ordering on WhatsApp was super seamless. Received fresh batch in 2 days directly from Sojat. Authentic rose water spray is also wonderful.',
    rating: 5,
    enabled: false,
    sortOrder: 3,
  },
  {
    id: 'test-4',
    customerName: 'Meenakshi Sundaram',
    location: 'Chennai, Tamil Nadu',
    reviewText: 'Our salon buys Sojat Henna in bulk from Musky Dose. Quality is consistently high lawsone grade. Highly recommended for professionals.',
    rating: 5,
    enabled: false,
    sortOrder: 4,
  },
];

import { DEFAULT_CMS_TEXT } from './cms';

export const INITIAL_SEO_KEYWORDS: import('./types').SeoKeyword[] = [
  {
    id: 'kw-1',
    keyword: 'sojat henna powder',
    targetType: 'homepage',
    targetUrl: '/',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Primary brand & product focus keyword for Musky Dose',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-2',
    keyword: 'pure rajasthani mehendi powder',
    targetType: 'homepage',
    targetUrl: '/',
    priority: 'HIGH',
    active: true,
    isPrimary: false,
    notes: 'Secondary regional focus keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-3',
    keyword: 'natural henna powder',
    targetType: 'category',
    targetId: 'cat-1',
    targetUrl: '/categories/henna',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Henna category target keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-4',
    keyword: 'triple shifted sojat henna powder 100g',
    targetType: 'product',
    targetId: 'prod-1',
    targetUrl: '/products/sojat-henna-powder-100g',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Flagship product primary target keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-5',
    keyword: 'wholesale henna manufacturer sojat',
    targetType: 'wholesale',
    targetUrl: '/wholesale',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Bulk B2B enquiry keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-6',
    keyword: 'sojat henna harvesting process',
    targetType: 'guide',
    targetId: 'guide-1',
    targetUrl: '/guides/sojat-henna-harvesting-guide',
    priority: 'MEDIUM',
    active: true,
    isPrimary: true,
    notes: 'Educational guide keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  brandColors: DEFAULT_BRAND_COLORS,
  trustStripItems: DEFAULT_TRUST_STRIP_ITEMS,
  cmsText: DEFAULT_CMS_TEXT,
  layoutControls: DEFAULT_LAYOUT_CONTROLS,
  // Brand & Identity
  brandName: 'Musky Dose',
  businessName: 'Musky Dose Enterprise',
  tagline: 'Rooted in Nature. Made for You.',
  shortDescription: 'Authentic 100% pure, unadulterated Lawsonia Inermis Henna & natural botanical products cultivated in Sojat, Rajasthan — the Henna Capital of India.',
  logoUrl: '/logo.png',
  faviconUrl: '/favicon.png',

  // Contact & Location
  displayPhone: '+91 82337 03080',
  whatsappNumber: '918233703080',
  whatsappMessageTemplate: 'Hello Musky Dose!\n\nI would like to place an order from your website.\n\nOrder Number: {orderNumber}\n\nCustomer Details:\nName: {customerName}\nPhone: {phone}\nAddress: {address}, {city}, {state} - {pincode}\n\nProducts:\n{products}\n\nSubtotal: ₹{subtotal}\nShipping: {shipping}\nProduct Amount: ₹{total}\n\nNotes: {notes}\n\nPlease confirm product availability and delivery shipping charges.',
  whatsappWholesaleMessageTemplate: 'Hello Musky Dose Wholesale Team!\n\nI want to submit a bulk/wholesale enquiry.\n\nCustomer Name: {customerName}\nBusiness Name: {businessName}\nPhone: {phone}\nWhatsApp: {whatsapp}\nEmail: {email}\nLocation: {city}, {state}\n\nProducts Required:\n{products}\n\nApprox Quantity: {quantity}\nNotes: {notes}\n\nPlease share wholesale price catalog.',
  whatsappGreeting: 'Namaste! Welcome to Musky Dose Sojat. How can we assist you today?',
  businessEmail: 'info@muskydose.in',
  websiteUrl: 'https://muskydose.in',
  address: 'Musky Dose Herbal Complex, Station Road, Sojat City, Pali District, Rajasthan - 306104, India',
  city: 'Sojat City',
  state: 'Rajasthan',
  pincode: '306104',
  country: 'India',
  businessHours: 'Monday – Saturday: 9:00 AM – 7:00 PM IST',

  // Social Links
  socials: {
    instagram: 'https://instagram.com/muskydose',
    facebook: 'https://facebook.com/muskydose',
    youtube: 'https://youtube.com/muskydose',
    twitter: 'https://twitter.com/muskydose',
  },

  // Homepage Hero
  heroEyebrow: 'Direct from Sojat, Rajasthan, India',
  heroTitle: 'Authentic 100% Pure Sojat Henna & Natural Herbal Care',
  heroSubtitle: 'Ultra-fine sifted natural mehendi, natural indigo, and traditional Rajasthani herbal remedies crafted without chemicals or additives.',
  heroPrimaryCtaText: 'SHOP PRODUCTS',
  heroPrimaryCtaLink: '/products',
  heroSecondaryCtaText: 'EXPLORE PRODUCTS',
  heroSecondaryCtaLink: '/products',
  heroImageUrl: '/images/fallback.svg',

  // Homepage Section, Product & Category Merchandising & Ordering
  homepageSections: DEFAULT_HOMEPAGE_SECTIONS,
  homepageProducts: [],
  homepageCategories: [],

  // Homepage Video Showcase Section
  homepageVideo: DEFAULT_HOMEPAGE_VIDEO,

  // Homepage Announcement Bar & Running Ticker
  announcementEnabled: true,
  announcementText: 'Pure Natural & Ultra-Fine Sifted Henna Direct from Sojat, Rajasthan',
  announcementLink: '/products',
  announcements: DEFAULT_ANNOUNCEMENTS,
  announcementTickerEnabled: true,
  announcementTickerSpeed: 'normal',

  // Homepage Sections & Toggles
  featuredSectionTitle: 'Featured Henna & Herbal Products',
  featuredSectionDescription: 'Bestselling Lawsonia Inermis, natural indigo & botanical formulations.',
  featuredSectionEnabled: true,

  categorySectionTitle: 'Explore Our Product Categories',
  categorySectionDescription: 'Curated herbal formulations from Sojat farms.',
  categorySectionEnabled: true,
  homepageCategoryCount: 6,

  whyMuskyDoseTitle: 'Pure Lawsonia Inermis Sourced From Sojat',
  whyMuskyDoseDescription: 'Sojat in Pali district, Rajasthan is globally celebrated for cultivating the finest quality henna leaves due to its ideal climate and rich soil.',
  whyCards: DEFAULT_WHY_CARDS,
  testimonials: DEFAULT_TESTIMONIALS,

  // WhatsApp 3-Step Ordering Guide
  whatsappGuideHeading: 'Simple 3-Step WhatsApp Ordering',
  whatsappGuideSubheading: 'HOW ORDERING WORKS',
  whatsappGuideDescription: 'We operate a direct WhatsApp ordering model so you receive personal service and prompt response directly from Sojat.',
  whatsappStep1Title: 'Select Your Products',
  whatsappStep1Description: 'Browse available Musky Dose products and add your required items and quantities to your order cart.',
  whatsappStep2Title: 'Order on WhatsApp',
  whatsappStep2Description: 'Click "Order on WhatsApp" to open a formatted WhatsApp message with your selected products pre-filled.',
  whatsappStep3Title: 'Direct Sojat Dispatch',
  whatsappStep3Description: 'Confirm delivery address and payment. We package and dispatch directly from Sojat, Rajasthan to your door.',

  // Wholesale Page CMS
  wholesaleHeroTitle: 'Bulk Henna & Herbal Supply Direct From Sojat, Rajasthan',
  wholesaleHeroSubtitle: 'We partner with salons, distributors, retailers, and exporters worldwide to supply 100% natural, ultra-fine sifted Henna and traditional herbal products.',
  wholesaleSectionHeading: 'Request Wholesale Price Quote',
  wholesaleSectionDescription: 'Fill out the details below and our trade team will respond within 24 hours.',

  trustSectionHeading: 'THE MUSKY DOSE PROMISE',
  trustSectionDescription: 'We preserve centuries-old Rajasthani herbal heritage with pure, ultra-fine sifted henna delivered directly to your doorstep.',
  trustSectionEnabled: true,

  aboutText: 'Musky Dose was established with a singular objective: to eliminate adulteration in henna products by providing pure, farm-fresh Lawsonia Inermis directly from Sojat.',
  aboutHeroEyebrow: 'OUR SOJAT HERITAGE',
  aboutHeroTitle: 'About Musky Dose',
  aboutHeroSubtitle: 'Delivering authentic, highest-pigment Henna & pure Indian herbal wellness directly from Sojat, Rajasthan.',
  aboutSectionEyebrow: 'THE HENNA CAPITAL OF INDIA',
  aboutSectionHeading: 'Rooted In Sojat, Rajasthan',
  aboutParagraph2: 'Sojat’s unique arid soil and climate naturally produce henna leaves containing high concentrations of Lawsone (the natural red-orange pigment). We harvest leaves at peak maturity and micro-cloth filter them to produce silk-smooth powders loved by brides and artists worldwide.',
  aboutImageUrl: '/images/fallback.svg',
  aboutPillar1Title: 'Zero Adulteration',
  aboutPillar1Description: 'We never add chemicals, artificial dyes, sodium picramate, or metallic salts to our products.',
  aboutPillar2Title: 'Ultra-Fine Sifted',
  aboutPillar2Description: 'Our ultra-fine sifting process ensures smooth, clog-free cone flow and rich dye release.',
  aboutPillar3Title: 'Farmer Empowerment',
  aboutPillar3Description: 'Sourced directly from local Sojat farmers at fair trade prices, sustaining rural livelihoods.',

  factoryStory: 'Located in Sojat City, Pali district, our plant handles solar drying, stainless steel micro-pulverizing, and ultra-fine cloth-sifting. Every batch is sealed in moisture-proof food grade pouches to preserve peak dye potency.',
  factoryImageUrl: '/images/fallback.svg',
  factorySectionHeading: 'Hygienic Manufacturing & Processing Steps',
  factorySectionDescription: 'Our facility in Sojat City houses stainless-steel pulverizers and micro-cloth sifting chambers. Every batch undergoes quality testing for lawsone pigment density, purity, and micro-sift consistency.',
  factorySectionEnabled: true,
  factoryHeroEyebrow: 'STATE-OF-THE-ART PROCESSING',
  factoryHeroTitle: 'Our Sojat Factory & Lab',
  factoryHeroSubtitle: 'Where traditional Rajasthani herbal expertise meets modern hygienic processing.',
  factoryStep1Title: 'Solar Shade Drying',
  factoryStep1Description: 'Leaves are shade-dried under controlled solar chambers to protect chlorophyll and lawsone pigments from degradation.',
  factoryStep2Title: 'Micro Pulverization',
  factoryStep2Description: 'Heavy-duty food-grade stainless steel mills grind leaves into uniform fine particles without heat buildup.',
  factoryStep3Title: 'Ultra-Fine Cloth Sifting',
  factoryStep3Description: 'Milled powder passes ultra-fine micro cloth filters to eliminate any stem fibers or coarse residue.',
  factoryStep4Title: 'Vacuum Pouch Sealing',
  factoryStep4Description: 'Packed in nitrogen-flushed, multi-layer aluminum barrier pouches to prevent moisture ingress and oxidation.',

  finalCtaHeading: 'Ready To Order Pure Sojat Henna?',
  finalCtaDescription: 'We process retail and wholesale orders directly via WhatsApp. Click below to connect with our Sojat team instantly.',
  finalCtaButtonText: 'CHAT & ORDER ON WHATSAPP (+91 82337 03080)',
  finalCtaEnabled: true,

  // Checkout Field Config
  checkoutFieldConfig: DEFAULT_CHECKOUT_FIELD_CONFIG,

  // Delivery & Order Settings
  minOrderAmount: 0,
  shippingFee: 0,
  freeShippingThreshold: 0,
  deliveryMessage: 'Direct dispatch from Sojat City, Rajasthan via Express Courier.',

  // Footer & Legal
  footerDescription: 'Authentic 100% pure, unadulterated Lawsonia Inermis Henna & natural botanical products cultivated in Sojat, Rajasthan — the Henna Capital of India.',
  copyrightText: '© 2026 Musky Dose. All Rights Reserved. Crafted with care in Sojat, Rajasthan, India.',

  // Navigation & Footer Controls
  navItems: DEFAULT_NAV_ITEMS,
  footerSections: DEFAULT_FOOTER_SECTIONS,

  // FAQ & Policies
  faqItems: INITIAL_FAQ_ITEMS,
  shippingPolicy: {
    title: 'Shipping & Delivery Policy',
    summary: 'Direct dispatch from Sojat City, Rajasthan via express courier.',
    content: 'All Musky Dose orders are processed and packaged directly from our facility in Sojat City, Pali District, Rajasthan.\n\nDispatch Timeframe:\nOrders are dispatched within 24 to 48 business hours following WhatsApp order confirmation.\n\nShipping Charges:\nShipping charges extra / calculated on order confirmation based on destination pincode and package total weight.\n\nTracking:\nTracking details and courier tracking links will be shared directly on WhatsApp once your package is dispatched.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  returnRefundPolicy: {
    title: 'Return & Refund Policy',
    summary: 'Our policy regarding returns, damage claims, and replacements.',
    content: 'At Musky Dose, we take immense pride in delivering 100% pure, freshly processed Sojat Henna and herbal products.\n\n1. Damaged or Wrong Product Delivered:\nIf you receive a damaged pouch, leaking bottle, or wrong product item, please notify our team within 48 hours of delivery via WhatsApp (+91 82337 03080) along with an unboxing photo/video.\n\n2. Replacement & Refunds:\nOnce verified, we will immediately arrange a free replacement dispatch or issue a full refund to your original payment mode or bank account.\n\n3. Non-Returnable Items:\nDue to hygiene and botanical quality standards, opened or used powder pouches cannot be returned unless verified defective.\n\n4. Contact Us:\nFor any return assistance, message our customer support team directly on WhatsApp or email info@muskydose.in.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  privacyPolicy: {
    title: 'Privacy Policy',
    summary: 'How Musky Dose protects and respects customer personal data.',
    content: 'Musky Dose ("we", "our") respects your privacy and is committed to protecting all personal information shared during browsing and ordering.\n\n1. Information We Collect:\nWhen placing an order or enquiry, we collect your Name, Phone Number, WhatsApp Number, Email Address, and Postal Delivery Address solely for order processing and delivery fulfillment.\n\n2. How We Use Your Data:\nYour details are used strictly to process orders, generate delivery labels, send WhatsApp order tracking updates, and respond to trade enquiries. We do NOT sell, rent, or trade customer databases to third parties.\n\n3. Data Security:\nYour order details are securely stored with encrypted database backups. Access is restricted exclusively to authorized Musky Dose personnel.\n\n4. Contact Privacy Officer:\nFor data deletion requests or privacy questions, write to info@muskydose.in.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  termsConditions: {
    title: 'Terms & Conditions',
    summary: 'General terms governing website usage, WhatsApp ordering, and product supply.',
    content: 'Welcome to Musky Dose (muskydose.in). By using our website or placing orders through WhatsApp, you agree to these terms:\n\n1. Botanical Product Characteristics:\nOur henna and herbal powders are 100% natural agricultural products harvested in Sojat, Rajasthan. Minor natural color variations between seasonal crop batches are normal and signify zero chemical dye standardization.\n\n2. Pricing & Orders:\nPrices listed on the website are in Indian Rupees (₹). Orders placed via WhatsApp are confirmed once stock availability and delivery location charges are verified by our team.\n\n3. Intellectual Property:\nAll brand text, logo designs, factory imagery, and trade descriptions on muskydose.in are proprietary property of Musky Dose Enterprise.\n\n4. Jurisdiction:\nAny legal disputes arising from orders or transactions are subject to the exclusive jurisdiction of courts in Pali District, Rajasthan, India.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  cancellationPolicy: {
    title: 'Cancellation Policy',
    summary: 'Guidelines for order cancellation prior to dispatch.',
    content: '1. Order Cancellation Before Dispatch:\nYou may cancel your order at zero cost anytime before dispatch by sending a cancellation request with your Order Number on WhatsApp (+91 82337 03080).\n\n2. Post-Dispatch Cancellation:\nOnce an order has been picked up and handed over to express courier transport (waybill generated), it cannot be canceled in transit.\n\n3. Refund Timelines:\nApproved order cancellations before dispatch receive 100% instant refund or WhatsApp credit within 24 business hours.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },

  // SEO & Meta
  seoTitle: 'Musky Dose — Premium Henna & Herbal Products from Sojat, Rajasthan',
  seoDescription: 'Order Pure Natural Sojat Mehendi Powder, Natural Indigo, Herbal Hair Packs & Damask Rose Water directly on WhatsApp from Musky Dose.',
  seoKeywords: 'Sojat Henna, Pure Mehendi, Rajasthani Henna, Natural Indigo, Herbal Hair Care, Damask Rose Water, Sojat City, Musky Dose',
  ogTitle: 'Musky Dose — Premium Henna & Herbal Care from Sojat, Rajasthan',
  ogDescription: 'Authentic 100% Pure Sojat Henna, Indigo, Hair & Skin Care directly from Sojat, Rajasthan.',
  ogImageUrl: '/images/fallback.svg',
  canonicalUrl: 'https://muskydose.in',

  // Media Library Initial
  mediaLibrary: INITIAL_MEDIA_LIBRARY,

  // Business Content & Documents Initial
  businessContentItems: INITIAL_BUSINESS_CONTENT,

  // SEO Keywords Initial Store
  seoKeywordsStore: INITIAL_SEO_KEYWORDS,

  // Feature Flags & Commerce Switches
  featureFlags: {
    onlinePaymentsEnabled: false,
    wholesaleEnabled: true,
    inventoryEnabled: false,
    customerAccountsEnabled: false,
    couponsEnabled: true,
    shippingIntegrationEnabled: false,
    invoiceEnabled: true,
    notificationsEnabled: false,
    recommendationsEnabled: true,
    analyticsEnabled: true,
    multilingualEnabled: false,
    exportModeEnabled: false,
  },

  paymentConfig: {
    provider: 'razorpay',
    enabled: false,
    mode: 'test',
    keyId: '',
    merchantName: 'Musky Dose',
  },

  shippingConfig: {
    provider: 'flat_rate',
    enabled: true,
    freeShippingThreshold: 999,
    flatRateAmount: 0,
  },

  invoiceConfig: {
    enabled: true,
    companyLegalName: 'Musky Dose Enterprise',
    registeredAddress: 'Musky Dose Complex, Station Road, Sojat City, Pali District, Rajasthan - 306104',
    invoicePrefix: 'MD-INV-',
  },
};

export const INITIAL_PAYMENT_SETTINGS: PaymentSettings = {
  onlinePaymentEnabled: false, // CRITICAL: Always OFF by default
  whatsappOrderEnabled: true,
  upiEnabled: true,
  upiId: 'muskydose@upi',
  upiMerchantName: 'Musky Dose Enterprise',
  cardEnabled: true,
  netbankingEnabled: true,
  gatewayMode: 'sandbox',
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'MD-ORD-8821',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98123 45678',
    customerAddress: '42 Lotus Garden, Malviya Nagar, Jaipur, Rajasthan',
    items: [
      { productId: 'prod-1', productName: 'Sojat Pure Ultra-Fine Sifted Henna Powder', quantity: 2, price: 249, weight: '250g Pack' },
      { productId: 'prod-5', productName: 'Pure Sojat Damask Rose Water Spray', quantity: 1, price: 199, weight: '100ml Spray' },
    ],
    subtotal: 697,
    shippingFee: 0,
    totalAmount: 697,
    orderStatus: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'WhatsApp',
    notes: 'Requested urgent dispatch for bridal function',
    createdAt: '2026-08-01T10:30:00Z',
    updatedAt: '2026-08-03T14:20:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'MD-ORD-8822',
    customerName: 'Ananya Verma',
    customerPhone: '+91 98765 12345',
    customerAddress: 'B-204 Green Acres, Powai, Mumbai, Maharashtra',
    items: [
      { productId: 'prod-3', productName: 'Musky Dose Special Bridal Mehendi Cones', quantity: 1, price: 299, weight: 'Pack of 12' },
    ],
    subtotal: 299,
    shippingFee: 0,
    totalAmount: 299,
    orderStatus: 'SHIPPED',
    paymentStatus: 'PAID',
    paymentMethod: 'WhatsApp',
    notes: 'Tracking ID shared via WhatsApp',
    createdAt: '2026-08-05T12:00:00Z',
    updatedAt: '2026-08-06T09:15:00Z',
  },
  {
    id: 'ord-1003',
    orderNumber: 'MD-ORD-8823',
    customerName: 'Rajesh Patel',
    customerPhone: '+91 99887 76655',
    customerAddress: '15 Sardar Patel Colony, Ahmedabad, Gujarat',
    items: [
      { productId: 'prod-2', productName: 'Natural Indigo Powder for Dark Hair', quantity: 2, price: 349, weight: '200g Pack' },
      { productId: 'prod-1', productName: 'Sojat Pure Ultra-Fine Sifted Henna Powder', quantity: 1, price: 249, weight: '250g Pack' },
    ],
    subtotal: 947,
    shippingFee: 0,
    totalAmount: 947,
    orderStatus: 'NEW',
    paymentStatus: 'UNPAID',
    paymentMethod: 'WhatsApp',
    notes: 'New WhatsApp order enquiry received',
    createdAt: '2026-08-08T08:10:00Z',
    updatedAt: '2026-08-08T08:10:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'cust-1', name: 'Priya Sharma', phone: '+91 98123 45678', email: 'priya.s@gmail.com', address: 'Jaipur, Rajasthan', totalOrders: 2, totalSpent: 1250, lastOrderAt: '2026-08-01', createdAt: '2026-07-15' },
  { id: 'cust-2', name: 'Ananya Verma', phone: '+91 98765 12345', email: 'ananya.v@yahoo.com', address: 'Mumbai, Maharashtra', totalOrders: 1, totalSpent: 299, lastOrderAt: '2026-08-05', createdAt: '2026-08-05' },
  { id: 'cust-3', name: 'Rajesh Patel', phone: '+91 99887 76655', email: 'r.patel@outlooks.com', address: 'Ahmedabad, Gujarat', totalOrders: 1, totalSpent: 947, lastOrderAt: '2026-08-08', createdAt: '2026-08-08' },
];

export const INITIAL_PRODUCT_GUIDES: ProductGuide[] = [
  {
    id: 'guide-1',
    title: 'Sojat Pure Henna Powder — Complete Dye Release & Application Guide',
    slug: 'sojat-henna-powder-complete-guide',
    coverImage: '/images/fallback.svg',
    shortIntro: 'Master the art of mixing Sojat Lawsonia Inermis henna for rich mahogany-burgundy stain and deep natural hair conditioning.',
    productId: 'prod-1',
    overview: 'Harvested from Sojat, Rajasthan — the Henna capital of India — pure Lawsonia Inermis is renowned worldwide for its high lawsone pigment density. This comprehensive guide details the exact dye release process, liquid ratios, and step-by-step application technique.',
    whatIsThis: '100% natural, unadulterated Lawsonia Inermis leaf powder that has been dried under shade, micro-milled and ultra-fine cloth-sifted for maximum dye yield.',
    keyBenefits: [
      'Rich, long-lasting mahogany reddish-brown stain on hair and skin',
      'Natural hair coat that seals split ends and adds glossy shine',
      'Zero synthetic chemicals, PPD, ammonia, or metallic salts',
      'Ultra-fine cloth-sifted texture for clog-free cone or bowl mixing',
    ],
    ingredients: [
      '100% Pure Lawsonia Inermis (Henna) Leaf Powder harvested from Sojat, Rajasthan',
    ],
    whoShouldUse: 'Anyone looking for a 100% natural red-brown hair dye, natural scalp conditioner, or professional Mehendi artists looking for reliable rich stain.',
    whoShouldAvoid: 'Individuals with rare G6PD deficiency should consult a medical physician before applying pure henna.',
    howToUse: 'Step 1: Take desired powder quantity (approx 100g for shoulder hair).\nStep 2: Mix with warm water and 1-2 tbsp lemon juice or tea decoction into a thick yoghurt consistency.\nStep 3: Cover and let sit for 6-8 hours at room temperature for dye release.\nStep 4: Apply evenly on clean dry hair. Leave for 2-3 hours before washing with plain water.',
    quantityPreparation: '100g for root touch-ups or short hair, 200g for shoulder length hair, 300g+ for long waist length hair.',
    storageInstructions: 'Store unused powder in a cool, dark, airtight container. Mixed paste can be frozen for up to 3 months.',
    importantNotes: 'Do not shampoo hair immediately after rinsing henna. Color deepens naturally over 24 to 48 hours via oxidation.',
    faqs: [
      {
        question: 'How long does Sojat Henna stain last on hair?',
        answer: 'Henna binds permanently with hair keratin. The color remains rich for 4-6 weeks with natural fading only on new hair growth.',
      },
      {
        question: 'Can I cover grey hair completely with Sojat Henna?',
        answer: 'Yes! Grey hair absorbs henna pigment beautifully, turning into a warm copper-red shade. For a natural black shade, follow with Natural Indigo Powder.',
      },
    ],
    relatedProductIds: ['prod-1', 'prod-2', 'prod-3'],
    seoTitle: 'Sojat Pure Henna Powder — Complete Usage & Dye Release Guide | Musky Dose',
    seoDescription: 'Learn how to use pure Sojat Henna powder from Rajasthan for rich mahogany stain, natural hair conditioning, and 100% chemical-free hair color.',
    published: true,
    isFeatured: true,
    sortOrder: 1,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'guide-2',
    title: 'How to Use Natural Indigo Powder for Deep Black Hair',
    slug: 'how-to-use-natural-indigo-powder-for-black-hair',
    coverImage: '/images/fallback.svg',
    shortIntro: 'The ultimate 2-step natural black hair routine using pure Sojat Henna and Indigo leaf powder without synthetic chemicals.',
    productId: 'prod-2',
    overview: 'Natural Indigo (Indigofera Tinctoria) is an ancient plant leaf powder that produces a deep blue-black pigment. When applied on hair previously treated with Henna, it yields a rich, natural midnight black shade.',
    whatIsThis: 'Pure Indigofera Tinctoria leaf powder harvested, solar-dried, and finely ground without additives or metallic dyes.',
    keyBenefits: [
      'Provides a natural 100% chemical-free black hair shade',
      'Eliminates grey hair when used in the 2-step Henna + Indigo method',
      'Soothes scalp irritation and conditions hair fibers',
    ],
    ingredients: ['100% Pure Indigofera Tinctoria Leaf Powder'],
    whoShouldUse: 'People with grey hair or dark hair wanting a deep black or dark brown natural hair color without chemical hair dyes.',
    whoShouldAvoid: 'Do not apply Indigo alone on light or grey hair without Henna base, as it may result in a bluish-green hue.',
    howToUse: 'Step 1: Apply Sojat Henna first and rinse with plain water.\nStep 2: Mix Indigo powder with lukewarm water into a smooth paste. Apply immediately (Indigo dye releases within 10-15 minutes).\nStep 3: Leave on hair for 1-2 hours, then rinse thoroughly with plain water.',
    quantityPreparation: 'Use equal parts Indigo to Henna weight (e.g. 100g Henna on Day 1, 100g Indigo on Day 2).',
    storageInstructions: 'Keep Indigo powder tightly sealed away from sunlight and moisture. Mixed Indigo paste MUST be used immediately and cannot be stored or frozen.',
    importantNotes: 'Do not use shampoo for 48 hours after Indigo application to allow full dye oxidation.',
    faqs: [
      {
        question: 'Why must Indigo be applied after Henna?',
        answer: 'Henna provides the orange-red base pigment (Lawsone) that allows Indigo (Indican) to bind strongly to the hair shaft, creating a dark black color.',
      },
    ],
    relatedProductIds: ['prod-1', 'prod-2'],
    seoTitle: 'How to Use Natural Indigo Powder for Black Hair | Musky Dose Guide',
    seoDescription: 'Master the 2-step Henna & Indigo natural hair dye method for 100% chemical-free jet black hair coverage from Musky Dose.',
    published: true,
    isFeatured: true,
    sortOrder: 2,
    createdAt: '2026-08-02T10:00:00Z',
    updatedAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'guide-3',
    title: 'Which Henna & Herbal Powder Is Right For You? (Buyer Comparison Guide)',
    slug: 'which-henna-powder-is-right-for-you',
    coverImage: '/images/fallback.svg',
    shortIntro: 'Compare Sojat Henna, Indigo, Amla, Reetha, Shikakai, and Rose Water to build your ideal natural hair & skin care routine.',
    productId: 'prod-1',
    productIds: ['prod-1', 'prod-2', 'prod-4', 'prod-5'],
    overview: 'Choosing between pure Henna, Indigo, or Ayurvedic herbal powders depends on your specific goals — whether it is grey coverage, hair growth, scalp cleansing, or skin rejuvenation.',
    whatIsThis: 'A comprehensive educational guide comparing different Musky Dose herbal offerings and their optimal combinations.',
    keyBenefits: [
      'Helps you choose the exact products suited for your hair & skin type',
      'Provides custom recipe combinations for different hair shades',
      'Explains the difference between cloth-sifted henna, raw powders, and bridal cones',
    ],
    ingredients: ['Sojat Henna', 'Natural Indigo', 'Amla', 'Reetha', 'Shikakai', 'Bhringraj', 'Multani Mitti', 'Damask Rose Water'],
    whoShouldUse: 'First-time buyers and beauty enthusiasts looking to understand the full Musky Dose botanical catalog.',
    whoShouldAvoid: 'N/A — Suitable for all readers.',
    howToUse: 'Read through our comparison breakdown below to select your desired shade or routine.',
    quantityPreparation: 'Varies by selected product routine.',
    storageInstructions: 'All Musky Dose herbal powders should be stored in dry, cool conditions.',
    importantNotes: 'Always perform a patch test on skin 24 hours prior to full application.',
    faqs: [
      {
        question: 'Can I mix Henna and Indigo together in one bowl?',
        answer: 'Yes! Mixing Henna and Indigo together in a single step yields warm brown to chestnut shades, whereas a 2-step process yields jet black.',
      },
    ],
    relatedProductIds: ['prod-1', 'prod-2', 'prod-4', 'prod-5'],
    seoTitle: 'Which Henna & Herbal Powder Is Right For You? | Musky Dose Guide',
    seoDescription: 'Compare pure Sojat Henna, Indigo, Amla, Reetha, Shikakai, and Rose Water to find the best natural products for your hair and skin.',
    published: true,
    isFeatured: true,
    sortOrder: 3,
    createdAt: '2026-08-03T10:00:00Z',
    updatedAt: '2026-08-03T10:00:00Z',
  },
];

export function normalizeKeyword(kw: string): string {
  if (!kw) return '';
  return kw.trim().toLowerCase().replace(/\s+/g, ' ');
}
