/**
 * ============================================================================
 * MUSKY DOSE — SEED & MIGRATION FIXTURE DATA STORE
 *
 * ARCHITECTURAL CLASSIFICATION: SEED / MIGRATION ONLY
 *
 * In accordance with the Musky Dose Universal Platform Governance Contract:
 * - Runtime database services (lib/db/*) MUST NOT import INITIAL_* arrays as operational fallbacks.
 * - Empty database states must fail-closed (return [] / 404), never resurrect seed fixtures.
 * - This file exists strictly for database bootstrapping, tests, and mock migration scripts.
 * ============================================================================
 */

export const DATA_STORE_ROLE = 'MIGRATION_SEED_ONLY' as const;

import { SiteSettings, PaymentSettings, HomepageSectionConfig, HomepageVideoConfig, AnnouncementItem, NavItem, FooterLink, FooterSectionConfig, FAQItem, PolicyContent, MediaItem, WhyCard, TestimonialItem, LayoutControls, BusinessContentItem, BrandColors, TrustStripItem } from './types';

export const INITIAL_BUSINESS_CONTENT: BusinessContentItem[] = [
  {
    id: 'doc-gst-cert',
    title: 'GST Registration Certificate',
    slug: 'gst-registration-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Official Goods & Services Tax Registration Certificate issued by the Government of India for Musky Dose Enterprise.',
    longDescription: 'Verified GSTIN registration for Musky Dose Enterprise located in Sojat City, Pali District, Rajasthan. Ensures fully transparent and legal B2B and B2C commercial supply of herbal products.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'ShieldCheck',
    issueDate: '2021-04-12',
    certificateNumber: '08XXXXX1234X1Z5',
    issuingAuthority: 'Government of India - GST Revenue Portal',
    verificationUrl: 'https://services.gst.gov.in',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'footer', 'trust_section'],
    sortOrder: 1,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-fssai-lic',
    title: 'FSSAI Food Safety & Standards License',
    slug: 'fssai-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Food Safety and Standards Authority of India Compliance for natural herbal & consumable botanical products.',
    longDescription: 'Compliance certification from FSSAI confirming hygiene, safety, and purity standards at our Sojat processing unit for natural powders and floral waters.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Award',
    issueDate: '2022-09-18',
    expiryDate: '2027-09-17',
    certificateNumber: '10021013000892',
    issuingAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    verificationUrl: 'https://foscos.fssai.gov.in',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'factory', 'trust_section'],
    sortOrder: 2,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-iso-9001',
    title: 'ISO 9001:2015 Quality Management Certificate',
    slug: 'iso-9001-2015-quality-certificate',
    type: 'CERTIFICATE',
    shortDescription: 'Internationally recognized Quality Management System certification for harvesting, milling, micro-sifting, and packaging Sojat Henna.',
    longDescription: 'ISO 9001:2015 standard verification certifying that our Sojat manufacturing and quality control processes adhere to strict international quality standards.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Award',
    issueDate: '2023-01-15',
    expiryDate: '2028-01-14',
    certificateNumber: 'ISO-9001-MD-SOJAT-2025',
    issuingAuthority: 'International Organization for Standardization (ISO Accredited)',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'factory', 'footer', 'trust_section'],
    sortOrder: 3,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-lab-coa',
    title: '100% Pure Lawsonia Inermis Lab Analysis Report (COA)',
    slug: 'sojat-henna-lab-analysis-coa',
    type: 'DOCUMENT',
    shortDescription: 'Comprehensive Chemical & Microbiological Lab Certificate of Analysis confirming high Lawsone Content and zero added synthetic dyes.',
    longDescription: 'NABL Accredited Laboratory Test Report verifying that Musky Dose Lawsonia Inermis leaves contain peak natural lawsone pigment density with zero synthetic dye additives, heavy metals, or PPD.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'FileCheck',
    issueDate: '2026-02-10',
    certificateNumber: 'NABL-LAB-SOJAT-2026-981',
    issuingAuthority: 'NABL Accredited Botanical & Chemical Testing Laboratory',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'factory', 'trust_section'],
    sortOrder: 4,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'doc-msme-udyam',
    title: 'MSME Udyam Enterprise Registration',
    slug: 'msme-udyam-enterprise-registration',
    type: 'CERTIFICATE',
    shortDescription: 'Ministry of Micro, Small & Medium Enterprises Registration for Herbal & Botanical Manufacturing in Sojat.',
    longDescription: 'Official Udyam Registration Certificate issued by the Ministry of MSME, Government of India, recognizing Musky Dose Enterprise as an accredited manufacturer and processor in Sojat, Rajasthan.',
    fileUrl: '',
    thumbnailUrl: '/images/fallback.svg',
    badgeIcon: 'Building',
    issueDate: '2020-11-05',
    certificateNumber: 'UDYAM-RJ-26-0012948',
    issuingAuthority: 'Ministry of Micro, Small and Medium Enterprises',
    downloadEnabled: false,
    published: false,
    displayLocations: ['documents_page', 'about', 'footer'],
    sortOrder: 5,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const DEFAULT_LAYOUT_CONTROLS: LayoutControls = {
  mobileLogoWidth: 140,
  desktopLogoWidth: 180,
  headerPaddingVertical: 12,
  headerStyle: 'normal',
  mobileHeroHeight: 420,
  desktopHeroHeight: 560,
  heroHeadingMobileSize: 28,
  heroHeadingDesktopSize: 48,
  mobileGridColumns: 2,
  desktopGridColumns: 4,
  productCardAspectRatio: 'portrait',
  productCardPadding: 'standard',
  headingScaleFactor: 1.0,
  bodyFontSizeBase: 16,
  containerMaxWidth: 1280,
  sectionVerticalPadding: 'standard',
  mobileScreenMargin: 16,
};

export const INITIAL_MEDIA_LIBRARY: MediaItem[] = [
  {
    id: 'media-1',
    name: 'Sojat Henna Powder Banner',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 245000,
    category: 'hero',
    altText: 'Sojat Pure Ultra-Fine Sifted Henna Powder in bowl',
    uploadedAt: '2026-08-01T10:00:00Z',
    usedIn: ['Homepage Hero', 'Henna Category', 'Product: Sojat Pure Ultra-Fine Sifted Henna Powder'],
  },
  {
    id: 'media-2',
    name: 'Natural Indigo Powder',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 180000,
    category: 'products',
    altText: 'Natural Indigo Leaf Powder for Dark Hair',
    uploadedAt: '2026-08-01T10:05:00Z',
    usedIn: ['Product: Natural Indigo Powder for Dark Hair', 'Hair Care Category'],
  },
  {
    id: 'media-3',
    name: 'Sojat Henna Leaf Harvest',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 310000,
    category: 'factory',
    altText: 'Sojat Henna Crop Harvest Field',
    uploadedAt: '2026-08-01T10:10:00Z',
    usedIn: ['About Page Hero', 'Product: Sojat Pure Ultra-Fine Sifted Henna Powder'],
  },
  {
    id: 'media-4',
    name: 'Damask Rose Water Spray',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 210000,
    category: 'products',
    altText: 'Pure Sojat Damask Rose Water Spray',
    uploadedAt: '2026-08-01T10:15:00Z',
    usedIn: ['Product: Pure Sojat Damask Rose Water Spray', 'Face Care Category'],
  },
  {
    id: 'media-5',
    name: 'Herbal Botanical Processing',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 280000,
    category: 'factory',
    altText: 'Herbal Botanical Processing Facility',
    uploadedAt: '2026-08-01T10:20:00Z',
    usedIn: ['Factory Story Section', 'Herbal Products Category'],
  },
  {
    id: 'media-6',
    name: 'Ayurvedic Herbal Hair Powder',
    url: '/images/fallback.svg',
    type: 'image/jpeg',
    size: 195000,
    category: 'products',
    altText: '9-Herbal Natural Botanical Hair Care Pack',
    uploadedAt: '2026-08-01T10:25:00Z',
    usedIn: ['Product: 9-Herbal Natural Botanical Hair Care Pack'],
  },
];

export const DEFAULT_CHECKOUT_FIELD_CONFIG = {
  fullName: { enabled: true, required: true },
  mobile: { enabled: true, required: true },
  whatsapp: { enabled: true, required: false },
  email: { enabled: true, required: false },
  houseShop: { enabled: true, required: false },
  address: { enabled: true, required: true },
  area: { enabled: true, required: false },
  landmark: { enabled: true, required: false },
  city: { enabled: true, required: true },
  state: { enabled: true, required: true },
  pincode: { enabled: true, required: true },
  notes: { enabled: true, required: false },
};

export const DEFAULT_BRAND_COLORS: import('./types').BrandColors = {
  primary: '#183F2B',
  secondary: '#5F7F52',
  henna: '#9A4F32',
  gold: '#C49A55',
  background: '#F7F3E8',
  card: '#FFFDF8',
  text: '#22231F',
  muted: '#626c66',
  border: '#e8e2d5',
  success: '#2d6a4f',
  warning: '#c5a059',
  error: '#9A4F32',
};

export const DEFAULT_TRUST_STRIP_ITEMS: import('./types').TrustStripItem[] = [
  {
    id: 'ts-1',
    icon: 'Leaf',
    title: 'Direct Sojat Origin',
    description: '100% Pure & Authentic Henna cultivated in Sojat, Rajasthan',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'ts-2',
    icon: 'ShieldCheck',
    title: 'Triple Sifted Powder',
    description: 'Ultra-Fine Cloth Sifted Quality for Smooth Paste',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'ts-3',
    icon: 'Sparkles',
    title: 'Chemical Free & Pure',
    description: 'No PPD, No Ammonia, 100% Natural Botanicals',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'ts-4',
    icon: 'Truck',
    title: 'Fast Dispatch',
    description: 'Express Shipping & Fresh Batch Stock Direct from Factory',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_HOMEPAGE_VIDEO: HomepageVideoConfig = {
  enabled: true,
  videoUrl: '',
  posterUrl: '/images/hero-1.webp',
  heading: 'Behind The Scenes: Pure Sojat Henna Processing',
  subheading: 'SOJAT HERITAGE IN MOTION',
  description: 'Experience the traditional harvest, solar drying, and fine micro-sifting of authentic Rajasthani Lawsonia Inermis henna in Sojat City.',
  ctaText: 'Explore Henna Collection',
  ctaUrl: '/categories/henna',
  badgeText: 'DIRECT FROM SOJAT FARMS',
  autoplay: false,
  muted: true,
  loop: false,
};

export const DEFAULT_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann-1',
    text: 'Direct Farm Dispatch from Sojat, Rajasthan • 100% Pure Lawsonia Inermis',
    link: '/about',
    enabled: true,
    sortOrder: 1,
    badge: 'ORIGIN SOJAT',
    priority: 'HIGH',
  },
  {
    id: 'ann-2',
    text: 'Wholesale & Bulk Orders Welcome • 25kg & 50kg Bags Available',
    link: '/wholesale',
    enabled: true,
    sortOrder: 2,
    badge: 'BULK & WHOLESALE',
    priority: 'NORMAL',
  },
  {
    id: 'ann-3',
    text: 'Fresh Batch Harvest Stock with Fast Courier Dispatch Across India',
    link: '/shipping-policy',
    enabled: true,
    sortOrder: 3,
    badge: 'FRESH BATCH',
    priority: 'NORMAL',
  },
];

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionConfig[] = [
  {
    id: 'announcement',
    name: 'Top Announcement Bar',
    enabled: false,
    sortOrder: 101,
    heading: 'Direct Factory Shipping from Sojat, Rajasthan',
    subheading: 'ANNOUNCEMENT',
    description: 'Weight-based pincode delivery across India',
  },
  {
    id: 'navbar',
    name: 'Header & Search Bar',
    enabled: false,
    sortOrder: 102,
    heading: 'Header Navigation',
    subheading: 'NAVIGATION',
    description: 'Header logo, search bar, navigation links and WhatsApp CTA.',
  },
  {
    id: 'hero',
    name: 'Hero Banner / Slider',
    enabled: true,
    sortOrder: 1,
    heading: 'Authentic 100% Pure Sojat Henna & Natural Herbal Care',
    subheading: 'Direct from Sojat, Rajasthan, India',
    description: 'Ultra-fine sifted natural mehendi, natural indigo, and traditional Rajasthani herbal remedies crafted without chemicals or additives.',
  },
  {
    id: 'trust_strip',
    name: 'Trust Badges Strip',
    enabled: true,
    sortOrder: 2,
    heading: 'Why Customers Trust Musky Dose',
    subheading: 'PURITY & HERITAGE',
    description: 'Key guarantees of our Sojat processing unit.',
  },
  {
    id: 'categories',
    name: 'Shop by Category',
    enabled: true,
    sortOrder: 3,
    heading: 'Explore Our Product Collections',
    subheading: 'BROWSE CATEGORIES',
    description: 'Curated herbal formulations grown and harvested from Sojat farms.',
  },
  {
    id: 'bestsellers',
    name: 'Best Sellers / Featured Products',
    enabled: true,
    sortOrder: 4,
    heading: 'Our Best Sellers & Featured Range',
    subheading: 'POPULAR CHOICE',
    description: 'Handpicked, high-lawsone Sojat henna and customer-favorite herbal remedies.',
  },
  {
    id: 'video',
    name: 'Brand & Processing Video Showcase',
    enabled: true,
    sortOrder: 5,
    heading: 'Behind The Scenes: Pure Sojat Henna Processing',
    subheading: 'SOJAT HERITAGE IN MOTION',
    description: 'Experience the traditional harvest, solar drying, and fine micro-sifting of authentic Rajasthani Lawsonia Inermis henna in Sojat City.',
    ctaText: 'Explore Henna Collection',
    ctaLink: '/categories/henna',
  },
  {
    id: 'why_musky_dose',
    name: 'Why Musky Dose',
    enabled: true,
    sortOrder: 6,
    heading: 'Pure Lawsonia Inermis Sourced From Sojat',
    subheading: 'WHY CHOOSE MUSKY DOSE',
    description: 'Sojat in Pali district, Rajasthan is globally celebrated for cultivating the finest quality henna leaves due to its ideal climate and rich soil.',
  },
  {
    id: 'sojat_story',
    name: 'Sojat / Factory Story',
    enabled: true,
    sortOrder: 7,
    heading: 'From Sojat, Rajasthan — The Henna City of India',
    subheading: 'OUR HERITAGE',
    description: 'Nestled in Pali district, Sojat produces over 90% of India’s natural henna. High lawsone density delivers rich, long-lasting natural color.',
  },
  {
    id: 'reviews',
    name: 'Verified Customer Reviews',
    enabled: true,
    sortOrder: 8,
    heading: 'Verified Customer Testimonials',
    subheading: 'CUSTOMER TRUST',
    description: 'Read genuine feedback from salons, artists, and retail customers.',
  },
  {
    id: 'wholesale_cta',
    name: 'Wholesale & Bulk Enquiries',
    enabled: true,
    sortOrder: 9,
    heading: 'Looking for Wholesale Henna & Bulk Supply?',
    subheading: 'B2B & WHOLESALE',
    description: 'Connect with Musky Dose for bulk requirements, 25kg/50kg bags, salon supply, and custom private label packaging directly from Sojat, Rajasthan.',
  },
  {
    id: 'whatsapp_cta',
    name: '3-Step WhatsApp Order Guide',
    enabled: false,
    sortOrder: 10,
    heading: 'How to Order Direct on WhatsApp',
    subheading: 'SIMPLE 3-STEP ORDERING',
    description: 'Experience effortless ordering directly with our Sojat team on WhatsApp in three quick steps.',
  },
  {
    id: 'new_arrivals',
    name: 'New Arrivals',
    enabled: false,
    sortOrder: 104,
    heading: 'Fresh Batch Harvest & New Arrivals',
    subheading: 'NEW ARRIVALS',
    description: 'Discover the latest micro-sifted botanical harvests freshly prepared at our Sojat facility.',
  },
  {
    id: 'guides',
    name: 'Product Guides & Articles',
    enabled: false,
    sortOrder: 105,
    heading: 'Botanical Knowledge & How-to Guides',
    subheading: 'HERBAL GUIDES',
    description: 'Learn how to mix, stain, and care for hair and skin naturally with expert guides.',
  },
  {
    id: 'wholesale_cta',
    name: 'Wholesale Enquiries Banner',
    enabled: false,
    sortOrder: 106,
    heading: 'Looking for Wholesale Henna & Herbal Products?',
    subheading: 'BULK SUPPLY & PRIVATE LABEL',
    description: 'We supply high-purity Sojat henna powder, indigo, and raw herbal powders in bulk bags and custom packaging to salons, body artists & global distributors.',
  },
  {
    id: 'footer',
    name: 'Footer Navigation',
    enabled: false,
    sortOrder: 107,
    heading: 'Footer Links & Business Details',
    subheading: 'FOOTER',
    description: 'Footer quick links, category menu, contact information, and legal policies.',
  },
];

export const DEFAULT_NAV_ITEMS: NavItem[] = [
  { id: 'nav-home', label: 'Home', href: '/', enabled: true, sortOrder: 1 },
  { id: 'nav-products', label: 'Products', href: '/products', enabled: true, sortOrder: 2 },
  { id: 'nav-categories', label: 'Categories', href: '/categories', enabled: true, sortOrder: 3 },
  { id: 'nav-wholesale', label: 'Wholesale', href: '/wholesale', enabled: true, sortOrder: 4 },
  { id: 'nav-about', label: 'About Us', href: '/about', enabled: true, sortOrder: 5 },
  { id: 'nav-factory', label: 'Our Factory', href: '/factory', enabled: true, sortOrder: 6 },
  { id: 'nav-contact', label: 'Contact', href: '/contact', enabled: true, sortOrder: 7 },
];

export const INITIAL_FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How does WhatsApp ordering work?',
    answer: 'Simply select your desired Sojat Henna or herbal products, click "Order on WhatsApp", and your order cart is automatically prepared in a structured WhatsApp message. Our Sojat team will confirm stock availability and calculate delivery charges instantly.',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'faq-2',
    question: 'Where are Musky Dose products processed?',
    answer: 'All Musky Dose products are grown, harvested, and processed directly at our facility in Sojat City, Pali District, Rajasthan — globally renowned as the Henna Capital of India.',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'faq-3',
    question: 'Are the products 100% natural and pure?',
    answer: 'Yes! We supply pure Lawsonia Inermis and unadulterated herbal powders, free from synthetic dyes, PPD, ammonia, metallic salts, or chemical additives.',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'faq-4',
    question: 'How quickly are orders dispatched from Sojat?',
    answer: 'Orders are processed and dispatched directly from our Sojat warehouse within 24 to 48 business hours via reliable express courier partners.',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_FOOTER_SECTIONS: FooterSectionConfig[] = [
  {
    id: 'footer-sec-quick',
    title: 'Quick Navigation',
    enabled: true,
    sortOrder: 1,
    links: [
      { id: 'fl-1', label: 'Home', href: '/', enabled: true, sortOrder: 1 },
      { id: 'fl-2', label: 'All Products', href: '/products', enabled: true, sortOrder: 2 },
      { id: 'fl-3', label: 'Product Categories', href: '/categories', enabled: true, sortOrder: 3 },
      { id: 'fl-4', label: 'Wholesale & Bulk Orders', href: '/wholesale', enabled: true, sortOrder: 4 },
      { id: 'fl-faq', label: 'Frequently Asked Questions (FAQ)', href: '/faq', enabled: true, sortOrder: 5 },
    ],
  },
  {
    id: 'footer-sec-business',
    title: 'Business & Story',
    enabled: true,
    sortOrder: 2,
    links: [
      { id: 'fl-5', label: 'Our Brand Story', href: '/about', enabled: true, sortOrder: 1 },
      { id: 'fl-6', label: 'Sojat Factory & Process', href: '/factory', enabled: true, sortOrder: 2 },
      { id: 'fl-docs', label: 'Certificates & Documents', href: '/documents', enabled: true, sortOrder: 3 },
      { id: 'fl-7', label: 'Contact Us', href: '/contact', enabled: true, sortOrder: 4 },
    ],
  },
  {
    id: 'footer-sec-policies',
    title: 'Support & Policies',
    enabled: true,
    sortOrder: 3,
    links: [
      { id: 'fl-shipping', label: 'Shipping & Delivery Policy', href: '/shipping-policy', enabled: true, sortOrder: 1 },
      { id: 'fl-return', label: 'Return & Refund Policy', href: '/return-policy', enabled: true, sortOrder: 2 },
      { id: 'fl-privacy', label: 'Privacy Policy', href: '/privacy-policy', enabled: true, sortOrder: 3 },
      { id: 'fl-terms', label: 'Terms & Conditions', href: '/terms', enabled: true, sortOrder: 4 },
      { id: 'fl-cancel', label: 'Cancellation Policy', href: '/cancellation-policy', enabled: true, sortOrder: 5 },
    ],
  },
];

export const DEFAULT_WHY_CARDS: WhyCard[] = [
  {
    id: 'why-1',
    title: 'Sojat Origin',
    description: "Rooted in the heart of Sojat, Rajasthan — India's world-renowned Henna hub.",
    icon: 'ShieldCheck',
    enabled: true,
    sortOrder: 1,
  },
  {
    id: 'why-2',
    title: '100% Pure & Natural',
    description: 'Zero PPD, zero ammonia, zero metallic salts, zero chemical dye additives.',
    icon: 'Leaf',
    enabled: true,
    sortOrder: 2,
  },
  {
    id: 'why-3',
    title: '3X Cloth Sifted',
    description: 'Micro-fine, silky smooth mehendi powder for clog-free cone flow and fast pigment release.',
    icon: 'Droplets',
    enabled: true,
    sortOrder: 3,
  },
  {
    id: 'why-4',
    title: 'Direct Factory Dispatch',
    description: 'Sourced and packed directly at our Sojat facility with maximum harvest freshness.',
    icon: 'Factory',
    enabled: true,
    sortOrder: 4,
  },
];

export const DEFAULT_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    customerName: 'Priya Sharma',
    location: 'Jaipur, Rajasthan',
    reviewText: 'The stain from this Sojat henna powder is astonishingly deep! Pure, ultra-smooth and cone flow is completely clog-free. Best bridal henna I have used.',
    rating: 5,
    enabled: false,
    sortOrder: 1,
  },
  {
    id: 'test-2',
    customerName: 'Ananya Verma',
    location: 'Mumbai, Maharashtra',
    reviewText: 'Used the Henna + Indigo combo for natural hair coloring. Covered my grays completely with zero chemical irritation. Direct Sojat quality is evident.',
    rating: 5,
    enabled: false,
    sortOrder: 2,
  },
  {
    id: 'test-3',
    customerName: 'Rajesh Patel',
    location: 'Ahmedabad, Gujarat',
    reviewText: 'Ordering on WhatsApp was super seamless. Received fresh batch in 2 days directly from Sojat. Authentic rose water spray is also wonderful.',
    rating: 5,
    enabled: false,
    sortOrder: 3,
  },
  {
    id: 'test-4',
    customerName: 'Meenakshi Sundaram',
    location: 'Chennai, Tamil Nadu',
    reviewText: 'Our salon buys Sojat Henna in bulk from Musky Dose. Quality is consistently high lawsone grade. Highly recommended for professionals.',
    rating: 5,
    enabled: false,
    sortOrder: 4,
  },
];

import { DEFAULT_CMS_TEXT } from './cms';

export const INITIAL_SEO_KEYWORDS: import('./types').SeoKeyword[] = [
  {
    id: 'kw-1',
    keyword: 'sojat henna powder',
    targetType: 'homepage',
    targetUrl: '/',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Primary brand & product focus keyword for Musky Dose',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-2',
    keyword: 'pure rajasthani mehendi powder',
    targetType: 'homepage',
    targetUrl: '/',
    priority: 'HIGH',
    active: true,
    isPrimary: false,
    notes: 'Secondary regional focus keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-3',
    keyword: 'natural henna powder',
    targetType: 'category',
    targetId: 'cat-1',
    targetUrl: '/categories/henna',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Henna category target keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-4',
    keyword: 'triple sifted sojat henna powder 100g',
    targetType: 'product',
    targetId: 'prod-1',
    targetUrl: '/products/sojat-henna-powder-100g',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Flagship product primary target keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-5',
    keyword: 'wholesale henna manufacturer sojat',
    targetType: 'wholesale',
    targetUrl: '/wholesale',
    priority: 'HIGH',
    active: true,
    isPrimary: true,
    notes: 'Bulk B2B enquiry keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'kw-6',
    keyword: 'sojat henna harvesting process',
    targetType: 'guide',
    targetId: 'guide-1',
    targetUrl: '/guides/sojat-henna-harvesting-guide',
    priority: 'MEDIUM',
    active: true,
    isPrimary: true,
    notes: 'Educational guide keyword',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  brandColors: DEFAULT_BRAND_COLORS,
  trustStripItems: DEFAULT_TRUST_STRIP_ITEMS,
  cmsText: DEFAULT_CMS_TEXT,
  layoutControls: DEFAULT_LAYOUT_CONTROLS,
  // Brand & Identity
  brandName: 'Musky Dose',
  businessName: 'Musky Dose Enterprise',
  tagline: 'Rooted in Nature. Made for You.',
  shortDescription: 'Authentic 100% pure, unadulterated Lawsonia Inermis Henna & natural botanical products cultivated in Sojat, Rajasthan — the Henna Capital of India.',
  logoUrl: '/logo.png',
  faviconUrl: '/favicon.png',

  // Contact & Location
  displayPhone: '+91 82337 03080',
  whatsappNumber: '918233703080',
  whatsappMessageTemplate: 'Hello Musky Dose!\n\nI would like to place an order from your website.\n\nOrder Number: {orderNumber}\n\nCustomer Details:\nName: {customerName}\nPhone: {phone}\nAddress: {address}, {city}, {state} - {pincode}\n\nProducts:\n{products}\n\nSubtotal: ₹{subtotal}\nShipping: {shipping}\nProduct Amount: ₹{total}\n\nNotes: {notes}\n\nPlease confirm product availability and delivery shipping charges.',
  whatsappWholesaleMessageTemplate: 'Hello Musky Dose Wholesale Team!\n\nI want to submit a bulk/wholesale enquiry.\n\nCustomer Name: {customerName}\nBusiness Name: {businessName}\nPhone: {phone}\nWhatsApp: {whatsapp}\nEmail: {email}\nLocation: {city}, {state}\n\nProducts Required:\n{products}\n\nApprox Quantity: {quantity}\nNotes: {notes}\n\nPlease share wholesale price catalog.',
  whatsappGreeting: 'Namaste! Welcome to Musky Dose Sojat. How can we assist you today?',
  businessEmail: 'info@muskydose.in',
  websiteUrl: 'https://muskydose.in',
  address: 'Musky Dose Products, Village: Dholiwadi Ka Bas, Post: Sojat City, District: Pali, Rajasthan – 306104, India',
  city: 'Sojat City',
  state: 'Rajasthan',
  pincode: '306104',
  country: 'India',
  businessHours: 'Monday – Saturday: 9:00 AM – 7:00 PM IST',

  // Social Links
  socials: {
    instagram: 'https://instagram.com/muskydose',
    facebook: 'https://facebook.com/muskydose',
    youtube: 'https://youtube.com/muskydose',
    twitter: 'https://twitter.com/muskydose',
  },

  // Homepage Hero
  heroEyebrow: 'Direct from Sojat, Rajasthan, India',
  heroTitle: 'Authentic 100% Pure Sojat Henna & Natural Herbal Care',
  heroSubtitle: 'Ultra-fine sifted natural mehendi, natural indigo, and traditional Rajasthani herbal remedies crafted without chemicals or additives.',
  heroPrimaryCtaText: 'SHOP PRODUCTS',
  heroPrimaryCtaLink: '/products',
  heroSecondaryCtaText: 'WHOLESALE',
  heroSecondaryCtaLink: '/wholesale',
  heroImageUrl: '/images/fallback.svg',

  // Homepage Section, Product & Category Merchandising & Ordering
  homepageSections: DEFAULT_HOMEPAGE_SECTIONS,
  homepageProducts: [],
  homepageCategories: [],

  // Homepage Video Showcase Section
  homepageVideo: DEFAULT_HOMEPAGE_VIDEO,

  // Homepage Announcement Bar & Running Ticker
  announcementEnabled: true,
  announcementText: 'Pure Natural & Ultra-Fine Sifted Henna Direct from Sojat, Rajasthan',
  announcementLink: '/products',
  announcements: DEFAULT_ANNOUNCEMENTS,
  announcementTickerEnabled: true,
  announcementTickerSpeed: 'normal',

  // Homepage Sections & Toggles
  featuredSectionTitle: 'Featured Henna & Herbal Products',
  featuredSectionDescription: 'Bestselling Lawsonia Inermis, natural indigo & botanical formulations.',
  featuredSectionEnabled: true,

  categorySectionTitle: 'Explore Our Product Categories',
  categorySectionDescription: 'Curated herbal formulations from Sojat farms.',
  categorySectionEnabled: true,
  homepageCategoryCount: 6,

  whyMuskyDoseTitle: 'Pure Lawsonia Inermis Sourced From Sojat',
  whyMuskyDoseDescription: 'Sojat in Pali district, Rajasthan is globally celebrated for cultivating the finest quality henna leaves due to its ideal climate and rich soil.',
  whyCards: DEFAULT_WHY_CARDS,
  testimonials: DEFAULT_TESTIMONIALS,

  // WhatsApp 3-Step Ordering Guide
  whatsappGuideHeading: 'Simple 3-Step WhatsApp Ordering',
  whatsappGuideSubheading: 'HOW ORDERING WORKS',
  whatsappGuideDescription: 'We operate a direct WhatsApp ordering model so you receive personal service and prompt response directly from Sojat.',
  whatsappStep1Title: 'Select Your Products',
  whatsappStep1Description: 'Browse available Musky Dose products and add your required items and quantities to your order cart.',
  whatsappStep2Title: 'Order on WhatsApp',
  whatsappStep2Description: 'Click "Order on WhatsApp" to open a formatted WhatsApp message with your selected products pre-filled.',
  whatsappStep3Title: 'Direct Sojat Dispatch',
  whatsappStep3Description: 'Confirm delivery address and payment. We package and dispatch directly from Sojat, Rajasthan to your door.',

  // Wholesale Page CMS
  wholesaleHeroTitle: 'Bulk Henna & Herbal Supply Direct From Sojat, Rajasthan',
  wholesaleHeroSubtitle: 'We partner with salons, distributors, retailers, and exporters worldwide to supply 100% natural, ultra-fine sifted Henna and traditional herbal products.',
  wholesaleSectionHeading: 'Request Wholesale Price Quote',
  wholesaleSectionDescription: 'Fill out the details below and our trade team will respond within 24 hours.',

  trustSectionHeading: 'THE MUSKY DOSE PROMISE',
  trustSectionDescription: 'We preserve centuries-old Rajasthani herbal heritage with pure, ultra-fine sifted henna delivered directly to your doorstep.',
  trustSectionEnabled: true,

  aboutText: 'Musky Dose was established with a singular objective: to eliminate adulteration in henna products by providing pure, farm-fresh Lawsonia Inermis directly from Sojat.',
  aboutHeroEyebrow: 'OUR SOJAT HERITAGE',
  aboutHeroTitle: 'About Musky Dose',
  aboutHeroSubtitle: 'Delivering authentic, highest-pigment Henna & pure Indian herbal wellness directly from Sojat, Rajasthan.',
  aboutSectionEyebrow: 'THE HENNA CAPITAL OF INDIA',
  aboutSectionHeading: 'Rooted In Sojat, Rajasthan',
  aboutParagraph2: 'Sojat’s unique arid soil and climate naturally produce henna leaves containing high concentrations of Lawsone (the natural red-orange pigment). We harvest leaves at peak maturity and micro-cloth filter them to produce silk-smooth powders loved by brides and artists worldwide.',
  aboutImageUrl: '/images/fallback.svg',
  aboutPillar1Title: 'Zero Adulteration',
  aboutPillar1Description: 'We never add chemicals, artificial dyes, sodium picramate, or metallic salts to our products.',
  aboutPillar2Title: 'Ultra-Fine Sifted',
  aboutPillar2Description: 'Our ultra-fine sifting process ensures smooth, clog-free cone flow and rich dye release.',
  aboutPillar3Title: 'Farmer Empowerment',
  aboutPillar3Description: 'Sourced directly from local Sojat farmers at fair trade prices, sustaining rural livelihoods.',

  factoryStory: 'Located in Sojat City, Pali district, our plant handles solar drying, stainless steel micro-pulverizing, and ultra-fine cloth-sifting. Every batch is sealed in moisture-proof food grade pouches to preserve peak dye potency.',
  factoryImageUrl: '/images/fallback.svg',
  factorySectionHeading: 'Hygienic Manufacturing & Processing Steps',
  factorySectionDescription: 'Our facility in Sojat City houses stainless-steel pulverizers and micro-cloth sifting chambers. Every batch undergoes quality testing for lawsone pigment density, purity, and micro-sift consistency.',
  factorySectionEnabled: true,
  factoryHeroEyebrow: 'STATE-OF-THE-ART PROCESSING',
  factoryHeroTitle: 'Our Sojat Factory & Lab',
  factoryHeroSubtitle: 'Where traditional Rajasthani herbal expertise meets modern hygienic processing.',
  factoryStep1Title: 'Solar Shade Drying',
  factoryStep1Description: 'Leaves are shade-dried under controlled solar chambers to protect chlorophyll and lawsone pigments from degradation.',
  factoryStep2Title: 'Micro Pulverization',
  factoryStep2Description: 'Heavy-duty food-grade stainless steel mills grind leaves into uniform fine particles without heat buildup.',
  factoryStep3Title: 'Ultra-Fine Cloth Sifting',
  factoryStep3Description: 'Milled powder passes ultra-fine micro cloth filters to eliminate any stem fibers or coarse residue.',
  factoryStep4Title: 'Vacuum Pouch Sealing',
  factoryStep4Description: 'Packed in nitrogen-flushed, multi-layer aluminum barrier pouches to prevent moisture ingress and oxidation.',

  finalCtaHeading: 'Ready To Experience Pure Sojat Henna?',
  finalCtaDescription: 'Shop our ultra-fine sifted Lawsonia Inermis mehendi, natural indigo, and herbal hair care directly from Sojat. Safe online checkout and fast doorstep delivery across India.',
  finalCtaButtonText: 'Explore All Products',
  finalCtaEnabled: true,

  // Checkout Field Config
  checkoutFieldConfig: DEFAULT_CHECKOUT_FIELD_CONFIG,

  // Delivery & Order Settings
  minOrderAmount: 0,
  shippingFee: 0,
  freeShippingThreshold: 0,
  deliveryMessage: 'Direct dispatch from Sojat City, Rajasthan via Express Courier.',

  // Footer & Legal
  footerDescription: 'Authentic 100% pure, unadulterated Lawsonia Inermis Henna & natural botanical products cultivated in Sojat, Rajasthan — the Henna Capital of India.',
  copyrightText: '© 2026 Musky Dose. All Rights Reserved. Crafted with care in Sojat, Rajasthan, India.',

  // Navigation & Footer Controls
  navItems: DEFAULT_NAV_ITEMS,
  footerSections: DEFAULT_FOOTER_SECTIONS,

  // FAQ & Policies
  faqItems: INITIAL_FAQ_ITEMS,
  shippingPolicy: {
    title: 'Shipping & Delivery Policy',
    summary: 'Direct dispatch from Sojat City, Rajasthan via express courier.',
    content: 'All Musky Dose orders are processed and packaged directly from our facility in Sojat City, Pali District, Rajasthan.\n\nDispatch Timeframe:\nOrders are dispatched within 24 to 48 business hours following WhatsApp order confirmation.\n\nShipping Charges:\nShipping charges extra / calculated on order confirmation based on destination pincode and package total weight.\n\nTracking:\nTracking details and courier tracking links will be shared directly on WhatsApp once your package is dispatched.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  returnRefundPolicy: {
    title: 'Return & Refund Policy',
    summary: 'Our policy regarding returns, damage claims, and replacements.',
    content: 'At Musky Dose, we take immense pride in delivering 100% pure, freshly processed Sojat Henna and herbal products.\n\n1. Damaged or Wrong Product Delivered:\nIf you receive a damaged pouch, leaking bottle, or wrong product item, please notify our team within 48 hours of delivery via WhatsApp (+91 82337 03080) along with an unboxing photo/video.\n\n2. Replacement & Refunds:\nOnce verified, we will immediately arrange a free replacement dispatch or issue a full refund to your original payment mode or bank account.\n\n3. Non-Returnable Items:\nDue to hygiene and botanical quality standards, opened or used powder pouches cannot be returned unless verified defective.\n\n4. Contact Us:\nFor any return assistance, message our customer support team directly on WhatsApp or email info@muskydose.in.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  privacyPolicy: {
    title: 'Privacy Policy',
    summary: 'How Musky Dose protects and respects customer personal data.',
    content: 'Musky Dose ("we", "our") respects your privacy and is committed to protecting all personal information shared during browsing and ordering.\n\n1. Information We Collect:\nWhen placing an order or enquiry, we collect your Name, Phone Number, WhatsApp Number, Email Address, and Postal Delivery Address solely for order processing and delivery fulfillment.\n\n2. How We Use Your Data:\nYour details are used strictly to process orders, generate delivery labels, send WhatsApp order tracking updates, and respond to trade enquiries. We do NOT sell, rent, or trade customer databases to third parties.\n\n3. Data Security:\nYour order details are securely stored with encrypted database backups. Access is restricted exclusively to authorized Musky Dose personnel.\n\n4. Contact Privacy Officer:\nFor data deletion requests or privacy questions, write to info@muskydose.in.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  termsConditions: {
    title: 'Terms & Conditions',
    summary: 'General terms governing website usage, WhatsApp ordering, and product supply.',
    content: 'Welcome to Musky Dose (muskydose.in). By using our website or placing orders through WhatsApp, you agree to these terms:\n\n1. Botanical Product Characteristics:\nOur henna and herbal powders are 100% natural agricultural products harvested in Sojat, Rajasthan. Minor natural color variations between seasonal crop batches are normal and signify zero chemical dye standardization.\n\n2. Pricing & Orders:\nPrices listed on the website are in Indian Rupees (₹). Orders placed via WhatsApp are confirmed once stock availability and delivery location charges are verified by our team.\n\n3. Intellectual Property:\nAll brand text, logo designs, factory imagery, and trade descriptions on muskydose.in are proprietary property of Musky Dose Enterprise.\n\n4. Jurisdiction:\nAny legal disputes arising from orders or transactions are subject to the exclusive jurisdiction of courts in Pali District, Rajasthan, India.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },
  cancellationPolicy: {
    title: 'Cancellation Policy',
    summary: 'Guidelines for order cancellation prior to dispatch.',
    content: '1. Order Cancellation Before Dispatch:\nYou may cancel your order at zero cost anytime before dispatch by sending a cancellation request with your Order Number on WhatsApp (+91 82337 03080).\n\n2. Post-Dispatch Cancellation:\nOnce an order has been picked up and handed over to express courier transport (waybill generated), it cannot be canceled in transit.\n\n3. Refund Timelines:\nApproved order cancellations before dispatch receive 100% instant refund or WhatsApp credit within 24 business hours.',
    enabled: true,
    updatedAt: new Date().toISOString().split('T')[0],
  },

  // SEO & Meta
  seoTitle: 'Musky Dose — Premium Henna & Herbal Products from Sojat, Rajasthan',
  seoDescription: 'Order Pure Natural Sojat Mehendi Powder, Natural Indigo, Herbal Hair Packs & Damask Rose Water directly from Musky Dose.',
  seoKeywords: 'Sojat Henna, Pure Mehendi, Rajasthani Henna, Natural Indigo, Herbal Hair Care, Damask Rose Water, Sojat City, Musky Dose',
  ogTitle: 'Musky Dose — Premium Henna & Herbal Care from Sojat, Rajasthan',
  ogDescription: 'Authentic 100% Pure Sojat Henna, Indigo, Hair & Skin Care directly from Sojat, Rajasthan.',
  ogImageUrl: '/images/fallback.svg',
  canonicalUrl: 'https://muskydose.in',

  // Media Library Initial
  mediaLibrary: INITIAL_MEDIA_LIBRARY,

  // Business Content & Documents Initial
  businessContentItems: INITIAL_BUSINESS_CONTENT,

  // SEO Keywords Initial Store
  seoKeywordsStore: INITIAL_SEO_KEYWORDS,

  // Feature Flags & Commerce Switches
  featureFlags: {
    onlinePaymentsEnabled: false,
    wholesaleEnabled: true,
    inventoryEnabled: false,
    customerAccountsEnabled: false,
    couponsEnabled: true,
    shippingIntegrationEnabled: false,
    invoiceEnabled: true,
    notificationsEnabled: false,
    recommendationsEnabled: true,
    analyticsEnabled: true,
    multilingualEnabled: false,
    exportModeEnabled: false,
  },

  paymentConfig: {
    provider: 'razorpay',
    enabled: false,
    mode: 'test',
    keyId: '',
    merchantName: 'Musky Dose',
  },

  shippingConfig: {
    provider: 'flat_rate',
    enabled: true,
    freeShippingThreshold: 999,
    flatRateAmount: 0,
  },

  invoiceConfig: {
    enabled: true,
    companyLegalName: 'Musky Dose Enterprise',
    registeredAddress: 'Musky Dose Products, Village: Dholiwadi Ka Bas, Post: Sojat City, District: Pali, Rajasthan – 306104, India',
    invoicePrefix: 'MD-INV-',
  },
};

export const INITIAL_PAYMENT_SETTINGS: PaymentSettings = {
  onlinePaymentEnabled: false, // CRITICAL: Always OFF by default
  whatsappOrderEnabled: true,
  upiEnabled: true,
  upiId: 'muskydose@upi',
  upiMerchantName: 'Musky Dose Enterprise',
  cardEnabled: true,
  netbankingEnabled: true,
  gatewayMode: 'sandbox',
};
